// GENERATED by scripts/tf_build.py -- do not edit.
import type { ConceptLink } from "./types";

export const CONCEPTS: ConceptLink[] = [
{"key": "self-attention", "label": "Self-Attention", "papers": ["T044", "T147", "T259", "T261", "T351", "T353", "T364"]},
{"key": "positional-encoding", "label": "Positional Encoding", "papers": ["T384"]},
{"key": "encoder-decoder", "label": "Encoder-Decoder", "papers": ["T010", "T108"]},
{"key": "pretraining", "label": "Pretraining", "papers": ["T007", "T008", "T027", "T037", "T056", "T063", "T074", "T082", "T083", "T084", "T108", "T117", "T156", "T178", "T181", "T187", "T188", "T197", "T198", "T246", "T261", "T264", "T266", "T273", "T280", "T289", "T295", "T296", "T306", "T311", "T341", "T354", "T363", "T368", "T380", "T391", "T394", "T410", "T418"]},
{"key": "scaling", "label": "Scaling", "papers": ["T096", "T250", "T260"]},
{"key": "emergence", "label": "Emergent Abilities", "papers": ["T165"]},
{"key": "in-context-learning", "label": "In-Context Learning", "papers": ["T237", "T263"]},
{"key": "instruction-tuning", "label": "Instruction Tuning", "papers": ["T239", "T383"]},
{"key": "alignment", "label": "Alignment", "papers": ["T210", "T400"]},
{"key": "prompt-tuning", "label": "Prompt Tuning", "papers": ["T032", "T086"]},
{"key": "peft", "label": "PEFT", "papers": ["T032", "T043", "T225"]},
{"key": "routing", "label": "Retrieval / RAG", "papers": ["T221", "T324", "T359"]},
{"key": "reasoning", "label": "Reasoning", "papers": ["T233", "T413"]},
{"key": "multimodal", "label": "Multimodal", "papers": ["T026", "T051", "T066", "T198", "T203", "T246", "T248", "T264", "T266", "T320", "T325", "T344", "T383"]},
{"key": "quantization", "label": "Quantization", "papers": ["T014", "T326", "T356", "T387", "T389"]},
{"key": "pruning", "label": "Pruning", "papers": ["T147", "T180", "T334", "T379"]},
{"key": "distillation", "label": "Distillation", "papers": ["T011", "T079", "T144", "T160", "T204", "T244", "T261", "T265", "T330"]},
{"key": "efficient-inference", "label": "Efficient Inference", "papers": ["T389"]},
];
