// GENERATED by scripts/tf_build.py -- do not edit.
import type { MetricLink } from "./types";

export const METRICS: MetricLink[] = [
{"key": "accuracy", "label": "Accuracy", "papers": ["T275"]},
{"key": "memory", "label": "Peak Memory", "papers": ["T065", "T129", "T149", "T159", "T176", "T358"]},
{"key": "energy", "label": "Energy", "papers": ["T023", "T282"]},
{"key": "params", "label": "Parameters", "papers": ["T258"]},
];
