/* GENERATED by scripts/neuro_simbind.py — do not edit by hand.
 *
 * Sim → corpus binding. Every id below is checked to resolve to a structured
 * record by the audit view, and each binding states what the simulator is an
 * instance of, so the mapping can be checked rather than trusted.
 */

import type { SimulatorId } from "@/labs/neuroevolution/sims";

export type SimPaper = { id: string; note: string };

// ga-demo: instance of: selection + crossover + mutation over a population
const ga_demoPapers: SimPaper[] = [
  { id: "N047", note: "instance of: selection + crossover + mutation over a population" },
  { id: "N243", note: "instance of: selection + crossover + mutation over a population" },
  { id: "N085", note: "instance of: selection + crossover + mutation over a population" },
  { id: "N096", note: "instance of: selection + crossover + mutation over a population" },
];

// locus-demo: instance of: a mutation operator applied at named loci
const locus_demoPapers: SimPaper[] = [
  { id: "N047", note: "instance of: a mutation operator applied at named loci" },
  { id: "N243", note: "instance of: a mutation operator applied at named loci" },
  { id: "N085", note: "instance of: a mutation operator applied at named loci" },
  { id: "N096", note: "instance of: a mutation operator applied at named loci" },
];

// qd-demo: instance of: quality-diversity / MAP-Elites repertoire search
const qd_demoPapers: SimPaper[] = [
  { id: "N188", note: "instance of: quality-diversity / MAP-Elites repertoire search" },
  { id: "N028", note: "instance of: quality-diversity / MAP-Elites repertoire search" },
  { id: "N255", note: "instance of: quality-diversity / MAP-Elites repertoire search" },
  { id: "N101", note: "instance of: quality-diversity / MAP-Elites repertoire search" },
];

// novelty-demo: instance of: behavioural novelty as the selection signal
const novelty_demoPapers: SimPaper[] = [
  { id: "N047", note: "instance of: behavioural novelty as the selection signal" },
  { id: "N243", note: "instance of: behavioural novelty as the selection signal" },
  { id: "N085", note: "instance of: behavioural novelty as the selection signal" },
  { id: "N096", note: "instance of: behavioural novelty as the selection signal" },
];

// encoding-demo: instance of: a stated genotype-to-phenotype encoding
const encoding_demoPapers: SimPaper[] = [
  { id: "N085", note: "instance of: a stated genotype-to-phenotype encoding" },
  { id: "N109", note: "instance of: a stated genotype-to-phenotype encoding" },
  { id: "N004", note: "instance of: a stated genotype-to-phenotype encoding" },
  { id: "N169", note: "instance of: a stated genotype-to-phenotype encoding" },
];

// topology-demo: instance of: topology changing under the search
const topology_demoPapers: SimPaper[] = [
  { id: "N047", note: "instance of: topology changing under the search" },
  { id: "N085", note: "instance of: topology changing under the search" },
  { id: "N249", note: "instance of: topology changing under the search" },
  { id: "N219", note: "instance of: topology changing under the search" },
];

// fitness-shaping: instance of: an explicitly described fitness or objective signal
const fitness_shapingPapers: SimPaper[] = [
  { id: "N243", note: "instance of: an explicitly described fitness or objective signal" },
  { id: "N085", note: "instance of: an explicitly described fitness or objective signal" },
  { id: "N096", note: "instance of: an explicitly described fitness or objective signal" },
  { id: "N109", note: "instance of: an explicitly described fitness or objective signal" },
];

// selection-pressure: instance of: an explicitly described selection scheme
const selection_pressurePapers: SimPaper[] = [
  { id: "N243", note: "instance of: an explicitly described selection scheme" },
  { id: "N096", note: "instance of: an explicitly described selection scheme" },
  { id: "N109", note: "instance of: an explicitly described selection scheme" },
  { id: "N004", note: "instance of: an explicitly described selection scheme" },
];

// es-gradient: instance of: a gradient-free evolution strategy
const es_gradientPapers: SimPaper[] = [
  { id: "N141", note: "instance of: a gradient-free evolution strategy" },
  { id: "N203", note: "instance of: a gradient-free evolution strategy" },
  { id: "N020", note: "instance of: a gradient-free evolution strategy" },
  { id: "N081", note: "instance of: a gradient-free evolution strategy" },
];

// nas-budget: instance of: architecture search under an evaluation budget
const nas_budgetPapers: SimPaper[] = [
  { id: "N249", note: "instance of: architecture search under an evaluation budget" },
  { id: "N219", note: "instance of: architecture search under an evaluation budget" },
  { id: "N227", note: "instance of: architecture search under an evaluation budget" },
  { id: "N042", note: "instance of: architecture search under an evaluation budget" },
];

export const papers: Record<SimulatorId, SimPaper[]> = {
  "ga-demo": ga_demoPapers,
  "locus-demo": locus_demoPapers,
  "qd-demo": qd_demoPapers,
  "novelty-demo": novelty_demoPapers,
  "encoding-demo": encoding_demoPapers,
  "topology-demo": topology_demoPapers,
  "fitness-shaping": fitness_shapingPapers,
  "selection-pressure": selection_pressurePapers,
  "es-gradient": es_gradientPapers,
  "nas-budget": nas_budgetPapers,
};

export const SIM_BINDINGS = papers;

/** Ids bound per simulator, for the audit view. */
export const SIM_BOUND_IDS: Record<string, string[]> = Object.fromEntries(
  Object.entries(papers).map(([k, v]) => [k, v.map((p) => p.id)]),
);
