// GENERATED by scripts/tf_build.py -- do not edit.
import type { PaperRecord } from "../types";

export const batch06: PaperRecord[] = [
  {
    "id": "T401",
    "openalex": "W4381587418",
    "arxiv": "2306.10070",
    "doi": "10.1093/bib/bbad493",
    "title": "Opportunities and challenges for ChatGPT and large language models in biomedicine and health",
    "shortTitle": "Opportunities and challenges for ChatGPT and large\u2026",
    "year": 2023,
    "venue": "Briefings in Bioinformatics",
    "authors": [
      "Shubo Tian",
      "Qiao Jin",
      "Lana Yeganova",
      "Po\u2010Ting Lai",
      "Qingqing Zhu",
      "Xiuying Chen",
      "Yifan Yang",
      "Qingyu Chen",
      "Won Bae Kim",
      "Donald C. Comeau",
      "Rezarta Islamaj",
      "Aadit Kapoor"
    ],
    "citations": 376,
    "pages": 23,
    "fileName": "W4381587418.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2306.10070",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 68041,
    "architecture": {
      "summary": "Opportunities and challenges for ChatGPT and large language models in biomedicine and health",
      "layers": [
        {
          "kind": "attention",
          "label": "Attention",
          "quote": "The transformer architecture includes an encoder of bidirectional attention blocks and a decoder of unidirectional attention blocks."
        }
      ]
    },
    "changes": [],
    "objectives": [
      {
        "kind": "accuracy",
        "label": "Task accuracy",
        "quote": "Performance of LLMs vs. human on the MedQA (USMLE) dataset in terms of accuracy."
      },
      {
        "kind": "size",
        "label": "Parameter count",
        "quote": "LLMs such as ChatGPT and GPT-4 are language models that have billions of parameters in model size and are trained with data sets containing tens or hundreds of billions of tokens."
      }
    ],
    "results": [],
    "referenceCount": 20
  },
  {
    "id": "T402",
    "openalex": "W3156978626",
    "arxiv": "2104.08541",
    "doi": "10.1109/iccv48922.2021.00179",
    "title": "TransVG: End-to-End Visual Grounding with Transformers",
    "shortTitle": "TransVG: End-to-End Visual Grounding with\u2026",
    "year": 2021,
    "venue": "2021 IEEE/CVF International Conference on Computer Vision (ICCV)",
    "authors": [
      "Jiajun Deng",
      "Zhengyuan Yang",
      "Tianlang Chen",
      "Wengang Zhou",
      "Houqiang Li"
    ],
    "citations": 372,
    "pages": 11,
    "fileName": "W3156978626.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2104.08541",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 52212,
    "architecture": {
      "summary": "TransVG: End-to-End Visual Grounding with Transformers",
      "layers": [
        {
          "kind": "embedding",
          "label": "Embedding",
          "quote": "Our linguistic branch includes a token embedding layer and a linguistic transformer."
        },
        {
          "kind": "attention",
          "label": "Attention",
          "quote": "Particularly, the core component of transformers (i.e., attention layer) is ready to establish intra-modality and inter-modality correspondence across visual and linguistic inputs, despite that we do not pre-define any specific fusion mechanism."
        },
        {
          "kind": "ffn",
          "label": "Feed-forward / MLP",
          "quote": "Concretely, each transformer encoder layer has two sublayers, i.e., a multi-head self-attention layer and a simple feed forward network (FFN)."
        },
        {
          "kind": "norm",
          "label": "Normalization",
          "quote": "Let us denote the input as xn , the procedure in a transformer encoder layer is: x0n = LN(xn + FMSA (xn )), (2) xn+1 = LN(x0n + FFFN (x0n )), (3) where LN(\u00b7) indicates layer normalization, FMSA (\u00b7) is the multi-head self-attention layer, and FFFN (\u00b7) represents the feed forward network. 3.2."
        },
        {
          "kind": "head",
          "label": "Output head",
          "quote": "The regression block is implemented by an MLP with two ReLU activated 256dim hidden layers and a linear output layer."
        }
      ]
    },
    "changes": [],
    "objectives": [],
    "results": [],
    "referenceCount": 6
  },
  {
    "id": "T403",
    "openalex": "W3034689979",
    "arxiv": "",
    "doi": "10.18653/v1/2020.acl-main.449",
    "title": "A Transformer-based Approach for Source Code Summarization",
    "shortTitle": "A Transformer-based Approach for Source Code\u2026",
    "year": 2020,
    "venue": "",
    "authors": [
      "Wasi Uddin Ahmad",
      "Saikat Chakraborty",
      "Baishakhi Ray",
      "Kai-Wei Chang"
    ],
    "citations": 372,
    "pages": 10,
    "fileName": "W3034689979.pdf",
    "pdfUrl": "https://www.aclweb.org/anthology/2020.acl-main.449.pdf",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 36819,
    "architecture": {
      "summary": "A Transformer-based Approach for Source Code Summarization",
      "layers": [
        {
          "kind": "positional",
          "label": "Positional encoding",
          "quote": "Java 69,708 8,714 8,714 66,650 46,895 120.16 17.73 where, aVij and aK ij are relative positional representations for the two position i and j."
        },
        {
          "kind": "attention",
          "label": "Attention",
          "quote": "To learn code representation for summarization, we explore the Transformer model that uses a self-attention mechanism and has shown to be effective in capturing long-range dependencies."
        }
      ]
    },
    "changes": [],
    "objectives": [
      {
        "kind": "accuracy",
        "label": "Task accuracy",
        "quote": "The result shows that the Base model outperforms the baselines (except for ROUGE-L in java), while the Full model improves the performance further.4 We ran the Base model on the original datasets (without splitting the CamelCase and snake case code tokens) and observed that the performance drops by 0.60, 0.72 BLEU and 1.66, 2.09 ROUGE-L points for the Java and Python datasets respectively."
      },
      {
        "kind": "size",
        "label": "Parameter count",
        "quote": "Intuitively, the source code summariza5 Considering the model complexity, we do not increase the model size or number of layers further. tion task depends on more semantic information than syntactic, and thus deeper model helps."
      }
    ],
    "results": [],
    "referenceCount": 22
  },
  {
    "id": "T404",
    "openalex": "W4385469325",
    "arxiv": "2305.18339",
    "doi": "10.1109/ojcs.2023.3300321",
    "title": "A Survey on ChatGPT: AI\u2013Generated Contents, Challenges, and Solutions",
    "shortTitle": "A Survey on ChatGPT: AI\u2013Generated Contents\u2026",
    "year": 2023,
    "venue": "IEEE Open Journal of the Computer Society",
    "authors": [
      "Yuntao Wang",
      "Yanghe Pan",
      "Miao Yan",
      "Zhou Su",
      "Tom H. Luan"
    ],
    "citations": 371,
    "pages": 20,
    "fileName": "W4385469325.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2305.18339",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 127905,
    "architecture": {
      "summary": "A Survey on ChatGPT: AI\u2013Generated Contents, Challenges, and Solutions",
      "layers": []
    },
    "changes": [],
    "objectives": [
      {
        "kind": "size",
        "label": "Parameter count",
        "quote": "A large AI model refers to any neural network architecture that has large number of parameters, such as large visual model (LVM), large language model (LLM), and large multimodal model."
      }
    ],
    "results": [],
    "referenceCount": 0
  },
  {
    "id": "T405",
    "openalex": "W4384389802",
    "arxiv": "2307.06435",
    "doi": "10.48550/arxiv.2307.06435",
    "title": "A Comprehensive Overview of Large Language Models",
    "shortTitle": "A Comprehensive Overview of Large Language Models",
    "year": 2023,
    "venue": "arXiv (Cornell University)",
    "authors": [
      "Humza Naveed",
      "Asad Ullah Khan",
      "Shi Qiu",
      "Muhammad Saqib",
      "Saeed Anwar",
      "Usman, Muhammad",
      "Akhtar, Naveed",
      "Nick M. Barnes",
      "Ajmal Saeed Mian"
    ],
    "citations": 368,
    "pages": 47,
    "fileName": "W4384389802.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2307.06435",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 275118,
    "architecture": {
      "summary": "A Comprehensive Overview of Large Language Models",
      "layers": [
        {
          "kind": "positional",
          "label": "Positional encoding",
          "quote": "Variants of positional embedding include absolute, relative, or learned positional encodings."
        },
        {
          "kind": "attention",
          "label": "Attention",
          "quote": "Moreover, the attention module in the transformer does not capture positional information."
        },
        {
          "kind": "router",
          "label": "MoE router",
          "quote": "Mixture-of-Experts: It is a variant of transformer architecture with parallel independent experts and a router to route tokens to experts."
        }
      ]
    },
    "changes": [
      {
        "operator": "quantization",
        "label": "Quantization",
        "quote": "Parameter efficient tuning [38, 41, 40], pruning [42, 43], quantization [44, 45], knowledge distillation, and context length interpolation [46, 47, 48, 49] among others are some of the methods widely studied for efficient LLM utilization."
      },
      {
        "operator": "pruning",
        "label": "Pruning",
        "quote": "Parameter efficient tuning [38, 41, 40], pruning [42, 43], quantization [44, 45], knowledge distillation, and context length interpolation [46, 47, 48, 49] among others are some of the methods widely studied for efficient LLM utilization."
      },
      {
        "operator": "distillation",
        "label": "Distillation",
        "quote": "Parameter efficient tuning [38, 41, 40], pruning [42, 43], quantization [44, 45], knowledge distillation, and context length interpolation [46, 47, 48, 49] among others are some of the methods widely studied for efficient LLM utilization."
      }
    ],
    "objectives": [
      {
        "kind": "size",
        "label": "Parameter count",
        "quote": "Mixture-of-Experts (MoE) is an efficient sparse architecture that offers comparable performance to dense models and allows increasing the model size without increasing the computational cost by activating only a few experts at a time [91, 92]. 2.8."
      }
    ],
    "results": [],
    "referenceCount": 1
  },
  {
    "id": "T406",
    "openalex": "W4386302153",
    "arxiv": "2308.14921",
    "doi": "10.1145/3582269.3615599",
    "title": "Gender bias and stereotypes in Large Language Models",
    "shortTitle": "Gender bias and stereotypes in Large Language Models",
    "year": 2023,
    "venue": "",
    "authors": [
      "Hadas Kotek",
      "Rikker Dockum",
      "David Sun"
    ],
    "citations": 367,
    "pages": 13,
    "fileName": "W4386302153.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2308.14921",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 76943,
    "architecture": {
      "summary": "Gender bias and stereotypes in Large Language Models",
      "layers": [
        {
          "kind": "embedding",
          "label": "Embedding",
          "quote": "Gender bias has been shown to exist in word embeddings [9, 16, 19, 31, 51, 61, 89, 100, 101, 103], as well as in a broad array of models developed specifically for various NLP tasks, such as CI \u201923, November 06\u201310, 2023, Delft, Netherlands auto-captioning, sentiment analysis, toxicity detection, machine translation, and more [46, 58, 71, 80, 83, 87, 91, 95]."
        }
      ]
    },
    "changes": [],
    "objectives": [],
    "results": [],
    "referenceCount": 15
  },
  {
    "id": "T407",
    "openalex": "W4391301614",
    "arxiv": "2309.00087",
    "doi": "10.7326/m23-2772",
    "title": "Large Language Models in Medicine: The Potentials and Pitfalls",
    "shortTitle": "Large Language Models in Medicine: The Potentials\u2026",
    "year": 2023,
    "venue": "Annals of Internal Medicine",
    "authors": [
      "Jesutofunmi A. Omiye",
      "Haiwen Gui",
      "Shawheen J. Rezaei",
      "James Zou",
      "Roxana Daneshjou"
    ],
    "citations": 367,
    "pages": 19,
    "fileName": "W4391301614.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2309.00087",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 52826,
    "architecture": {
      "summary": "Large Language Models in Medicine: The Potentials and Pitfalls",
      "layers": [
        {
          "kind": "attention",
          "label": "Attention",
          "quote": "A deep learning model architecture that relies on self-attention mechanisms, by differentially weighting the importance of each part of the model\u2019s input."
        }
      ]
    },
    "changes": [
      {
        "operator": "calibration",
        "label": "Calibration",
        "quote": "As LLMs continue to scale up with larger parameter counts, they appear likely to implicitly learn useful biological and clinical knowledge, evidenced by models like Med-PaLM demonstrating improved accuracy, calibration, and physician-like responses."
      }
    ],
    "objectives": [
      {
        "kind": "accuracy",
        "label": "Task accuracy",
        "quote": "As LLMs continue to scale up with larger parameter counts, they appear likely to implicitly learn useful biological and clinical knowledge, evidenced by models like Med-PaLM demonstrating improved accuracy, calibration, and physician-like responses."
      },
      {
        "kind": "size",
        "label": "Parameter count",
        "quote": "As LLMs continue to scale up with larger parameter counts, they appear likely to implicitly learn useful biological and clinical knowledge, evidenced by models like Med-PaLM demonstrating improved accuracy, calibration, and physician-like responses."
      }
    ],
    "results": [],
    "referenceCount": 32
  },
  {
    "id": "T408",
    "openalex": "W4389524555",
    "arxiv": "",
    "doi": "10.18653/v1/2023.findings-emnlp.936",
    "title": "RWKV: Reinventing RNNs for the Transformer Era",
    "shortTitle": "RWKV: Reinventing RNNs for the Transformer Era",
    "year": 2023,
    "venue": "",
    "authors": [
      "Bo Peng",
      "Eric Alcaide",
      "Quentin G. Anthony",
      "Alon Albalak",
      "Samuel Arcadinho",
      "Stella Biderman",
      "Huanqi Cao",
      "Xin Cheng",
      "Michael Chung",
      "Leon Derczynski",
      "Xingjian Du",
      "Matteo Grella"
    ],
    "citations": 367,
    "pages": 30,
    "fileName": "W4389524555.pdf",
    "pdfUrl": "https://aclanthology.org/2023.findings-emnlp.936.pdf",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 90920,
    "architecture": {
      "summary": "RWKV: Reinventing RNNs for the Transformer Era",
      "layers": [
        {
          "kind": "embedding",
          "label": "Embedding",
          "quote": "LayerNorm LayerNorm RWKV-LM Head Attn(Q, K, V )t = PT Output Probabilities Channel Mixing LayerNorm Input Embedding Figure 2: Elements within an RWKV block (left) and the complete RWKV residual block, equipped with a final head for language modeling (right). softmax operation improving numerical stability and mitigating vanishing gradients (for rigorous proof, see Appendix H)."
        },
        {
          "kind": "positional",
          "label": "Positional encoding",
          "quote": "Each wt,i in RWKV is a channelwise time decay vector multiplied by the relative position and traced backward from current time as it decays: (10) where w \u2208 (R\u22650 )d , with d the number of channels."
        },
        {
          "kind": "attention",
          "label": "Attention",
          "quote": "Our approach leverages a linear attention mechanism and allows us to formulate the model as either a Transformer or an RNN, thus parallelizing computations during training and maintains constant computational and memory complexity during inference."
        },
        {
          "kind": "norm",
          "label": "Normalization",
          "quote": "Time Mix Layer Norm Layer Norm Layer Norm Layer Norm My name is 3.2 Figure 3: RWKV architecture for language modeling. as are the channel-mixing inputs: rt\u2032 = Wr\u2032 \u00b7 (\u00b5\u2032r \u2299 xt + (1 \u2212 \u00b5\u2032r ) \u2299 xt\u22121 ), kt\u2032 = Wk\u2032 \u00b7 (\u00b5\u2032k \u2299 xt + (1 \u2212 \u00b5\u2032k ) \u2299 xt\u22121 )."
        },
        {
          "kind": "head",
          "label": "Output head",
          "quote": "LayerNorm LayerNorm RWKV-LM Head Attn(Q, K, V )t = PT Output Probabilities Channel Mixing LayerNorm Input Embedding Figure 2: Elements within an RWKV block (left) and the complete RWKV residual block, equipped with a final head for language modeling (right). softmax operation improving numerical stability and mitigating vanishing gradients (for rigorous proof, see Appendix H)."
        }
      ]
    },
    "changes": [
      {
        "operator": "quantization",
        "label": "Quantization",
        "quote": "Performance under different quantization setups is left to further work."
      },
      {
        "operator": "attention-approximation",
        "label": "Attention approximation",
        "quote": "Our approach leverages a linear attention mechanism and allows us to formulate the model as either a Transformer or an RNN, thus parallelizing computations during training and maintains constant computational and memory complexity during inference."
      }
    ],
    "objectives": [
      {
        "kind": "accuracy",
        "label": "Task accuracy",
        "quote": "This work presents a significant step towards reconciling trade-offs between computational efficiency and model performance in sequence processing tasks. 1 1 Accuracy 55 Equal first authorship."
      },
      {
        "kind": "perplexity",
        "label": "Perplexity",
        "quote": "This kernel enables the execution of a single compute kernel on training accelerators, while all other parts of the model, such as matrix multiplications and point-wise operations, are already inherently parallelizable and efficient. for next-token prediction and computation of the cross-entropy loss during training."
      },
      {
        "kind": "size",
        "label": "Parameter count",
        "quote": "The number of parameters for each model is computed using the formula: # parameters = 2V D + 13D2 L + D(11L + 4) where V = 50277 is the vocabulary size, D represents the Model Dimension and L corresponds to the number of layers."
      }
    ],
    "results": [
      {
        "dataset": "pile",
        "label": "The Pile",
        "quote": "All RWKV models were trained for one epoch on the Pile (330B tokens), which is close but not identical to the amount of tokens the Pythia, OPT, and BLOOM models were trained for."
      }
    ],
    "referenceCount": 32
  },
  {
    "id": "T409",
    "openalex": "W2947609478",
    "arxiv": "",
    "doi": "10.1017/s0140525x19001213",
    "title": "Thinking through other minds: A variational approach to cognition and culture",
    "shortTitle": "Thinking through other minds: A variational\u2026",
    "year": 2019,
    "venue": "Behavioral and Brain Sciences",
    "authors": [
      "Samuel P. L. Veissi\u00e8re",
      "Axel Constant",
      "Maxwell J. D. Ramstead",
      "Karl John Friston",
      "Laurence J. Kirmayer"
    ],
    "citations": 367,
    "pages": 97,
    "fileName": "W2947609478.pdf",
    "pdfUrl": "https://discovery.ucl.ac.uk/10075929/1/thinking_through_other_minds_a_variational_approach_to_cognition_and_culture.pdf",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 208095,
    "architecture": {
      "summary": "Thinking through other minds: A variational approach to cognition and culture",
      "layers": []
    },
    "changes": [],
    "objectives": [
      {
        "kind": "energy",
        "label": "Energy",
        "quote": "We integrate these candidates using the variational (free energy) approach to human cognition and culture in theoretical neuroscience."
      }
    ],
    "results": [],
    "referenceCount": 39
  },
  {
    "id": "T410",
    "openalex": "W2962785754",
    "arxiv": "",
    "doi": "10.18653/v1/p19-1499",
    "title": "HIBERT: Document Level Pre-training of Hierarchical Bidirectional Transformers for Document Summarization",
    "shortTitle": "HIBERT: Document Level Pre-training of Hierarchical\u2026",
    "year": 2019,
    "venue": "",
    "authors": [
      "Xingxing Zhang",
      "Furu Wei",
      "Ming Zhou"
    ],
    "citations": 366,
    "pages": 11,
    "fileName": "W2962785754.pdf",
    "pdfUrl": "https://www.aclweb.org/anthology/P19-1499.pdf",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 44266,
    "architecture": {
      "summary": "HIBERT: Document Level Pre-training of Hierarchical Bidirectional Transformers for Document Summarization",
      "layers": [
        {
          "kind": "embedding",
          "label": "Embedding",
          "quote": "The resulting word embedding table can be used in other downstream tasks."
        },
        {
          "kind": "positional",
          "label": "Positional encoding",
          "quote": "To learn the reprei ) is first sentation of Si , Si = (w1i , w2i , . . . , w|S i| mapped into continuous space Ei = (ei1 , ei2 , . . . , ei|Si | ) where eij = e(wji ) + pj (1) where e(wji ) and pj are the word and positional embeddings of wji , respectively."
        },
        {
          "kind": "attention",
          "label": "Attention",
          "quote": "The original decoder employs two multi-head attention layers to 2 There might be multiple sentences selected in a document, but in this example there is only one. 5062 include both the context in encoder and decoder, while we only need one to learn the decoder context, since the context in encoder is a vector (i.e., d\u02dck )."
        }
      ]
    },
    "changes": [],
    "objectives": [
      {
        "kind": "accuracy",
        "label": "Task accuracy",
        "quote": "We apply the pre-trained H IBERT to our summarization model and it outperforms its randomly initialized counterpart by 1.25 ROUGE on the CNN/Dailymail dataset and by 2.0 ROUGE on a version of New York Times dataset."
      },
      {
        "kind": "perplexity",
        "label": "Perplexity",
        "quote": "In pre-training stages, we trained our models until validation perplexities do not decrease significantly (around 45 epochs on GIGA-CM dataset and 100 to 200 epochs on CNNDM and NYT50)."
      },
      {
        "kind": "size",
        "label": "Parameter count",
        "quote": "We mainly trained two model sizes: H IBERTS (L = 6, H = 512 and A = 8) and H IBERTM (L = 6, H = 768 and A = 12)."
      }
    ],
    "results": [],
    "referenceCount": 21
  },
  {
    "id": "T411",
    "openalex": "W4400118952",
    "arxiv": "2307.16376",
    "doi": "10.1007/s11280-024-01276-1",
    "title": "When large language models meet personalization: perspectives of challenges and opportunities",
    "shortTitle": "When large language models meet personalization\u2026",
    "year": 2023,
    "venue": "World Wide Web",
    "authors": [
      "Jing Chen",
      "Zheng Liu",
      "Xu Huang",
      "Chenwang Wu",
      "Qi Liu",
      "Gangwei Jiang",
      "Yuanhao Pu",
      "Yuxuan Lei",
      "Xiaolong Chen",
      "Xingmei Wang",
      "Kai Zheng",
      "Defu Lian"
    ],
    "citations": 360,
    "pages": 24,
    "fileName": "W4400118952.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2307.16376",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 156908,
    "architecture": {
      "summary": "When large language models meet personalization: perspectives of challenges and opportunities",
      "layers": []
    },
    "changes": [],
    "objectives": [],
    "results": [],
    "referenceCount": 0
  },
  {
    "id": "T412",
    "openalex": "W4328049044",
    "arxiv": "2210.13966",
    "doi": "10.1073/pnas.2215907120",
    "title": "The debate over understanding in AI\u2019s large language models",
    "shortTitle": "The debate over understanding in AI\u2019s large\u2026",
    "year": 2022,
    "venue": "Proceedings of the National Academy of Sciences",
    "authors": [
      "Melanie Mitchell",
      "David C. Krakauer"
    ],
    "citations": 342,
    "pages": 13,
    "fileName": "W4328049044.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2210.13966",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 35525,
    "architecture": {
      "summary": "The debate over understanding in AI\u2019s large language models",
      "layers": []
    },
    "changes": [],
    "objectives": [],
    "results": [],
    "referenceCount": 15
  },
  {
    "id": "T413",
    "openalex": "W4385570088",
    "arxiv": "",
    "doi": "10.18653/v1/2023.acl-long.147",
    "title": "Plan-and-Solve Prompting: Improving Zero-Shot Chain-of-Thought Reasoning by Large Language Models",
    "shortTitle": "Plan-and-Solve Prompting: Improving Zero-Shot\u2026",
    "year": 2023,
    "venue": "",
    "authors": [
      "Lei Wang",
      "Wanyu Xu",
      "Yihuai Lan",
      "Zhiqiang Hu",
      "Yunshi Lan",
      "Roy Ka-Wei Lee",
      "Ee\u2010Peng Lim"
    ],
    "citations": 326,
    "pages": 26,
    "fileName": "W4385570088.pdf",
    "pdfUrl": "https://aclanthology.org/2023.acl-long.147.pdf",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 72861,
    "architecture": {
      "summary": "Plan-and-Solve Prompting: Improving Zero-Shot Chain-of-Thought Reasoning by Large Language Models",
      "layers": []
    },
    "changes": [],
    "objectives": [
      {
        "kind": "accuracy",
        "label": "Task accuracy",
        "quote": "To tackle multi-step reasoning tasks, few-shot chain-of-thought (CoT) prompting includes a few manually crafted step-by-step reasoning demonstrations which enable LLMs to explicitly generate reasoning steps and improve their reasoning task accuracy."
      }
    ],
    "results": [
      {
        "dataset": "gsm8k",
        "label": "GSM8K",
        "quote": "The code can be found at https://github.com/AGIEdgerunners/Plan-and-Solve-Prompting. 1 Ratio (%) 30 27 20 15 5 12 7 Figure 1: Error analysis of 46 GSM8K problems with incorrect answers returned by Zero-shot-CoT using GPT3 LLM."
      }
    ],
    "referenceCount": 54
  },
  {
    "id": "T414",
    "openalex": "W3016489761",
    "arxiv": "",
    "doi": "10.3389/fncom.2020.00029",
    "title": "Attention in Psychology, Neuroscience, and Machine Learning",
    "shortTitle": "Attention in Psychology, Neuroscience, and Machine\u2026",
    "year": 2020,
    "venue": "Frontiers in Computational Neuroscience",
    "authors": [
      "Grace W. Lindsay"
    ],
    "citations": 318,
    "pages": 21,
    "fileName": "W3016489761.pdf",
    "pdfUrl": "https://www.frontiersin.org/articles/10.3389/fncom.2020.00029/pdf",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 126073,
    "architecture": {
      "summary": "Attention in Psychology, Neuroscience, and Machine Learning",
      "layers": []
    },
    "changes": [
      {
        "operator": "architecture-search",
        "label": "Architecture search",
        "quote": "It is the taking possession by the mind, in clear, and vivid form, of one out of what seems several simultaneously possible objects or trains of thought.\u201d Since James wrote this, many attempts have been made to more precisely define and quantify this process while also identifying the underlying mental and neural architectures that give rise to it."
      }
    ],
    "objectives": [],
    "results": [],
    "referenceCount": 26
  },
  {
    "id": "T415",
    "openalex": "W3154632195",
    "arxiv": "2104.07059",
    "doi": "10.1016/j.conb.2021.10.010",
    "title": "Neural population geometry: An approach for understanding biological and artificial neural networks",
    "shortTitle": "Neural population geometry: An approach for\u2026",
    "year": 2021,
    "venue": "Current Opinion in Neurobiology",
    "authors": [
      "SueYeon Chung",
      "L. F. Abbott"
    ],
    "citations": 312,
    "pages": 15,
    "fileName": "W3154632195.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2104.07059",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 38174,
    "architecture": {
      "summary": "Neural population geometry: An approach for understanding biological and artificial neural networks",
      "layers": []
    },
    "changes": [],
    "objectives": [],
    "results": [],
    "referenceCount": 44
  },
  {
    "id": "T416",
    "openalex": "W4361866125",
    "arxiv": "2303.17564",
    "doi": "10.48550/arxiv.2303.17564",
    "title": "BloombergGPT: A Large Language Model for Finance",
    "shortTitle": "BloombergGPT: A Large Language Model for Finance",
    "year": 2023,
    "venue": "RePEc: Research Papers in Economics",
    "authors": [
      "Shijie Wu",
      "Ozan \u0130rsoy",
      "Steven Z. Lu",
      "Vadim Dabravolski",
      "Mark H. Dredze",
      "Sebastian Gehrmann",
      "Prabhanjan Kambadur",
      "David Rosenberg",
      "Mann, Gideon"
    ],
    "citations": 302,
    "pages": 76,
    "fileName": "W4361866125.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2303.17564",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 204897,
    "architecture": {
      "summary": "BloombergGPT: A Large Language Model for Finance",
      "layers": [
        {
          "kind": "tokenizer",
          "label": "Tokenizer",
          "quote": "We take a different approach and use a Unigram model instead of greedy merge-based sub-word tokenizers since it saves probabilities allowing for smarter tokenization at inference time (Kudo, 2018)."
        },
        {
          "kind": "ffn",
          "label": "Feed-forward / MLP",
          "quote": "A.4 FeedForwardNetwork (FFN) . . . . . . . . . . . . . . . . . . . . . . . . . . ."
        }
      ]
    },
    "changes": [],
    "objectives": [],
    "results": [
      {
        "dataset": "c4",
        "label": "C4",
        "quote": "Although it overlaps with Pile-CC, C4 is cleaned and processed differently; hence, we feel that including C4 in addition to The Pile can add value more than duplicated documents would."
      },
      {
        "dataset": "pile",
        "label": "The Pile",
        "quote": "We include The Pile in our training data for the following reasons."
      }
    ],
    "referenceCount": 35
  },
  {
    "id": "T417",
    "openalex": "W4317553041",
    "arxiv": "2301.07597",
    "doi": "10.48550/arxiv.2301.07597",
    "title": "How Close is ChatGPT to Human Experts? Comparison Corpus, Evaluation, and Detection",
    "shortTitle": "How Close is ChatGPT to Human Experts? Comparison\u2026",
    "year": 2023,
    "venue": "arXiv (Cornell University)",
    "authors": [
      "Biyang Guo",
      "Xin Zhang",
      "Ziyuan Wang",
      "Minqi Jiang",
      "Jinran Nie",
      "Yuxuan Ding",
      "Yue, Jianwei",
      "Wu, Yupeng"
    ],
    "citations": 296,
    "pages": 20,
    "fileName": "W4317553041.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2301.07597",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 68660,
    "architecture": {
      "summary": "How Close is ChatGPT to Human Experts? Comparison Corpus, Evaluation, and Detection",
      "layers": []
    },
    "changes": [],
    "objectives": [
      {
        "kind": "accuracy",
        "label": "Task accuracy",
        "quote": "We conducted comprehensive human evaluations and linguistic analyses of ChatGPT-generated content compared with that of humans, where many interesting results are revealed."
      }
    ],
    "results": [],
    "referenceCount": 7
  },
  {
    "id": "T418",
    "openalex": "W4303443398",
    "arxiv": "2210.02414",
    "doi": "10.48550/arxiv.2210.02414",
    "title": "GLM-130B: An Open Bilingual Pre-trained Model",
    "shortTitle": "GLM-130B: An Open Bilingual Pre-trained Model",
    "year": 2022,
    "venue": "arXiv (Cornell University)",
    "authors": [
      "Aohan Zeng",
      "Xiao Liu",
      "Zhengxiao Du",
      "Zihan Wang",
      "Hanyu Lai",
      "Ming Ding",
      "Zhuoyi Yang",
      "Yifan Xu",
      "Wendi Zheng",
      "Xiao Lan Xia",
      "Weng Lam Tam",
      "Zixuan Ma"
    ],
    "citations": 293,
    "pages": 56,
    "fileName": "W4303443398.pdf",
    "pdfUrl": "https://arxiv.org/pdf/2210.02414",
    "relevance": "transformers",
    "abstractNote": "",
    "textChars": 184436,
    "architecture": {
      "summary": "GLM-130B: An Open Bilingual Pre-trained Model",
      "layers": [
        {
          "kind": "embedding",
          "label": "Embedding",
          "quote": "To avoid insufficient memory utilization in the middle stages due to the additional word embedding at both ends, we balance the pipeline partition by removing one layer from them, making 9\u00d78-2=70 transformer layers in GLM-130B."
        },
        {
          "kind": "positional",
          "label": "Positional encoding",
          "quote": "We empirically test different options for positional encoding (PE) and FFN improvements in terms of both training stability and downstream performance (Cf."
        },
        {
          "kind": "ffn",
          "label": "Feed-forward / MLP",
          "quote": "Specifically, given the number of GLM-130B\u2019s layers N , we adopt DeepNorm(x) = 1 LayerNorm(\u03b1 \u00b7 x + Network(x)), where \u03b1 = (2N ) 2 , and apply the Xavier normal initialization 1 with the scaling factor of (2N )\u2212 2 to ffn, v_proj and out_proj."
        },
        {
          "kind": "norm",
          "label": "Normalization",
          "quote": "(LN: layer norm.; FPF: floating-point format; MIP: multi-task instruction pre-training; CN : Chinese) Architecture & Data Opensource Objective LN GPT-3 175B OPT-175B BLOOM-176B \u00d7 \u2713 \u2713 GPT Pre-LN PaLM 540B \u00d7 GPT Pre-LN GLM-130B \u2713 Model GLM (Blank DeepInfilling & MIP) Norm Training Major Lang."
        }
      ]
    },
    "changes": [
      {
        "operator": "quantization",
        "label": "Quantization",
        "quote": "Finally, we leverage a unique scaling property of GLM-130B to reach INT4 quantization without post training, with almost no performance loss, making it the first among 100B-scale models and more importantly, allowing its effective inference on 4\u00d7RTX 3090 (24G) or 8\u00d7RTX 2080 Ti (11G) GPUs, the most affordable GPUs required for using 100B-scale models."
      },
      {
        "operator": "mixed-precision",
        "label": "Mixed precision",
        "quote": "We aim to enable our 100B-scale LLM to run a single DGX-A100 (40G) node in FP16 precision."
      }
    ],
    "objectives": [
      {
        "kind": "accuracy",
        "label": "Task accuracy",
        "quote": "Empirically, GLM-130B offers a record-high accuracy of 80.2% on zero-shot LAMBADA by outperforming both GPT-3 and PaLM 540B in Figure 2."
      },
      {
        "kind": "latency",
        "label": "Latency",
        "quote": "Figure 4 (b) suggests that empirically, setting \u03b1 = 0.1 wipes out most spikes we would have met, with negligible latency."
      },
      {
        "kind": "memory",
        "label": "Memory / footprint",
        "quote": "To further handle the huge GPU memory requirement and the decrease in overall GPU utilization resulted from applying tensor parallel between nodes\u2014as 40G rather than 80G A100s are used for training GLM-130B, we combine the pipeline model parallelism with the other two strategies to form a 3D parallel strategy."
      },
      {
        "kind": "size",
        "label": "Parameter count",
        "quote": "Based on the hidden state dimension of 12,288 we adopt from GPT-3, the resultant model size has to be no more than 130B parameters, thus GLM-130B."
      }
    ],
    "results": [
      {
        "dataset": "mmlu",
        "label": "MMLU",
        "quote": "Due to a unique property of the GLM architecture, GLM-130B\u2019s INT4 quantization introduces negligible performance degradation, e.g., -0.74% on LAMBADA and even +0.05% on MMLU, making it still better than the uncompressed GPT-3."
      },
      {
        "dataset": "lambada",
        "label": "LAMBADA",
        "quote": "Due to a unique property of the GLM architecture, GLM-130B\u2019s INT4 quantization introduces negligible performance degradation, e.g., -0.74% on LAMBADA and even +0.05% on MMLU, making it still better than the uncompressed GPT-3."
      }
    ],
    "referenceCount": 0
  },
];
