// GENERATED by scripts/networking_manifest.py — do not edit by hand.
export const MANIFEST = {
 "total": 300,
 "window": "2011–2023",
 "totalCitations": 425328,
 "papers": [
  {
   "id": "N001",
   "title": "Internet of Things (IoT): A vision, architectural elements, and future directions",
   "year": 2013,
   "citations": 12328,
   "fileName": "",
   "doi": "10.1016/j.future.2013.01.010",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N002",
   "title": "Edge Computing: Vision and Challenges",
   "year": 2016,
   "citations": 8668,
   "fileName": "",
   "doi": "10.1109/jiot.2016.2579198",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N003",
   "title": "Internet of Things: A Survey on Enabling Technologies, Protocols, and Applications",
   "year": 2015,
   "citations": 8667,
   "fileName": "",
   "doi": "10.1109/comst.2015.2444095",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N004",
   "title": "Convergence Culture: Where Old and New Media Collide",
   "year": 2017,
   "citations": 6962,
   "fileName": "",
   "doi": "10.7551/mitpress/9780262036016.003.0012",
   "venue": "The MIT Press eBooks"
  },
  {
   "id": "N005",
   "title": "Internet of Things for Smart Cities",
   "year": 2014,
   "citations": 6359,
   "fileName": "",
   "doi": "10.1109/jiot.2014.2306328",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N006",
   "title": "Fog computing and its role in the internet of things",
   "year": 2012,
   "citations": 6121,
   "fileName": "",
   "doi": "10.1145/2342509.2342513",
   "venue": ""
  },
  {
   "id": "N007",
   "title": "A Survey on Mobile Edge Computing: The Communication Perspective",
   "year": 2017,
   "citations": 5716,
   "fileName": "",
   "doi": "10.1109/comst.2017.2745201",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N008",
   "title": "Software-Defined Networking: A Comprehensive Survey",
   "year": 2014,
   "citations": 5043,
   "fileName": "",
   "doi": "10.1109/jproc.2014.2371999",
   "venue": "Proceedings of the IEEE"
  },
  {
   "id": "N009",
   "title": "Toward Generating a New Intrusion Detection Dataset and Intrusion Traffic Characterization",
   "year": 2018,
   "citations": 4766,
   "fileName": "",
   "doi": "10.5220/0006639801080116",
   "venue": "International Conference on Information Systems Security and Privacy (ICISSP)"
  },
  {
   "id": "N010",
   "title": "UNSW-NB15: a comprehensive data set for network intrusion detection systems (UNSW-NB15 network data set)",
   "year": 2015,
   "citations": 3977,
   "fileName": "",
   "doi": "10.1109/milcis.2015.7348942",
   "venue": "Military Communications and Information Systems Conference"
  },
  {
   "id": "N011",
   "title": "Internet of things: Vision, applications and research challenges",
   "year": 2012,
   "citations": 3613,
   "fileName": "",
   "doi": "10.1016/j.adhoc.2012.02.016",
   "venue": "Ad Hoc Networks"
  },
  {
   "id": "N012",
   "title": "Information Theory: Coding Theorems for Discrete Memoryless Systems",
   "year": 2014,
   "citations": 3354,
   "fileName": "",
   "doi": "",
   "venue": "REAL-EOD (Library of the Hungarian Academy of Sciences and the Information Center Oriental Collection)"
  },
  {
   "id": "N013",
   "title": "A Survey of Data Mining and Machine Learning Methods for Cyber Security Intrusion Detection",
   "year": 2015,
   "citations": 3316,
   "fileName": "",
   "doi": "10.1109/comst.2015.2494502",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N014",
   "title": "ERROR DETECTING AND ERROR CORRECTING CODES",
   "year": 2014,
   "citations": 3226,
   "fileName": "",
   "doi": "",
   "venue": ""
  },
  {
   "id": "N015",
   "title": "Mobile Edge Computing: A Survey on Architecture and Computation Offloading",
   "year": 2017,
   "citations": 3109,
   "fileName": "10.1109_comst.2017.2682318.pdf",
   "doi": "10.1109/comst.2017.2682318",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N016",
   "title": "P4",
   "year": 2014,
   "citations": 2889,
   "fileName": "",
   "doi": "10.1145/2656877.2656890",
   "venue": "ACM SIGCOMM Computer Communication Review"
  },
  {
   "id": "N017",
   "title": "A Survey on Internet of Things: Architecture, Enabling Technologies, Security and Privacy, and Applications",
   "year": 2017,
   "citations": 2820,
   "fileName": "",
   "doi": "10.1109/jiot.2017.2683200",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N018",
   "title": "The Emergence of Edge Computing",
   "year": 2017,
   "citations": 2791,
   "fileName": "",
   "doi": "10.1109/mc.2017.9",
   "venue": "Computer"
  },
  {
   "id": "N019",
   "title": "Network Information Theory",
   "year": 2011,
   "citations": 2729,
   "fileName": "",
   "doi": "10.1017/cbo9781139030687",
   "venue": "Cambridge University Press eBooks"
  },
  {
   "id": "N020",
   "title": "Efficient Multi-User Computation Offloading for Mobile-Edge Cloud Computing",
   "year": 2015,
   "citations": 2708,
   "fileName": "",
   "doi": "10.1109/tnet.2015.2487344",
   "venue": "IEEE/ACM Transactions on Networking"
  },
  {
   "id": "N021",
   "title": "RPL: IPv6 Routing Protocol for Low-Power and Lossy Networks",
   "year": 2012,
   "citations": 2686,
   "fileName": "",
   "doi": "10.17487/rfc6550",
   "venue": ""
  },
  {
   "id": "N022",
   "title": "The Culture of Connectivity",
   "year": 2013,
   "citations": 2639,
   "fileName": "",
   "doi": "10.1093/acprof:oso/9780199970773.001.0001",
   "venue": ""
  },
  {
   "id": "N023",
   "title": "IoT security: Review, blockchain solutions, and open challenges",
   "year": 2017,
   "citations": 2508,
   "fileName": "",
   "doi": "10.1016/j.future.2017.11.022",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N024",
   "title": "Real-time status: How often should one update?",
   "year": 2012,
   "citations": 2508,
   "fileName": "",
   "doi": "10.1109/infcom.2012.6195689",
   "venue": "IEEE Conference on Computer Communications (INFOCOM)"
  },
  {
   "id": "N025",
   "title": "Mobile Edge Computing: A Survey",
   "year": 2017,
   "citations": 2507,
   "fileName": "",
   "doi": "10.1109/jiot.2017.2750180",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N026",
   "title": "Edge Intelligence: Paving the Last Mile of Artificial Intelligence With Edge Computing",
   "year": 2019,
   "citations": 2422,
   "fileName": "",
   "doi": "10.1109/jproc.2019.2918951",
   "venue": "Proceedings of the IEEE"
  },
  {
   "id": "N027",
   "title": "Fog and IoT: An Overview of Research Opportunities",
   "year": 2016,
   "citations": 2414,
   "fileName": "",
   "doi": "10.1109/jiot.2016.2584538",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N028",
   "title": "A survey of mobile cloud computing: architecture, applications, and approaches",
   "year": 2011,
   "citations": 2410,
   "fileName": "",
   "doi": "10.1002/wcm.1203",
   "venue": "Wireless Communications and Mobile Computing"
  },
  {
   "id": "N029",
   "title": "Integration of Cloud computing and Internet of Things: A survey",
   "year": 2015,
   "citations": 2405,
   "fileName": "",
   "doi": "10.1016/j.future.2015.09.021",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N030",
   "title": "The internet of things: a survey",
   "year": 2014,
   "citations": 2299,
   "fileName": "",
   "doi": "10.1007/s10796-014-9492-7",
   "venue": "Information Systems Frontiers"
  },
  {
   "id": "N031",
   "title": "Named data networking",
   "year": 2014,
   "citations": 2235,
   "fileName": "",
   "doi": "10.1145/2656877.2656887",
   "venue": "ACM SIGCOMM Computer Communication Review"
  },
  {
   "id": "N032",
   "title": "A Survey of Software-Defined Networking: Past, Present, and Future of Programmable Networks",
   "year": 2014,
   "citations": 2210,
   "fileName": "",
   "doi": "10.1109/surv.2014.012214.00180",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N033",
   "title": "Security, privacy and trust in Internet of Things: The road ahead",
   "year": 2014,
   "citations": 2199,
   "fileName": "",
   "doi": "10.1016/j.comnet.2014.11.008",
   "venue": "Computer Networks"
  },
  {
   "id": "N034",
   "title": "The culture of connectivity: a critical history of social media",
   "year": 2013,
   "citations": 2158,
   "fileName": "",
   "doi": "10.5860/choice.50-6579",
   "venue": "Choice Reviews Online"
  },
  {
   "id": "N035",
   "title": "Consensus Problems on Networks With Antagonistic Interactions",
   "year": 2012,
   "citations": 2142,
   "fileName": "",
   "doi": "10.1109/tac.2012.2224251",
   "venue": "IEEE Transactions on Automatic Control"
  },
  {
   "id": "N036",
   "title": "A Deep Learning Approach for Intrusion Detection Using Recurrent Neural Networks",
   "year": 2017,
   "citations": 2096,
   "fileName": "",
   "doi": "10.1109/access.2017.2762418",
   "venue": "IEEE Access"
  },
  {
   "id": "N037",
   "title": "Survey of intrusion detection systems: techniques, datasets and challenges",
   "year": 2019,
   "citations": 1989,
   "fileName": "",
   "doi": "10.1186/s42400-019-0038-7",
   "venue": "Cybersecurity"
  },
  {
   "id": "N038",
   "title": "Towards the development of realistic botnet dataset in the Internet of Things for network forensic analytics: Bot-IoT dataset",
   "year": 2019,
   "citations": 1962,
   "fileName": "10.1016_j.future.2019.05.041.pdf",
   "doi": "10.1016/j.future.2019.05.041",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N039",
   "title": "Network Function Virtualization: State-of-the-Art and Research Challenges",
   "year": 2015,
   "citations": 1952,
   "fileName": "10.1109_comst.2015.2477041.pdf",
   "doi": "10.1109/comst.2015.2477041",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N040",
   "title": "Research Directions for the Internet of Things",
   "year": 2014,
   "citations": 1947,
   "fileName": "",
   "doi": "10.1109/jiot.2014.2312291",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N041",
   "title": "Deep Learning Approach for Intelligent Intrusion Detection System",
   "year": 2019,
   "citations": 1941,
   "fileName": "",
   "doi": "10.1109/access.2019.2895334",
   "venue": "IEEE Access"
  },
  {
   "id": "N042",
   "title": "Stream Control Transmission Protocol",
   "year": 2022,
   "citations": 1925,
   "fileName": "",
   "doi": "10.17487/rfc9260",
   "venue": ""
  },
  {
   "id": "N043",
   "title": "DDoS in the IoT: Mirai and Other Botnets",
   "year": 2017,
   "citations": 1909,
   "fileName": "",
   "doi": "10.1109/mc.2017.201",
   "venue": "Computer"
  },
  {
   "id": "N044",
   "title": "The tail at scale",
   "year": 2013,
   "citations": 1865,
   "fileName": "",
   "doi": "10.1145/2408776.2408794",
   "venue": "Communications of the ACM"
  },
  {
   "id": "N045",
   "title": "The Transport Layer Security (TLS) Protocol Version 1.3",
   "year": 2018,
   "citations": 1855,
   "fileName": "",
   "doi": "10.17487/rfc8446",
   "venue": ""
  },
  {
   "id": "N046",
   "title": "Fundamental Limits of Caching",
   "year": 2014,
   "citations": 1844,
   "fileName": "",
   "doi": "10.1109/tit.2014.2306938",
   "venue": "IEEE Transactions on Information Theory"
  },
  {
   "id": "N047",
   "title": "A Deep Learning Approach to Network Intrusion Detection",
   "year": 2018,
   "citations": 1832,
   "fileName": "10.1109_tetci.2017.2772792.pdf",
   "doi": "10.1109/tetci.2017.2772792",
   "venue": "IEEE Transactions on Emerging Topics in Computational Intelligence"
  },
  {
   "id": "N048",
   "title": "DeepLog",
   "year": 2017,
   "citations": 1823,
   "fileName": "",
   "doi": "10.1145/3133956.3134015",
   "venue": "ACM SIGSAC Conference on Computer and Communications Security (CCS)"
  },
  {
   "id": "N049",
   "title": "Deep Learning in Mobile and Wireless Networking: A Survey",
   "year": 2019,
   "citations": 1821,
   "fileName": "",
   "doi": "10.1109/comst.2019.2904897",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N050",
   "title": "On Multi-Access Edge Computing: A Survey of the Emerging 5G Network Edge Cloud Architecture and Orchestration",
   "year": 2017,
   "citations": 1795,
   "fileName": "",
   "doi": "10.1109/comst.2017.2705720",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N051",
   "title": "B4",
   "year": 2013,
   "citations": 1793,
   "fileName": "",
   "doi": "10.1145/2486001.2486019",
   "venue": ""
  },
  {
   "id": "N052",
   "title": "Tool release",
   "year": 2011,
   "citations": 1773,
   "fileName": "",
   "doi": "10.1145/1925861.1925870",
   "venue": "ACM SIGCOMM Computer Communication Review"
  },
  {
   "id": "N053",
   "title": "A survey of network anomaly detection techniques",
   "year": 2015,
   "citations": 1765,
   "fileName": "",
   "doi": "10.1016/j.jnca.2015.11.016",
   "venue": "Journal of Network and Computer Applications"
  },
  {
   "id": "N054",
   "title": "Dynamic Computation Offloading for Mobile-Edge Computing With Energy Harvesting Devices",
   "year": 2016,
   "citations": 1753,
   "fileName": "10.1109_jsac.2016.2611964.pdf",
   "doi": "10.1109/jsac.2016.2611964",
   "venue": "IEEE Journal on Selected Areas in Communications"
  },
  {
   "id": "N055",
   "title": "The Internet Topology Zoo",
   "year": 2011,
   "citations": 1753,
   "fileName": "",
   "doi": "10.1109/jsac.2011.111002",
   "venue": "IEEE Journal on Selected Areas in Communications"
  },
  {
   "id": "N056",
   "title": "The Future of Industrial Communication: Automation Networks in the Era of the Internet of Things and Industry 4.0",
   "year": 2017,
   "citations": 1732,
   "fileName": "",
   "doi": "10.1109/mie.2017.2649104",
   "venue": "IEEE Industrial Electronics Magazine"
  },
  {
   "id": "N057",
   "title": "Personal connections in the digital age",
   "year": 2016,
   "citations": 1721,
   "fileName": "",
   "doi": "10.5860/choice.194329",
   "venue": "Choice Reviews Online"
  },
  {
   "id": "N058",
   "title": "Internet of Things: Architectures, Protocols, and Applications",
   "year": 2017,
   "citations": 1712,
   "fileName": "",
   "doi": "10.1155/2017/9324035",
   "venue": "Journal of Electrical and Computer Engineering"
  },
  {
   "id": "N059",
   "title": "iFogSim: A toolkit for modeling and simulation of resource management techniques in the Internet of Things, Edge and Fog computing environments",
   "year": 2017,
   "citations": 1657,
   "fileName": "",
   "doi": "10.1002/spe.2509",
   "venue": "Software Practice and Experience"
  },
  {
   "id": "N060",
   "title": "Infrastructure studies meet platform studies in the age of Google and Facebook",
   "year": 2016,
   "citations": 1649,
   "fileName": "10.1177_1461444816661553.pdf",
   "doi": "10.1177/1461444816661553",
   "venue": "New Media & Society"
  },
  {
   "id": "N061",
   "title": "Intrusion detection system: A comprehensive review",
   "year": 2012,
   "citations": 1643,
   "fileName": "",
   "doi": "10.1016/j.jnca.2012.09.004",
   "venue": "Journal of Network and Computer Applications"
  },
  {
   "id": "N062",
   "title": "A survey of information-centric networking",
   "year": 2012,
   "citations": 1640,
   "fileName": "",
   "doi": "10.1109/mcom.2012.6231276",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N063",
   "title": "Search and replication in unstructured peer-to-peer networks",
   "year": 2014,
   "citations": 1618,
   "fileName": "",
   "doi": "10.1145/2591635.2667182",
   "venue": ""
  },
  {
   "id": "N064",
   "title": "Learning IoT in Edge: Deep Learning for the Internet of Things with Edge Computing",
   "year": 2018,
   "citations": 1598,
   "fileName": "10.1109_mnet.2018.1700202.pdf",
   "doi": "10.1109/mnet.2018.1700202",
   "venue": "IEEE Network"
  },
  {
   "id": "N065",
   "title": "The Internet of Things—A survey of topics and trends",
   "year": 2014,
   "citations": 1585,
   "fileName": "",
   "doi": "10.1007/s10796-014-9489-2",
   "venue": "Information Systems Frontiers"
  },
  {
   "id": "N066",
   "title": "Energy-Efficient Resource Allocation for Mobile-Edge Computation Offloading",
   "year": 2016,
   "citations": 1566,
   "fileName": "",
   "doi": "10.1109/twc.2016.2633522",
   "venue": "IEEE Transactions on Wireless Communications"
  },
  {
   "id": "N067",
   "title": "Deep Learning With Edge Computing: A Review",
   "year": 2019,
   "citations": 1547,
   "fileName": "",
   "doi": "10.1109/jproc.2019.2921977",
   "venue": "Proceedings of the IEEE"
  },
  {
   "id": "N068",
   "title": "BUBBLE Rap: Social-Based Forwarding in Delay-Tolerant Networks",
   "year": 2011,
   "citations": 1529,
   "fileName": "",
   "doi": "10.1109/tmc.2010.246",
   "venue": "IEEE Transactions on Mobile Computing"
  },
  {
   "id": "N069",
   "title": "A Survey on the Edge Computing for the Internet of Things",
   "year": 2017,
   "citations": 1525,
   "fileName": "",
   "doi": "10.1109/access.2017.2778504",
   "venue": "IEEE Access"
  },
  {
   "id": "N070",
   "title": "Flying Ad-Hoc Networks (FANETs): A survey",
   "year": 2013,
   "citations": 1525,
   "fileName": "",
   "doi": "10.1016/j.adhoc.2012.12.004",
   "venue": "Ad Hoc Networks"
  },
  {
   "id": "N071",
   "title": "Convergence of Edge Computing and Deep Learning: A Comprehensive Survey",
   "year": 2020,
   "citations": 1508,
   "fileName": "10.1109_comst.2020.2970550.pdf",
   "doi": "10.1109/comst.2020.2970550",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N072",
   "title": "Internet of Things: Applications and Challenges in Technology and Standardization",
   "year": 2011,
   "citations": 1507,
   "fileName": "",
   "doi": "10.1007/s11277-011-0288-5",
   "venue": "Wireless Personal Communications"
  },
  {
   "id": "N073",
   "title": "N-BaIoT—Network-Based Detection of IoT Botnet Attacks Using Deep Autoencoders",
   "year": 2018,
   "citations": 1481,
   "fileName": "10.1109_mprv.2018.03367731.pdf",
   "doi": "10.1109/mprv.2018.03367731",
   "venue": "IEEE Pervasive Computing"
  },
  {
   "id": "N074",
   "title": "The Internet of Things vision: Key features, applications and open issues",
   "year": 2014,
   "citations": 1480,
   "fileName": "",
   "doi": "10.1016/j.comcom.2014.09.008",
   "venue": "Computer Communications"
  },
  {
   "id": "N075",
   "title": "On the features and challenges of security and privacy in distributed internet of things",
   "year": 2013,
   "citations": 1478,
   "fileName": "",
   "doi": "10.1016/j.comnet.2012.12.018",
   "venue": "Computer Networks"
  },
  {
   "id": "N076",
   "title": "A Survey on IoT Security: Application Areas, Security Threats, and Solution Architectures",
   "year": 2019,
   "citations": 1414,
   "fileName": "",
   "doi": "10.1109/access.2019.2924045",
   "venue": "IEEE Access"
  },
  {
   "id": "N077",
   "title": "The NewReno Modification to TCP's Fast Recovery Algorithm",
   "year": 2012,
   "citations": 1414,
   "fileName": "",
   "doi": "10.17487/rfc6582",
   "venue": ""
  },
  {
   "id": "N078",
   "title": "2014 IEEE Global Communications Conference",
   "year": 2014,
   "citations": 1405,
   "fileName": "",
   "doi": "10.1109/globecom18177.2014",
   "venue": ""
  },
  {
   "id": "N079",
   "title": "A Survey of Defense Mechanisms Against Distributed Denial of Service (DDoS) Flooding Attacks",
   "year": 2013,
   "citations": 1401,
   "fileName": "",
   "doi": "10.1109/surv.2013.031413.00127",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N080",
   "title": "All one needs to know about fog computing and related edge computing paradigms: A complete survey",
   "year": 2019,
   "citations": 1382,
   "fileName": "",
   "doi": "10.1016/j.sysarc.2019.02.009",
   "venue": "Journal of Systems Architecture"
  },
  {
   "id": "N081",
   "title": "The OAuth 2.0 Authorization Framework",
   "year": 2012,
   "citations": 1382,
   "fileName": "",
   "doi": "10.17487/rfc6749",
   "venue": ""
  },
  {
   "id": "N082",
   "title": "A Survey of Machine and Deep Learning Methods for Internet of Things (IoT) Security",
   "year": 2020,
   "citations": 1378,
   "fileName": "10.1109_comst.2020.2988293.pdf",
   "doi": "10.1109/comst.2020.2988293",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N083",
   "title": "Future Internet: The Internet of Things Architecture, Possible Applications and Key Challenges",
   "year": 2012,
   "citations": 1375,
   "fileName": "",
   "doi": "10.1109/fit.2012.53",
   "venue": "International Conference on Frontiers of Information Technology (FIT)"
  },
  {
   "id": "N084",
   "title": "Toward developing a systematic approach to generate benchmark datasets for intrusion detection",
   "year": 2012,
   "citations": 1365,
   "fileName": "",
   "doi": "10.1016/j.cose.2011.12.012",
   "venue": "Computers & Security"
  },
  {
   "id": "N085",
   "title": "A Survey of Information-Centric Networking Research",
   "year": 2013,
   "citations": 1364,
   "fileName": "",
   "doi": "10.1109/surv.2013.070813.00063",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N086",
   "title": "Network Anomaly Detection: Methods, Systems and Tools",
   "year": 2013,
   "citations": 1361,
   "fileName": "",
   "doi": "10.1109/surv.2013.052213.00046",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N087",
   "title": "A Survey of Fog Computing",
   "year": 2015,
   "citations": 1353,
   "fileName": "",
   "doi": "10.1145/2757384.2757397",
   "venue": ""
  },
  {
   "id": "N088",
   "title": "EXTRA: An Exact First-Order Algorithm for Decentralized Consensus Optimization",
   "year": 2015,
   "citations": 1319,
   "fileName": "",
   "doi": "10.1137/14096668x",
   "venue": "SIAM Journal on Optimization"
  },
  {
   "id": "N089",
   "title": "Mobile edge computing, Fog et al.: A survey and analysis of security threats and challenges",
   "year": 2016,
   "citations": 1318,
   "fileName": "10.1016_j.future.2016.11.009.pdf",
   "doi": "10.1016/j.future.2016.11.009",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N090",
   "title": "FemtoCaching: Wireless Content Delivery Through Distributed Caching Helpers",
   "year": 2013,
   "citations": 1318,
   "fileName": "",
   "doi": "10.1109/tit.2013.2281606",
   "venue": "IEEE Transactions on Information Theory"
  },
  {
   "id": "N091",
   "title": "Internet of Things security: A survey",
   "year": 2017,
   "citations": 1314,
   "fileName": "",
   "doi": "10.1016/j.jnca.2017.04.002",
   "venue": "Journal of Network and Computer Applications"
  },
  {
   "id": "N092",
   "title": "Social Media: Defining, Developing, and Divining",
   "year": 2015,
   "citations": 1313,
   "fileName": "",
   "doi": "10.1080/15456870.2015.972282",
   "venue": "Atlantic Journal of Communication"
  },
  {
   "id": "N093",
   "title": "Information Theory",
   "year": 2011,
   "citations": 1309,
   "fileName": "",
   "doi": "10.1017/cbo9780511921889",
   "venue": "Cambridge University Press eBooks"
  },
  {
   "id": "N094",
   "title": "Energy-Efficient Routing Protocols in Wireless Sensor Networks: A Survey",
   "year": 2012,
   "citations": 1291,
   "fileName": "",
   "doi": "10.1109/surv.2012.062612.00084",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N095",
   "title": "Network intrusion detection system: A systematic study of machine learning and deep learning approaches",
   "year": 2020,
   "citations": 1289,
   "fileName": "",
   "doi": "10.1002/ett.4150",
   "venue": "Transactions on Emerging Telecommunications Technologies"
  },
  {
   "id": "N096",
   "title": "A Survey on Security and Privacy Issues in Internet-of-Things",
   "year": 2017,
   "citations": 1287,
   "fileName": "",
   "doi": "10.1109/jiot.2017.2694844",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N097",
   "title": "A Deep Learning Approach for Network Intrusion Detection System",
   "year": 2016,
   "citations": 1287,
   "fileName": "",
   "doi": "10.4108/eai.3-12-2015.2262516",
   "venue": ""
  },
  {
   "id": "N098",
   "title": "Improving network management with software defined networking",
   "year": 2013,
   "citations": 1271,
   "fileName": "",
   "doi": "10.1109/mcom.2013.6461195",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N099",
   "title": "An Overview on Edge Computing Research",
   "year": 2020,
   "citations": 1259,
   "fileName": "",
   "doi": "10.1109/access.2020.2991734",
   "venue": "IEEE Access"
  },
  {
   "id": "N100",
   "title": "Security of the Internet of Things: perspectives and challenges",
   "year": 2014,
   "citations": 1259,
   "fileName": "",
   "doi": "10.1007/s11276-014-0761-7",
   "venue": "Wireless Networks"
  },
  {
   "id": "N101",
   "title": "The Social Internet of Things (SIoT) – When social networks meet the Internet of Things: Concept, architecture and network characterization",
   "year": 2012,
   "citations": 1257,
   "fileName": "",
   "doi": "10.1016/j.comnet.2012.07.010",
   "venue": "Computer Networks"
  },
  {
   "id": "N102",
   "title": "Virtual Network Embedding: A Survey",
   "year": 2013,
   "citations": 1254,
   "fileName": "",
   "doi": "10.1109/surv.2013.013013.00155",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N103",
   "title": "The Promise of Edge Computing",
   "year": 2016,
   "citations": 1251,
   "fileName": "",
   "doi": "10.1109/mc.2016.145",
   "venue": "Computer"
  },
  {
   "id": "N104",
   "title": "Machine Learning and Deep Learning Methods for Cybersecurity",
   "year": 2018,
   "citations": 1233,
   "fileName": "",
   "doi": "10.1109/access.2018.2836950",
   "venue": "IEEE Access"
  },
  {
   "id": "N105",
   "title": "Secure Routing in Mobile Ad hoc Networks",
   "year": 2022,
   "citations": 1230,
   "fileName": "",
   "doi": "10.22271/ed.book.2027",
   "venue": ""
  },
  {
   "id": "N106",
   "title": "Distributed Optimization Over Time-Varying Directed Graphs",
   "year": 2014,
   "citations": 1230,
   "fileName": "",
   "doi": "10.1109/tac.2014.2364096",
   "venue": "IEEE Transactions on Automatic Control"
  },
  {
   "id": "N107",
   "title": "A Vision of IoT: Applications, Challenges, and Opportunities With China Perspective",
   "year": 2014,
   "citations": 1214,
   "fileName": "",
   "doi": "10.1109/jiot.2014.2337336",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N108",
   "title": "Living on the edge: The role of proactive caching in 5G wireless networks",
   "year": 2014,
   "citations": 1214,
   "fileName": "",
   "doi": "10.1109/mcom.2014.6871674",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N109",
   "title": "Exploiting smart e-Health gateways at the edge of healthcare Internet-of-Things: A fog computing approach",
   "year": 2017,
   "citations": 1209,
   "fileName": "",
   "doi": "10.1016/j.future.2017.02.014",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N110",
   "title": "Fog Computing: A Platform for Internet of Things and Analytics",
   "year": 2014,
   "citations": 1204,
   "fileName": "",
   "doi": "10.1007/978-3-319-05029-4_7",
   "venue": "Studies in computational intelligence"
  },
  {
   "id": "N111",
   "title": "An Overview of Recent Advances in Event-Triggered Consensus of Multiagent Systems",
   "year": 2017,
   "citations": 1199,
   "fileName": "",
   "doi": "10.1109/tcyb.2017.2771560",
   "venue": "IEEE Transactions on Cybernetics"
  },
  {
   "id": "N112",
   "title": "Network Slicing in 5G: Survey and Challenges",
   "year": 2017,
   "citations": 1185,
   "fileName": "10.1109_mcom.2017.1600951.pdf",
   "doi": "10.1109/mcom.2017.1600951",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N113",
   "title": "Age of Information: An Introduction and Survey",
   "year": 2021,
   "citations": 1182,
   "fileName": "10.1109_jsac.2021.3065072.pdf",
   "doi": "10.1109/jsac.2021.3065072",
   "venue": "IEEE Journal on Selected Areas in Communications"
  },
  {
   "id": "N114",
   "title": "Network function virtualization: Challenges and opportunities for innovations",
   "year": 2015,
   "citations": 1181,
   "fileName": "",
   "doi": "10.1109/mcom.2015.7045396",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N115",
   "title": "A survey on Internet of Things architectures",
   "year": 2016,
   "citations": 1179,
   "fileName": "",
   "doi": "10.1016/j.jksuci.2016.10.003",
   "venue": "Journal of King Saud University - Computer and Information Sciences"
  },
  {
   "id": "N116",
   "title": "Synchronization in complex networks of phase oscillators: A survey",
   "year": 2014,
   "citations": 1177,
   "fileName": "",
   "doi": "10.1016/j.automatica.2014.04.012",
   "venue": "Automatica"
  },
  {
   "id": "N117",
   "title": "Status update: celebrity, publicity, and branding in the social media age",
   "year": 2014,
   "citations": 1172,
   "fileName": "",
   "doi": "10.5860/choice.51-5062",
   "venue": "Choice Reviews Online"
  },
  {
   "id": "N118",
   "title": "An IoT-Aware Architecture for Smart Healthcare Systems",
   "year": 2015,
   "citations": 1171,
   "fileName": "",
   "doi": "10.1109/jiot.2015.2417684",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N119",
   "title": "Edge Intelligence: The Confluence of Edge Computing and Artificial Intelligence",
   "year": 2020,
   "citations": 1161,
   "fileName": "10.1109_jiot.2020.2984887.pdf",
   "doi": "10.1109/jiot.2020.2984887",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N120",
   "title": "Nonsingular fixed-time consensus tracking for second-order multi-agent networks",
   "year": 2015,
   "citations": 1160,
   "fileName": "",
   "doi": "10.1016/j.automatica.2015.01.021",
   "venue": "Automatica"
  },
  {
   "id": "N121",
   "title": "A survey on trust management for Internet of Things",
   "year": 2014,
   "citations": 1157,
   "fileName": "",
   "doi": "10.1016/j.jnca.2014.01.014",
   "venue": "Journal of Network and Computer Applications"
  },
  {
   "id": "N122",
   "title": "Machine Learning Paradigms for Next-Generation Wireless Networks",
   "year": 2016,
   "citations": 1152,
   "fileName": "",
   "doi": "10.1109/mwc.2016.1500356wc",
   "venue": "IEEE Wireless Communications"
  },
  {
   "id": "N123",
   "title": "Designing Fully Distributed Consensus Protocols for Linear Multi-Agent Systems With Directed Graphs",
   "year": 2014,
   "citations": 1150,
   "fileName": "10.1109_tac.2014.2350391.pdf",
   "doi": "10.1109/tac.2014.2350391",
   "venue": "IEEE Transactions on Automatic Control"
  },
  {
   "id": "N124",
   "title": "Security for the Internet of Things: A Survey of Existing Protocols and Open Research Issues",
   "year": 2015,
   "citations": 1147,
   "fileName": "",
   "doi": "10.1109/comst.2015.2388550",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N125",
   "title": "Edge-IIoTset: A New Comprehensive Realistic Cyber Security Dataset of IoT and IIoT Applications for Centralized and Federated Learning",
   "year": 2022,
   "citations": 1146,
   "fileName": "",
   "doi": "10.1109/access.2022.3165809",
   "venue": "IEEE Access"
  },
  {
   "id": "N126",
   "title": "Developing Realistic Distributed Denial of Service (DDoS) Attack Dataset and Taxonomy",
   "year": 2019,
   "citations": 1141,
   "fileName": "",
   "doi": "10.1109/ccst.2019.8888419",
   "venue": "International Carnahan Conference on Security Technology"
  },
  {
   "id": "N127",
   "title": "Edge computing: A survey",
   "year": 2019,
   "citations": 1141,
   "fileName": "",
   "doi": "10.1016/j.future.2019.02.050",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N128",
   "title": "Cache in the air: exploiting content caching and delivery techniques for 5G systems",
   "year": 2014,
   "citations": 1133,
   "fileName": "",
   "doi": "10.1109/mcom.2014.6736753",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N129",
   "title": "Deep learning for cyber security intrusion detection: Approaches, datasets, and comparative study",
   "year": 2019,
   "citations": 1126,
   "fileName": "",
   "doi": "10.1016/j.jisa.2019.102419",
   "venue": "Journal of Information Security and Applications"
  },
  {
   "id": "N130",
   "title": "Spectrum Sensing for Cognitive Radio : State-of-the-Art and Recent Advances",
   "year": 2012,
   "citations": 1125,
   "fileName": "",
   "doi": "10.1109/msp.2012.2183771",
   "venue": "IEEE Signal Processing Magazine"
  },
  {
   "id": "N131",
   "title": "ONOS",
   "year": 2014,
   "citations": 1124,
   "fileName": "",
   "doi": "10.1145/2620728.2620744",
   "venue": ""
  },
  {
   "id": "N132",
   "title": "Machine Learning and Deep Learning Methods for Intrusion Detection Systems: A Survey",
   "year": 2019,
   "citations": 1120,
   "fileName": "",
   "doi": "10.3390/app9204396",
   "venue": "Applied Sciences"
  },
  {
   "id": "N133",
   "title": "The evaluation of Network Anomaly Detection Systems: Statistical analysis of the UNSW-NB15 data set and the comparison with the KDD99 data set",
   "year": 2016,
   "citations": 1113,
   "fileName": "",
   "doi": "10.1080/19393555.2015.1125974",
   "venue": "Information Security Journal A Global Perspective"
  },
  {
   "id": "N134",
   "title": "Apache flink : Stream and batch processing in a single engine",
   "year": 2015,
   "citations": 1112,
   "fileName": "",
   "doi": "",
   "venue": "KTH Publication Database DiVA (KTH Royal Institute of Technology)"
  },
  {
   "id": "N135",
   "title": "Network Slicing and Softwarization: A Survey on Principles, Enabling Technologies, and Solutions",
   "year": 2018,
   "citations": 1106,
   "fileName": "",
   "doi": "10.1109/comst.2018.2815638",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N136",
   "title": "A Survey on Software-Defined Networking",
   "year": 2014,
   "citations": 1105,
   "fileName": "",
   "doi": "10.1109/comst.2014.2330903",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N137",
   "title": "Secure integration of IoT and Cloud Computing",
   "year": 2016,
   "citations": 1102,
   "fileName": "",
   "doi": "10.1016/j.future.2016.11.031",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N138",
   "title": "A Networked self: identity, community, and culture on social network sites",
   "year": 2011,
   "citations": 1097,
   "fileName": "",
   "doi": "10.5860/choice.48-3694",
   "venue": "Choice Reviews Online"
  },
  {
   "id": "N139",
   "title": "Raptor Codes",
   "year": 2011,
   "citations": 1097,
   "fileName": "",
   "doi": "",
   "venue": ""
  },
  {
   "id": "N140",
   "title": "Task Offloading for Mobile Edge Computing in Software Defined Ultra-Dense Network",
   "year": 2018,
   "citations": 1089,
   "fileName": "",
   "doi": "10.1109/jsac.2018.2815360",
   "venue": "IEEE Journal on Selected Areas in Communications"
  },
  {
   "id": "N141",
   "title": "Cognitive radio networking and communications: an overview",
   "year": 2011,
   "citations": 1083,
   "fileName": "",
   "doi": "10.1109/tvt.2011.2158673",
   "venue": "IEEE Transactions on Vehicular Technology"
  },
  {
   "id": "N142",
   "title": "Joint Task Offloading and Resource Allocation for Multi-Server Mobile-Edge Computing Networks",
   "year": 2018,
   "citations": 1078,
   "fileName": "10.1109_tvt.2018.2881191.pdf",
   "doi": "10.1109/tvt.2018.2881191",
   "venue": "IEEE Transactions on Vehicular Technology"
  },
  {
   "id": "N143",
   "title": "Achieving Geometric Convergence for Distributed Optimization Over Time-Varying Graphs",
   "year": 2017,
   "citations": 1073,
   "fileName": "",
   "doi": "10.1137/16m1084316",
   "venue": "SIAM Journal on Optimization"
  },
  {
   "id": "N144",
   "title": "Achieving high utilization with software-driven WAN",
   "year": 2013,
   "citations": 1073,
   "fileName": "",
   "doi": "10.1145/2486001.2486012",
   "venue": ""
  },
  {
   "id": "N145",
   "title": "Uses and Grats 2.0: New Gratifications for New Media",
   "year": 2013,
   "citations": 1073,
   "fileName": "",
   "doi": "10.1080/08838151.2013.845827",
   "venue": "Journal of Broadcasting & Electronic Media"
  },
  {
   "id": "N146",
   "title": "Distributed attack detection scheme using deep learning approach for Internet of Things",
   "year": 2017,
   "citations": 1067,
   "fileName": "",
   "doi": "10.1016/j.future.2017.08.043",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N147",
   "title": "Finding your Way in the Fog",
   "year": 2014,
   "citations": 1065,
   "fileName": "",
   "doi": "10.1145/2677046.2677052",
   "venue": "ACM SIGCOMM Computer Communication Review"
  },
  {
   "id": "N148",
   "title": "Wireless sensor networks: a survey on recent developments and potential synergies",
   "year": 2013,
   "citations": 1065,
   "fileName": "",
   "doi": "10.1007/s11227-013-1021-9",
   "venue": "The Journal of Supercomputing"
  },
  {
   "id": "N149",
   "title": "Understanding O-RAN: Architecture, Interfaces, Algorithms, Security, and Research Challenges",
   "year": 2023,
   "citations": 1064,
   "fileName": "",
   "doi": "10.1109/comst.2023.3239220",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N150",
   "title": "In-Edge AI: Intelligentizing Mobile Edge Computing, Caching and Communication by Federated Learning",
   "year": 2019,
   "citations": 1063,
   "fileName": "10.1109_mnet.2019.1800286.pdf",
   "doi": "10.1109/mnet.2019.1800286",
   "venue": "IEEE Network"
  },
  {
   "id": "N151",
   "title": "The Kuramoto model in complex networks",
   "year": 2015,
   "citations": 1056,
   "fileName": "10.1016_j.physrep.2015.10.008.pdf",
   "doi": "10.1016/j.physrep.2015.10.008",
   "venue": "Physics Reports"
  },
  {
   "id": "N152",
   "title": "Time-Varying Formation Control for Unmanned Aerial Vehicles: Theories and Applications",
   "year": 2014,
   "citations": 1056,
   "fileName": "",
   "doi": "10.1109/tcst.2014.2314460",
   "venue": "IEEE Transactions on Control Systems Technology"
  },
  {
   "id": "N153",
   "title": "Fog Computing: Helping the Internet of Things Realize Its Potential",
   "year": 2016,
   "citations": 1055,
   "fileName": "",
   "doi": "10.1109/mc.2016.245",
   "venue": "Computer"
  },
  {
   "id": "N154",
   "title": "Compute-and-Forward: Harnessing Interference Through Structured Codes",
   "year": 2011,
   "citations": 1054,
   "fileName": "",
   "doi": "10.1109/tit.2011.2165816",
   "venue": "IEEE Transactions on Information Theory"
  },
  {
   "id": "N155",
   "title": "Deep Reinforcement Learning for Online Computation Offloading in Wireless Powered Mobile-Edge Computing Networks",
   "year": 2019,
   "citations": 1046,
   "fileName": "10.1109_tmc.2019.2928811.pdf",
   "doi": "10.1109/tmc.2019.2928811",
   "venue": "IEEE Transactions on Mobile Computing"
  },
  {
   "id": "N156",
   "title": "Understanding the mirai botnet",
   "year": 2017,
   "citations": 1045,
   "fileName": "",
   "doi": "",
   "venue": "USENIX Security Symposium"
  },
  {
   "id": "N157",
   "title": "On the Levy-Walk Nature of Human Mobility",
   "year": 2011,
   "citations": 1044,
   "fileName": "",
   "doi": "10.1109/tnet.2011.2120618",
   "venue": "IEEE/ACM Transactions on Networking"
  },
  {
   "id": "N158",
   "title": "Media Sosial Perspektif komunikasi,Budaya,Dan sosioteknologi",
   "year": 2017,
   "citations": 1040,
   "fileName": "",
   "doi": "",
   "venue": ""
  },
  {
   "id": "N159",
   "title": "A comprehensive survey on machine learning for networking: evolution, applications and research opportunities",
   "year": 2018,
   "citations": 1037,
   "fileName": "",
   "doi": "10.1186/s13174-018-0087-2",
   "venue": "Journal of Internet Services and Applications"
  },
  {
   "id": "N160",
   "title": "Mobile-Edge Computing: Partial Computation Offloading Using Dynamic Voltage Scaling",
   "year": 2016,
   "citations": 1034,
   "fileName": "",
   "doi": "10.1109/tcomm.2016.2599530",
   "venue": "IEEE Transactions on Communications"
  },
  {
   "id": "N161",
   "title": "A survey of intrusion detection in Internet of Things",
   "year": 2017,
   "citations": 1033,
   "fileName": "",
   "doi": "10.1016/j.jnca.2017.02.009",
   "venue": "Journal of Network and Computer Applications"
  },
  {
   "id": "N162",
   "title": "HotStuff",
   "year": 2019,
   "citations": 1031,
   "fileName": "",
   "doi": "10.1145/3293611.3331591",
   "venue": "ACM Symposium on Principles of Distributed Computing (PODC)"
  },
  {
   "id": "N163",
   "title": "The Fog Computing Paradigm: Scenarios and Security Issues",
   "year": 2014,
   "citations": 1031,
   "fileName": "",
   "doi": "10.15439/2014f503",
   "venue": "Annals of Computer Science and Information Systems"
  },
  {
   "id": "N164",
   "title": "Middleware for Internet of Things: A Survey",
   "year": 2015,
   "citations": 1028,
   "fileName": "10.1109_jiot.2015.2498900.pdf",
   "doi": "10.1109/jiot.2015.2498900",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N165",
   "title": "CICIoT2023: A Real-Time Dataset and Benchmark for Large-Scale Attacks in IoT Environment",
   "year": 2023,
   "citations": 1023,
   "fileName": "",
   "doi": "10.3390/s23135941",
   "venue": "Sensors"
  },
  {
   "id": "N166",
   "title": "TCP Extensions for Multipath Operation with Multiple Addresses",
   "year": 2020,
   "citations": 1017,
   "fileName": "",
   "doi": "10.17487/rfc8684",
   "venue": ""
  },
  {
   "id": "N167",
   "title": "TCP Extensions for High Performance",
   "year": 2014,
   "citations": 1013,
   "fileName": "",
   "doi": "10.17487/rfc7323",
   "venue": ""
  },
  {
   "id": "N168",
   "title": "A Comprehensive Survey on Fog Computing: State-of-the-Art and Research Challenges",
   "year": 2017,
   "citations": 1012,
   "fileName": "10.1109_comst.2017.2771153.pdf",
   "doi": "10.1109/comst.2017.2771153",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N169",
   "title": "The Affordances of Social Media Platforms",
   "year": 2017,
   "citations": 1007,
   "fileName": "10.4135_9781473984066.n14.pdf",
   "doi": "10.4135/9781473984066.n14",
   "venue": "SAGE Publications Ltd eBooks"
  },
  {
   "id": "N170",
   "title": "B4",
   "year": 2013,
   "citations": 1007,
   "fileName": "",
   "doi": "10.1145/2534169.2486019",
   "venue": "ACM SIGCOMM Computer Communication Review"
  },
  {
   "id": "N171",
   "title": "Internet of Things Strategic Research Roadmap",
   "year": 2022,
   "citations": 1005,
   "fileName": "",
   "doi": "10.1201/9781003338604-2",
   "venue": "River Publishers eBooks"
  },
  {
   "id": "N172",
   "title": "Are we ready for SDN? Implementation challenges for software-defined networks",
   "year": 2013,
   "citations": 1002,
   "fileName": "",
   "doi": "10.1109/mcom.2013.6553676",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N173",
   "title": "Current research on Internet of Things (IoT) security: A survey",
   "year": 2018,
   "citations": 996,
   "fileName": "",
   "doi": "10.1016/j.comnet.2018.11.025",
   "venue": "Computer Networks"
  },
  {
   "id": "N174",
   "title": "Towards fog-driven IoT eHealth: Promises and challenges of IoT in medicine and healthcare",
   "year": 2017,
   "citations": 994,
   "fileName": "10.1016_j.future.2017.04.036.pdf",
   "doi": "10.1016/j.future.2017.04.036",
   "venue": "Future Generation Computer Systems"
  },
  {
   "id": "N175",
   "title": "Discretized streams",
   "year": 2013,
   "citations": 993,
   "fileName": "",
   "doi": "10.1145/2517349.2522737",
   "venue": ""
  },
  {
   "id": "N176",
   "title": "Inferring the structure and dynamics of interactions in schooling fish",
   "year": 2011,
   "citations": 980,
   "fileName": "10.1073_pnas.1107583108.pdf",
   "doi": "10.1073/pnas.1107583108",
   "venue": "Proceedings of the National Academy of Sciences"
  },
  {
   "id": "N177",
   "title": "Overview and Evaluation of Bluetooth Low Energy: An Emerging Low-Power Wireless Technology",
   "year": 2012,
   "citations": 972,
   "fileName": "",
   "doi": "10.3390/s120911734",
   "venue": "Sensors"
  },
  {
   "id": "N178",
   "title": "A Survey on Mobile Edge Networks: Convergence of Computing, Caching and Communications",
   "year": 2017,
   "citations": 968,
   "fileName": "10.1109_access.2017.2685434.pdf",
   "doi": "10.1109/access.2017.2685434",
   "venue": "IEEE Access"
  },
  {
   "id": "N179",
   "title": "Joint Offloading and Computing Optimization in Wireless Powered Mobile-Edge Computing Systems",
   "year": 2017,
   "citations": 968,
   "fileName": "",
   "doi": "10.1109/twc.2017.2785305",
   "venue": "IEEE Transactions on Wireless Communications"
  },
  {
   "id": "N180",
   "title": "DevoFlow",
   "year": 2011,
   "citations": 965,
   "fileName": "",
   "doi": "10.1145/2018436.2018466",
   "venue": "ACM SIGCOMM Conference (SIGCOMM)"
  },
  {
   "id": "N181",
   "title": "Sociality Through Social Network Sites",
   "year": 2013,
   "citations": 954,
   "fileName": "",
   "doi": "10.1093/oxfordhb/9780199589074.013.0008",
   "venue": "Oxford University Press eBooks"
  },
  {
   "id": "N182",
   "title": "Network Intrusion Detection for IoT Security Based on Learning Techniques",
   "year": 2019,
   "citations": 950,
   "fileName": "",
   "doi": "10.1109/comst.2019.2896380",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N183",
   "title": "Vehicular Fog Computing: A Viewpoint of Vehicles as the Infrastructures",
   "year": 2016,
   "citations": 948,
   "fileName": "",
   "doi": "10.1109/tvt.2016.2532863",
   "venue": "IEEE Transactions on Vehicular Technology"
  },
  {
   "id": "N184",
   "title": "A survey of network-based intrusion detection data sets",
   "year": 2019,
   "citations": 947,
   "fileName": "10.1016_j.cose.2019.06.005.pdf",
   "doi": "10.1016/j.cose.2019.06.005",
   "venue": "Computers & Security"
  },
  {
   "id": "N185",
   "title": "Edge-centric Computing",
   "year": 2015,
   "citations": 942,
   "fileName": "",
   "doi": "10.1145/2831347.2831354",
   "venue": "ACM SIGCOMM Computer Communication Review"
  },
  {
   "id": "N186",
   "title": "Dual Averaging for Distributed Optimization: Convergence Analysis and Network Scaling",
   "year": 2011,
   "citations": 937,
   "fileName": "10.1109_tac.2011.2161027.pdf",
   "doi": "10.1109/tac.2011.2161027",
   "venue": "IEEE Transactions on Automatic Control"
  },
  {
   "id": "N187",
   "title": "Edge AI: On-Demand Accelerating Deep Neural Network Inference via Edge Computing",
   "year": 2019,
   "citations": 936,
   "fileName": "",
   "doi": "10.1109/twc.2019.2946140",
   "venue": "IEEE Transactions on Wireless Communications"
  },
  {
   "id": "N188",
   "title": "IEEE Standard for Information technology—Telecommunications and information exchange between systems Local and metropolitan area networks—Specific requirements - Part 11: Wireless LAN Medium Access Control (MAC) and Physical Layer (PHY) Specifications",
   "year": 2016,
   "citations": 935,
   "fileName": "",
   "doi": "10.1109/ieeestd.2016.7786995",
   "venue": ""
  },
  {
   "id": "N189",
   "title": "Fog Computing: A Taxonomy, Survey and Future Directions",
   "year": 2017,
   "citations": 930,
   "fileName": "10.1007_978-981-10-5861-5_5.pdf",
   "doi": "10.1007/978-981-10-5861-5_5",
   "venue": "Internet of things"
  },
  {
   "id": "N190",
   "title": "‘You have one identity’: performing the self on Facebook and LinkedIn",
   "year": 2013,
   "citations": 930,
   "fileName": "",
   "doi": "10.1177/0163443712468605",
   "venue": "Media Culture & Society"
  },
  {
   "id": "N191",
   "title": "Joint Optimization of Radio and Computational Resources for Multicell Mobile-Edge Computing",
   "year": 2015,
   "citations": 928,
   "fileName": "10.1109_tsipn.2015.2448520.pdf",
   "doi": "10.1109/tsipn.2015.2448520",
   "venue": "IEEE Transactions on Signal and Information Processing over Networks"
  },
  {
   "id": "N192",
   "title": "Minimizing age of information in vehicular networks",
   "year": 2011,
   "citations": 926,
   "fileName": "",
   "doi": "10.1109/sahcn.2011.5984917",
   "venue": "Annual IEEE Communications Society Conference on Sensor, Mesh and Ad Hoc Communications and Networks (SECON)"
  },
  {
   "id": "N193",
   "title": "Computation Rate Maximization for Wireless Powered Mobile-Edge Computing With Binary Computation Offloading",
   "year": 2018,
   "citations": 924,
   "fileName": "",
   "doi": "10.1109/twc.2018.2821664",
   "venue": "IEEE Transactions on Wireless Communications"
  },
  {
   "id": "N194",
   "title": "Security and privacy challenges in industrial internet of things",
   "year": 2015,
   "citations": 923,
   "fileName": "",
   "doi": "10.1145/2744769.2747942",
   "venue": "Proceedings - ACM IEEE Design Automation Conference"
  },
  {
   "id": "N195",
   "title": "Resource Allocation in NFV: A Comprehensive Survey",
   "year": 2016,
   "citations": 920,
   "fileName": "",
   "doi": "10.1109/tnsm.2016.2598420",
   "venue": "IEEE Transactions on Network and Service Management"
  },
  {
   "id": "N196",
   "title": "BBR: Congestion-Based Congestion Control",
   "year": 2016,
   "citations": 918,
   "fileName": "",
   "doi": "10.1145/3012426.3022184",
   "venue": "Queue"
  },
  {
   "id": "N197",
   "title": "Energy efficiency in wireless sensor networks: A top-down survey",
   "year": 2014,
   "citations": 913,
   "fileName": "",
   "doi": "10.1016/j.comnet.2014.03.027",
   "venue": "Computer Networks"
  },
  {
   "id": "N198",
   "title": "SVELTE: Real-time intrusion detection in the Internet of Things",
   "year": 2013,
   "citations": 913,
   "fileName": "",
   "doi": "10.1016/j.adhoc.2013.04.014",
   "venue": "Ad Hoc Networks"
  },
  {
   "id": "N199",
   "title": "Workload analysis of a large-scale key-value store",
   "year": 2012,
   "citations": 906,
   "fileName": "",
   "doi": "10.1145/2254756.2254766",
   "venue": ""
  },
  {
   "id": "N200",
   "title": "The road to SDN",
   "year": 2014,
   "citations": 905,
   "fileName": "",
   "doi": "10.1145/2602204.2602219",
   "venue": "ACM SIGCOMM Computer Communication Review"
  },
  {
   "id": "N201",
   "title": "Offloading in Mobile Edge Computing: Task Allocation and Computational Frequency Scaling",
   "year": 2017,
   "citations": 904,
   "fileName": "",
   "doi": "10.1109/tcomm.2017.2699660",
   "venue": "IEEE Transactions on Communications"
  },
  {
   "id": "N202",
   "title": "Drain: An Online Log Parsing Approach with Fixed Depth Tree",
   "year": 2017,
   "citations": 902,
   "fileName": "",
   "doi": "10.1109/icws.2017.13",
   "venue": "IEEE International Conference on Web Services (ICWS)"
  },
  {
   "id": "N203",
   "title": "Synchronization in complex oscillator networks and smart grids",
   "year": 2013,
   "citations": 900,
   "fileName": "10.1073_pnas.1212134110.pdf",
   "doi": "10.1073/pnas.1212134110",
   "venue": "Proceedings of the National Academy of Sciences"
  },
  {
   "id": "N204",
   "title": "A Survey on Low Latency Towards 5G: RAN, Core Network and Caching Solutions",
   "year": 2018,
   "citations": 898,
   "fileName": "",
   "doi": "10.1109/comst.2018.2841349",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N205",
   "title": "A survey of intrusion detection techniques in Cloud",
   "year": 2012,
   "citations": 896,
   "fileName": "",
   "doi": "10.1016/j.jnca.2012.05.003",
   "venue": "Journal of Network and Computer Applications"
  },
  {
   "id": "N206",
   "title": "TON_IoT Telemetry Dataset: A New Generation Dataset of IoT and IIoT for Data-Driven Intrusion Detection Systems",
   "year": 2020,
   "citations": 895,
   "fileName": "",
   "doi": "10.1109/access.2020.3022862",
   "venue": "IEEE Access"
  },
  {
   "id": "N207",
   "title": "BBR",
   "year": 2017,
   "citations": 895,
   "fileName": "",
   "doi": "10.1145/3009824",
   "venue": "Communications of the ACM"
  },
  {
   "id": "N208",
   "title": "Energy-Optimal Mobile Cloud Computing under Stochastic Wireless Channel",
   "year": 2013,
   "citations": 891,
   "fileName": "",
   "doi": "10.1109/twc.2013.072513.121842",
   "venue": "IEEE Transactions on Wireless Communications"
  },
  {
   "id": "N209",
   "title": "Space/Aerial-Assisted Computing Offloading for IoT Applications: A Learning-Based Approach",
   "year": 2019,
   "citations": 890,
   "fileName": "",
   "doi": "10.1109/jsac.2019.2906789",
   "venue": "IEEE Journal on Selected Areas in Communications"
  },
  {
   "id": "N210",
   "title": "Collaborative Mobile Edge Computing in 5G Networks: New Paradigms, Scenarios, and Challenges",
   "year": 2017,
   "citations": 890,
   "fileName": "",
   "doi": "10.1109/mcom.2017.1600863",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N211",
   "title": "Survey on fog computing: architecture, key technologies, applications and open issues",
   "year": 2017,
   "citations": 889,
   "fileName": "",
   "doi": "10.1016/j.jnca.2017.09.002",
   "venue": "Journal of Network and Computer Applications"
  },
  {
   "id": "N212",
   "title": "Speeding Up Distributed Machine Learning Using Codes",
   "year": 2017,
   "citations": 885,
   "fileName": "10.1109_tit.2017.2736066.pdf",
   "doi": "10.1109/tit.2017.2736066",
   "venue": "IEEE Transactions on Information Theory"
  },
  {
   "id": "N213",
   "title": "Update or Wait: How to Keep Your Data Fresh",
   "year": 2017,
   "citations": 884,
   "fileName": "",
   "doi": "10.1109/tit.2017.2735804",
   "venue": "IEEE Transactions on Information Theory"
  },
  {
   "id": "N214",
   "title": "Future Edge Cloud and Edge Computing for Internet of Things Applications",
   "year": 2017,
   "citations": 882,
   "fileName": "",
   "doi": "10.1109/jiot.2017.2767608",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N215",
   "title": "A Survey of Multi-Access Edge Computing in 5G and Beyond: Fundamentals, Technology Integration, and State-of-the-Art",
   "year": 2020,
   "citations": 878,
   "fileName": "",
   "doi": "10.1109/access.2020.3001277",
   "venue": "IEEE Access"
  },
  {
   "id": "N216",
   "title": "On the Linear Convergence of the ADMM in Decentralized Consensus Optimization",
   "year": 2014,
   "citations": 873,
   "fileName": "10.1109_tsp.2014.2304432.pdf",
   "doi": "10.1109/tsp.2014.2304432",
   "venue": "IEEE Transactions on Signal Processing"
  },
  {
   "id": "N217",
   "title": "The controller placement problem",
   "year": 2012,
   "citations": 873,
   "fileName": "",
   "doi": "10.1145/2342441.2342444",
   "venue": ""
  },
  {
   "id": "N218",
   "title": "Recent Advances in Consensus of Multi-Agent Systems: A Brief Survey",
   "year": 2016,
   "citations": 871,
   "fileName": "",
   "doi": "10.1109/tie.2016.2636810",
   "venue": "IEEE Transactions on Industrial Electronics"
  },
  {
   "id": "N219",
   "title": "1Improving Amplify-and-Forward Relay Networks: Optimal Power Allocation versus Selection",
   "year": 2015,
   "citations": 866,
   "fileName": "",
   "doi": "",
   "venue": ""
  },
  {
   "id": "N220",
   "title": "Edge Computing in Industrial Internet of Things: Architecture, Advances and Challenges",
   "year": 2020,
   "citations": 865,
   "fileName": "",
   "doi": "10.1109/comst.2020.3009103",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N221",
   "title": "Energy-Efficient Offloading for Mobile Edge Computing in 5G Heterogeneous Networks",
   "year": 2016,
   "citations": 865,
   "fileName": "",
   "doi": "10.1109/access.2016.2597169",
   "venue": "IEEE Access"
  },
  {
   "id": "N222",
   "title": "Inside the Social Network's (Datacenter) Network",
   "year": 2015,
   "citations": 858,
   "fileName": "",
   "doi": "10.1145/2785956.2787472",
   "venue": ""
  },
  {
   "id": "N223",
   "title": "Internet of Things: A survey on the security of IoT frameworks",
   "year": 2017,
   "citations": 857,
   "fileName": "",
   "doi": "10.1016/j.jisa.2017.11.002",
   "venue": "Journal of Information Security and Applications"
  },
  {
   "id": "N224",
   "title": "Wireless Network Information Flow: A Deterministic Approach",
   "year": 2011,
   "citations": 855,
   "fileName": "10.1109_tit.2011.2110110.pdf",
   "doi": "10.1109/tit.2011.2110110",
   "venue": "IEEE Transactions on Information Theory"
  },
  {
   "id": "N225",
   "title": "Machine Learning in Wireless Sensor Networks: Algorithms, Strategies, and Applications",
   "year": 2014,
   "citations": 853,
   "fileName": "10.1109_comst.2014.2320099.pdf",
   "doi": "10.1109/comst.2014.2320099",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N226",
   "title": "Polymedia: Towards a new theory of digital media in interpersonal communication",
   "year": 2012,
   "citations": 853,
   "fileName": "",
   "doi": "10.1177/1367877912452486",
   "venue": "International Journal of Cultural Studies"
  },
  {
   "id": "N227",
   "title": "Network Slicing for 5G with SDN/NFV: Concepts, Architectures, and Challenges",
   "year": 2017,
   "citations": 852,
   "fileName": "10.1109_mcom.2017.1600935.pdf",
   "doi": "10.1109/mcom.2017.1600935",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N228",
   "title": "TCP Extensions for Multipath Operation with Multiple Addresses",
   "year": 2013,
   "citations": 852,
   "fileName": "",
   "doi": "10.17487/rfc6824",
   "venue": ""
  },
  {
   "id": "N229",
   "title": "Consensus of Multi-Agent Systems With General Linear and Lipschitz Nonlinear Dynamics Using Distributed Adaptive Protocols",
   "year": 2012,
   "citations": 850,
   "fileName": "10.1109_tac.2012.2235715.pdf",
   "doi": "10.1109/tac.2012.2235715",
   "venue": "IEEE Transactions on Automatic Control"
  },
  {
   "id": "N230",
   "title": "Attack and anomaly detection in IoT sensors in IoT sites using machine learning approaches",
   "year": 2019,
   "citations": 849,
   "fileName": "",
   "doi": "10.1016/j.iot.2019.100059",
   "venue": "Internet of Things"
  },
  {
   "id": "N231",
   "title": "Demystifying IoT Security: An Exhaustive Survey on IoT Vulnerabilities and a First Empirical Look on Internet-Scale IoT Exploitations",
   "year": 2019,
   "citations": 848,
   "fileName": "",
   "doi": "10.1109/comst.2019.2910750",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N232",
   "title": "The TESLA Broadcast Authentication Protocol",
   "year": 2018,
   "citations": 848,
   "fileName": "",
   "doi": "10.1184/r1/6073610",
   "venue": "Figshare"
  },
  {
   "id": "N233",
   "title": "The Future of Healthcare Internet of Things: A Survey of Emerging Technologies",
   "year": 2020,
   "citations": 847,
   "fileName": "",
   "doi": "10.1109/comst.2020.2973314",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N234",
   "title": "Bandwidth Efficient and Rate-Matched Low-Density Parity-Check Coded Modulation",
   "year": 2015,
   "citations": 844,
   "fileName": "",
   "doi": "10.1109/tcomm.2015.2494016",
   "venue": "IEEE Transactions on Communications"
  },
  {
   "id": "N235",
   "title": "A Survey of Intrusion Detection Systems in Wireless Sensor Networks",
   "year": 2013,
   "citations": 840,
   "fileName": "",
   "doi": "10.1109/surv.2013.050113.00191",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N236",
   "title": "Processing flows of information",
   "year": 2012,
   "citations": 838,
   "fileName": "",
   "doi": "10.1145/2187671.2187677",
   "venue": "ACM Computing Surveys"
  },
  {
   "id": "N237",
   "title": "State-of-the-Art Deep Learning: Evolving Machine Intelligence Toward Tomorrow’s Intelligent Network Traffic Control Systems",
   "year": 2017,
   "citations": 837,
   "fileName": "",
   "doi": "10.1109/comst.2017.2707140",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N238",
   "title": "Computer Networking: A Top-Down Approach",
   "year": 2012,
   "citations": 834,
   "fileName": "",
   "doi": "",
   "venue": ""
  },
  {
   "id": "N239",
   "title": "Internet of Things (IoT): A review of enabling technologies, challenges, and open research issues",
   "year": 2018,
   "citations": 832,
   "fileName": "",
   "doi": "10.1016/j.comnet.2018.07.017",
   "venue": "Computer Networks"
  },
  {
   "id": "N240",
   "title": "Computing TCP's Retransmission Timer",
   "year": 2011,
   "citations": 831,
   "fileName": "",
   "doi": "10.17487/rfc6298",
   "venue": ""
  },
  {
   "id": "N241",
   "title": "The Honey Badger of BFT Protocols",
   "year": 2016,
   "citations": 830,
   "fileName": "",
   "doi": "10.1145/2976749.2978399",
   "venue": "ACM SIGSAC Conference on Computer and Communications Security (CCS)"
  },
  {
   "id": "N242",
   "title": "QUIC: A UDP-Based Multiplexed and Secure Transport",
   "year": 2021,
   "citations": 828,
   "fileName": "",
   "doi": "10.17487/rfc9000",
   "venue": ""
  },
  {
   "id": "N243",
   "title": "Game theory meets network security and privacy",
   "year": 2013,
   "citations": 827,
   "fileName": "",
   "doi": "10.1145/2480741.2480742",
   "venue": "ACM Computing Surveys"
  },
  {
   "id": "N244",
   "title": "ViNEYard: Virtual Network Embedding Algorithms With Coordinated Node and Link Mapping",
   "year": 2011,
   "citations": 827,
   "fileName": "",
   "doi": "10.1109/tnet.2011.2159308",
   "venue": "IEEE/ACM Transactions on Networking"
  },
  {
   "id": "N245",
   "title": "The QUIC Transport Protocol",
   "year": 2017,
   "citations": 826,
   "fileName": "",
   "doi": "10.1145/3098822.3098842",
   "venue": ""
  },
  {
   "id": "N246",
   "title": "5G network slicing using SDN and NFV: A survey of taxonomy, architectures and future challenges",
   "year": 2019,
   "citations": 825,
   "fileName": "",
   "doi": "10.1016/j.comnet.2019.106984",
   "venue": "Computer Networks"
  },
  {
   "id": "N247",
   "title": "Deep learning approach for Network Intrusion Detection in Software Defined Networking",
   "year": 2016,
   "citations": 825,
   "fileName": "10.1109_wincom.2016.7777224.pdf",
   "doi": "10.1109/wincom.2016.7777224",
   "venue": "International Conference on Wireless Networks and Mobile Communications (WINCOM)"
  },
  {
   "id": "N248",
   "title": "Edge Artificial Intelligence for 6G: Vision, Enabling Technologies, and Applications",
   "year": 2021,
   "citations": 819,
   "fileName": "",
   "doi": "10.1109/jsac.2021.3126076",
   "venue": "IEEE Journal on Selected Areas in Communications"
  },
  {
   "id": "N249",
   "title": "Computation Offloading and Resource Allocation For Cloud Assisted Mobile Edge Computing in Vehicular Networks",
   "year": 2019,
   "citations": 819,
   "fileName": "",
   "doi": "10.1109/tvt.2019.2917890",
   "venue": "IEEE Transactions on Vehicular Technology"
  },
  {
   "id": "N250",
   "title": "Time-Varying Formation Tracking for Second-Order Multi-Agent Systems Subjected to Switching Topologies With Application to Quadrotor Formation Flying",
   "year": 2016,
   "citations": 819,
   "fileName": "",
   "doi": "10.1109/tie.2016.2593656",
   "venue": "IEEE Transactions on Industrial Electronics"
  },
  {
   "id": "N251",
   "title": "Fog Computing: Platform and Applications",
   "year": 2015,
   "citations": 819,
   "fileName": "",
   "doi": "10.1109/hotweb.2015.22",
   "venue": ""
  },
  {
   "id": "N252",
   "title": "IoT: Internet of Threats? A Survey of Practical Security Vulnerabilities in Real IoT Devices",
   "year": 2019,
   "citations": 812,
   "fileName": "",
   "doi": "10.1109/jiot.2019.2935189",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N253",
   "title": "Network Slicing Based 5G and Future Mobile Networks: Mobility, Resource Management, and Challenges",
   "year": 2017,
   "citations": 811,
   "fileName": "10.1109_mcom.2017.1600940.pdf",
   "doi": "10.1109/mcom.2017.1600940",
   "venue": "IEEE Communications Magazine"
  },
  {
   "id": "N254",
   "title": "A Comprehensive Study of Security of Internet-of-Things",
   "year": 2016,
   "citations": 811,
   "fileName": "",
   "doi": "10.1109/tetc.2016.2606384",
   "venue": "IEEE Transactions on Emerging Topics in Computing"
  },
  {
   "id": "N255",
   "title": "Distributed Deep Neural Networks Over the Cloud, the Edge and End Devices",
   "year": 2017,
   "citations": 810,
   "fileName": "",
   "doi": "10.1109/icdcs.2017.226",
   "venue": "IEEE International Conference on Distributed Computing Systems (ICDCS)"
  },
  {
   "id": "N256",
   "title": "Software-Defined Networking (SDN) and Distributed Denial of Service (DDoS) Attacks in Cloud Computing Environments: A Survey, Some Research Issues, and Challenges",
   "year": 2015,
   "citations": 810,
   "fileName": "",
   "doi": "10.1109/comst.2015.2487361",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N257",
   "title": "Survey on Multi-Access Edge Computing for Internet of Things Realization",
   "year": 2018,
   "citations": 807,
   "fileName": "10.1109_comst.2018.2849509.pdf",
   "doi": "10.1109/comst.2018.2849509",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N258",
   "title": "X.509 Internet Public Key Infrastructure Online Certificate Status Protocol - OCSP",
   "year": 2013,
   "citations": 806,
   "fileName": "",
   "doi": "10.17487/rfc6960",
   "venue": ""
  },
  {
   "id": "N259",
   "title": "Broadband Analog Aggregation for Low-Latency Federated Edge Learning",
   "year": 2019,
   "citations": 805,
   "fileName": "",
   "doi": "10.1109/twc.2019.2946245",
   "venue": "IEEE Transactions on Wireless Communications"
  },
  {
   "id": "N260",
   "title": "Distributed robust finite-time nonlinear consensus protocols for multi-agent systems",
   "year": 2014,
   "citations": 804,
   "fileName": "",
   "doi": "10.1080/00207721.2014.925608",
   "venue": "International Journal of Systems Science"
  },
  {
   "id": "N261",
   "title": "Neurosurgeon",
   "year": 2017,
   "citations": 803,
   "fileName": "",
   "doi": "10.1145/3093337.3037698",
   "venue": "ACM SIGARCH Computer Architecture News"
  },
  {
   "id": "N262",
   "title": "Consensus Tracking of Multi-Agent Systems With Lipschitz-Type Node Dynamics and Switching Topologies",
   "year": 2013,
   "citations": 802,
   "fileName": "",
   "doi": "10.1109/tcsi.2013.2268091",
   "venue": "IEEE Transactions on Circuits and Systems I Regular Papers"
  },
  {
   "id": "N263",
   "title": "Chimera states: coexistence of coherence and incoherence in networks of coupled oscillators",
   "year": 2015,
   "citations": 801,
   "fileName": "",
   "doi": "10.1088/0951-7715/28/3/r67",
   "venue": "Nonlinearity"
  },
  {
   "id": "N264",
   "title": "Erasure coding in windows azure storage",
   "year": 2012,
   "citations": 799,
   "fileName": "",
   "doi": "",
   "venue": ""
  },
  {
   "id": "N265",
   "title": "Delay-optimal computation task scheduling for mobile-edge computing systems",
   "year": 2016,
   "citations": 795,
   "fileName": "10.1109_isit.2016.7541539.pdf",
   "doi": "10.1109/isit.2016.7541539",
   "venue": "IEEE International Symposium on Information Theory (ISIT)"
  },
  {
   "id": "N266",
   "title": "A detailed and flexible cycle-accurate Network-on-Chip simulator",
   "year": 2013,
   "citations": 795,
   "fileName": "",
   "doi": "10.1109/ispass.2013.6557149",
   "venue": "IEEE International Symposium on Performance Analysis of Systems and Software (ISPASS)"
  },
  {
   "id": "N267",
   "title": "Securing the Internet of Things",
   "year": 2011,
   "citations": 792,
   "fileName": "",
   "doi": "10.1109/mc.2011.291",
   "venue": "Computer"
  },
  {
   "id": "N268",
   "title": "On Distributed Convex Optimization Under Inequality and Equality Constraints",
   "year": 2011,
   "citations": 791,
   "fileName": "",
   "doi": "10.1109/tac.2011.2167817",
   "venue": "IEEE Transactions on Automatic Control"
  },
  {
   "id": "N269",
   "title": "Security in the Internet of Things: A Review",
   "year": 2012,
   "citations": 788,
   "fileName": "",
   "doi": "10.1109/iccsee.2012.373",
   "venue": "International Conference on Computer Science and Electronics Engineering (ICCSEE)"
  },
  {
   "id": "N270",
   "title": "Edge Computing for Autonomous Driving: Opportunities and Challenges",
   "year": 2019,
   "citations": 787,
   "fileName": "",
   "doi": "10.1109/jproc.2019.2915983",
   "venue": "Proceedings of the IEEE"
  },
  {
   "id": "N271",
   "title": "A survey of deep learning-based network anomaly detection",
   "year": 2017,
   "citations": 787,
   "fileName": "",
   "doi": "10.1007/s10586-017-1117-8",
   "venue": "Cluster Computing"
  },
  {
   "id": "N272",
   "title": "Computer Networking A Top- Down Approach",
   "year": 2017,
   "citations": 782,
   "fileName": "",
   "doi": "",
   "venue": ""
  },
  {
   "id": "N273",
   "title": "Forwarding metamorphosis",
   "year": 2013,
   "citations": 780,
   "fileName": "",
   "doi": "10.1145/2486001.2486011",
   "venue": ""
  },
  {
   "id": "N274",
   "title": "Beyond Transmitting Bits: Context, Semantics, and Task-Oriented Communications",
   "year": 2022,
   "citations": 777,
   "fileName": "",
   "doi": "10.1109/jsac.2022.3223408",
   "venue": "IEEE Journal on Selected Areas in Communications"
  },
  {
   "id": "N275",
   "title": "Empowering Things With Intelligence: A Survey of the Progress, Challenges, and Opportunities in Artificial Intelligence of Things",
   "year": 2020,
   "citations": 772,
   "fileName": "",
   "doi": "10.1109/jiot.2020.3039359",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N276",
   "title": "Evaluating Critical Security Issues of the IoT World: Present and Future Challenges",
   "year": 2017,
   "citations": 772,
   "fileName": "",
   "doi": "10.1109/jiot.2017.2767291",
   "venue": "IEEE Internet of Things Journal"
  },
  {
   "id": "N277",
   "title": "Internet Celebrity: Understanding Fame Online",
   "year": 2018,
   "citations": 770,
   "fileName": "",
   "doi": "10.1108/9781787560765",
   "venue": "Emerald Group Publishing Limited eBooks"
  },
  {
   "id": "N278",
   "title": "IoT Privacy and Security: Challenges and Solutions",
   "year": 2020,
   "citations": 768,
   "fileName": "",
   "doi": "10.3390/app10124102",
   "venue": "Applied Sciences"
  },
  {
   "id": "N279",
   "title": "A survey of intrusion detection techniques for cyber-physical systems",
   "year": 2014,
   "citations": 767,
   "fileName": "",
   "doi": "10.1145/2542049",
   "venue": "ACM Computing Surveys"
  },
  {
   "id": "N280",
   "title": "Internet of things (IoT) security: Current status, challenges and prospective measures",
   "year": 2015,
   "citations": 765,
   "fileName": "",
   "doi": "10.1109/icitst.2015.7412116",
   "venue": "International Conference for Internet Technology and Secured Transactions"
  },
  {
   "id": "N281",
   "title": "An Overview of Recent Advances in Coordinated Control of Multiple Autonomous Surface Vehicles",
   "year": 2020,
   "citations": 761,
   "fileName": "",
   "doi": "10.1109/tii.2020.3004343",
   "venue": "IEEE Transactions on Industrial Informatics"
  },
  {
   "id": "N282",
   "title": "Spontaneous synchrony in power-grid networks",
   "year": 2013,
   "citations": 761,
   "fileName": "10.1038_nphys2535.pdf",
   "doi": "10.1038/nphys2535",
   "venue": "Nature Physics"
  },
  {
   "id": "N283",
   "title": "Cybersecurity data science: an overview from machine learning perspective",
   "year": 2020,
   "citations": 759,
   "fileName": "",
   "doi": "10.1186/s40537-020-00318-5",
   "venue": "Journal Of Big Data"
  },
  {
   "id": "N284",
   "title": "A Survey on Software-Defined Network and OpenFlow: From Concept to Implementation",
   "year": 2014,
   "citations": 757,
   "fileName": "",
   "doi": "10.1109/comst.2014.2326417",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N285",
   "title": "On the Age of Information in Status Update Systems With Packet Management",
   "year": 2016,
   "citations": 756,
   "fileName": "",
   "doi": "10.1109/tit.2016.2533395",
   "venue": "IEEE Transactions on Information Theory"
  },
  {
   "id": "N286",
   "title": "Prescribed-Time Consensus and Containment Control of Networked Multiagent Systems",
   "year": 2018,
   "citations": 749,
   "fileName": "",
   "doi": "10.1109/tcyb.2017.2788874",
   "venue": "IEEE Transactions on Cybernetics"
  },
  {
   "id": "N287",
   "title": "FemtoCaching: Wireless video content delivery through distributed caching helpers",
   "year": 2012,
   "citations": 748,
   "fileName": "",
   "doi": "10.1109/infcom.2012.6195469",
   "venue": "IEEE Conference on Computer Communications (INFOCOM)"
  },
  {
   "id": "N288",
   "title": "A Comprehensive Review of Cyber Security Vulnerabilities, Threats, Attacks, and Solutions",
   "year": 2023,
   "citations": 746,
   "fileName": "",
   "doi": "10.3390/electronics12061333",
   "venue": "Electronics"
  },
  {
   "id": "N289",
   "title": "A Detailed Investigation and Analysis of Using Machine Learning Techniques for Intrusion Detection",
   "year": 2018,
   "citations": 746,
   "fileName": "",
   "doi": "10.1109/comst.2018.2847722",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N290",
   "title": "Resilient Asymptotic Consensus in Robust Networks",
   "year": 2013,
   "citations": 746,
   "fileName": "",
   "doi": "10.1109/jsac.2013.130413",
   "venue": "IEEE Journal on Selected Areas in Communications"
  },
  {
   "id": "N291",
   "title": "Applications of Wireless Sensor Networks: An Up-to-Date Survey",
   "year": 2020,
   "citations": 735,
   "fileName": "",
   "doi": "10.3390/asi3010014",
   "venue": "Applied System Innovation"
  },
  {
   "id": "N292",
   "title": "Fog Computing for the Internet of Things: Security and Privacy Issues",
   "year": 2017,
   "citations": 734,
   "fileName": "",
   "doi": "10.1109/mic.2017.37",
   "venue": "IEEE Internet Computing"
  },
  {
   "id": "N293",
   "title": "Applications of wireless sensor networks for urban areas: A survey",
   "year": 2015,
   "citations": 734,
   "fileName": "",
   "doi": "10.1016/j.jnca.2015.09.008",
   "venue": "Journal of Network and Computer Applications"
  },
  {
   "id": "N294",
   "title": "Computation Offloading and Resource Allocation in Wireless Cellular Networks With Mobile Edge Computing",
   "year": 2017,
   "citations": 733,
   "fileName": "",
   "doi": "10.1109/twc.2017.2703901",
   "venue": "IEEE Transactions on Wireless Communications"
  },
  {
   "id": "N295",
   "title": "CONGA",
   "year": 2014,
   "citations": 733,
   "fileName": "",
   "doi": "10.1145/2619239.2626316",
   "venue": ""
  },
  {
   "id": "N296",
   "title": "A Survey on 5G Usage Scenarios and Traffic Models",
   "year": 2020,
   "citations": 732,
   "fileName": "",
   "doi": "10.1109/comst.2020.2971781",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N297",
   "title": "Distributed Formation Control of Networked Multi-Agent Systems Using a Dynamic Event-Triggered Communication Mechanism",
   "year": 2017,
   "citations": 732,
   "fileName": "",
   "doi": "10.1109/tie.2017.2701778",
   "venue": "IEEE Transactions on Industrial Electronics"
  },
  {
   "id": "N298",
   "title": "IoT Security: Ongoing Challenges and Research Opportunities",
   "year": 2014,
   "citations": 731,
   "fileName": "",
   "doi": "10.1109/soca.2014.58",
   "venue": "IEEE International Conference on Service-Oriented Computing and Applications (SOCA)"
  },
  {
   "id": "N299",
   "title": "A Survey of Man In The Middle Attacks",
   "year": 2016,
   "citations": 730,
   "fileName": "",
   "doi": "10.1109/comst.2016.2548426",
   "venue": "IEEE Communications Surveys & Tutorials"
  },
  {
   "id": "N300",
   "title": "Federated-Learning-Based Anomaly Detection for IoT Security Attacks",
   "year": 2021,
   "citations": 729,
   "fileName": "",
   "doi": "10.1109/jiot.2021.3077803",
   "venue": "IEEE Internet of Things Journal"
  }
 ]
};
