/* GENERATED by scripts/od_build.py — do not edit by hand. */
import type { AuditCheck } from "./types";
import { PAPERS, PAPER_BY_ID, PAPER_COUNT } from "./papers";
import { PROBLEM_LIFECYCLES } from "./problems";
import { SOLUTIONS } from "./solutions";
import { YEAR_STATES } from "./years";
import { RELATIONS } from "./relations";
import { BENCHMARKS } from "./benchmarks";
import { DATASETS } from "./datasets";
import { METRICS } from "./metrics";

const ids = new Set(PAPERS.map((p) => p.id));

function check(id: string, label: string, ok: boolean, detail: string): AuditCheck {
  return { id, label, pass: ok, detail };
}

/** Deterministic integrity checks over the generated corpus data.
 *  Quote-level provenance is checked in __tests__/audit.test.ts against
 *  the harvest JSON records (which are themselves verified against the
 *  extracted PDF text by scripts/od_harvest_check.py). */
export function runAudit(): AuditCheck[] {
  const checks: AuditCheck[] = [];

  const dupIds = PAPERS.length - ids.size;
  checks.push(check("unique-ids", "Every paper id is unique", dupIds === 0,
    `${dupIds} duplicate ids`));

  const badYear = PAPERS.filter((p) => !p.year);
  checks.push(check("paper-years", "Every paper has a year", badYear.length === 0,
    `${badYear.length} papers missing year`));

  const badSummary = PAPERS.filter((p) => !p.summary || !p.problemSummary);
  checks.push(check("summaries", "Every paper has summaries", badSummary.length === 0,
    `${badSummary.length} papers missing summary`));

  const noEvidence = PAPERS.filter((p) => p.evidences.length === 0);
  checks.push(check("paper-evidence", "Every paper evidences ≥1 corpus concept",
    noEvidence.length === 0, `${noEvidence.length} papers with empty evidences`));

  const problemIds = new Set(PROBLEM_LIFECYCLES.map((p) => p.id));
  const solutionIds = new Set(SOLUTIONS.map((s) => s.id));
  const badTags: string[] = [];
  for (const p of PAPERS) {
    for (const t of p.problemTags) if (!problemIds.has(t)) badTags.push(`${p.id}:${t}`);
    for (const t of p.solutionTags) if (!solutionIds.has(t)) badTags.push(`${p.id}:${t}`);
  }
  checks.push(check("tag-vocabulary",
    "Every problem/solution tag resolves to the dictionary",
    badTags.length === 0, badTags.slice(0, 5).join(", ") || "all resolve"));

  const referenced = new Set<string>();
  for (const pr of PROBLEM_LIFECYCLES)
    for (const o of pr.occurrences) for (const pid of o.papers) referenced.add(pid);
  for (const s of SOLUTIONS) for (const pid of s.paperIds) referenced.add(pid);
  for (const r of RELATIONS) { referenced.add(r.from); referenced.add(r.to); }
  for (const b of BENCHMARKS) referenced.add(b.paperId);
  for (const d of DATASETS) for (const pid of d.paperIds) referenced.add(pid);
  for (const m of METRICS) for (const pid of m.papers) referenced.add(pid);
  for (const y of Object.values(YEAR_STATES))
    for (const pid of y.supportingPapers) referenced.add(pid);
  const dangling = [...referenced].filter((pid) => !ids.has(pid));
  checks.push(check("referential-integrity",
    "Every referenced paperId resolves", dangling.length === 0,
    dangling.slice(0, 5).join(", ") || "all resolve"));

  const uncovered = PAPERS.filter(
    (p) => !YEAR_STATES[p.year] || !YEAR_STATES[p.year].supportingPapers.includes(p.id),
  );
  checks.push(check("year-coverage", "Every paper appears in its year state",
    uncovered.length === 0, `${uncovered.length} uncovered`));

  const emptyYears = Object.values(YEAR_STATES).filter(
    (y) => y.supportingPapers.length !== PAPERS.filter((p) => p.year === y.year).length,
  );
  checks.push(check("year-counts", "Year paper counts match corpus",
    emptyYears.length === 0,
    emptyYears.map((y) => String(y.year)).join(", ") || "all match"));

  const emptyProblems = PROBLEM_LIFECYCLES.filter((p) => p.occurrences.length === 0);
  checks.push(check("problem-occurrences", "Every problem has occurrences",
    emptyProblems.length === 0,
    emptyProblems.map((p) => p.id).join(", ") || "all have occurrences"));

  const summaryOk = PAPER_COUNT === PAPERS.length;
  checks.push(check("count", "PAPER_COUNT matches array length", summaryOk,
    `${PAPER_COUNT} vs ${PAPERS.length}`));

  return checks;
}

export function countPapersByYear(): Record<number, number> {
  const out: Record<number, number> = {};
  for (const p of PAPERS) out[p.year] = (out[p.year] ?? 0) + 1;
  return out;
}

export { PAPER_BY_ID };
