/* GENERATED by scripts/od_build.py — do not edit by hand. */
import type { Analogy } from "./types";

export const ANALOGIES: Analogy[] = [
 {
  "id": "human-receptive-field-eccentricity",
  "domain": "human visual system",
  "sourceConcept": "population receptive fields in human visual cortex grow with eccentricity",
  "detectionConcept": "multi-branch receptive-field module (RFB) for one-stage detectors",
  "mapping": "RFB Net builds a convolutional block whose branch kernel sizes and dilation-controlled eccentricities mimic how cortical receptive fields change with eccentricity, so feature discriminability improves without a deeper, heavier backbone.",
  "paperIds": [
   "OD025"
  ]
 },
 {
  "id": "saccadic-attention-sampling",
  "domain": "human visual system",
  "sourceConcept": "saccadic eye movements that sample only informative image regions",
  "detectionConcept": "attention-guided selective crop inference (CornerNet-Saccade)",
  "mapping": "CornerNet-Saccade treats inference like a saccade: an attention map predicts promising locations on a downsized image and high-resolution crops are processed only there, cutting the number of pixels examined rather than scanning the whole image.",
  "paperIds": [
   "OD051"
  ]
 },
 {
  "id": "bayesian-uncertainty-boxes",
  "domain": "Bayesian statistics",
  "sourceConcept": "Bayesian neural network predictive uncertainty with loss attenuation",
  "detectionConcept": "per-box Gaussian localization uncertainty used to suppress false positives",
  "mapping": "Gaussian YOLOv3 imports Kendall and Gal's Bayesian uncertainty modeling: every box coordinate gets a Gaussian, an NLL loss attenuates noisy targets during training, and predicted uncertainty down-weights detections during post-processing.",
  "paperIds": [
   "OD047"
  ]
 },
 {
  "id": "kalman-filter-forecasting",
  "domain": "control theory / Kalman filtering",
  "sourceConcept": "Kalman-filter state estimation for forecasting object motion",
  "detectionConcept": "learned trend-aware box forecasting for streaming detection",
  "mapping": "For streaming perception the corpus sets learned dual-flow trend forecasting against classical Kalman-filter forecasting as the baseline to beat, replacing explicit state estimation with learned motion cues that the paper reports are far cheaper per frame.",
  "paperIds": [
   "OD086"
  ]
 },
 {
  "id": "optimal-transport-label-assignment",
  "domain": "optimal transport / linear programming",
  "sourceConcept": "optimal transport with supply and demand constraints solved by entropic Sinkhorn-Knopp iteration",
  "detectionConcept": "global positive/negative label assignment across anchors and ground truths",
  "mapping": "OTA formulates label assignment as an optimal transport problem in which each ground truth is a supplier of k labels and each anchor a demander of one, solved by Sinkhorn-Knopp instead of per-object hand-crafted thresholds; YOLOX then adopts the same OT assignment as its SimOTA base.",
  "paperIds": [
   "OD069",
   "OD075"
  ]
 },
 {
  "id": "diffusion-noise-to-boxes",
  "domain": "denoising diffusion generative modeling",
  "sourceConcept": "forward noising process with a learned reverse denoising process",
  "detectionConcept": "object detection as a noise-to-box denoising process (DiffusionDet)",
  "mapping": "DiffusionDet recasts detection as a diffusion process: ground-truth boxes are padded and noised in training and the model learns to reverse that process, so inference starts from random Gaussian boxes and iteratively refines them into object boxes.",
  "paperIds": [
   "OD092"
  ]
 },
 {
  "id": "genetic-hyperparameter-search",
  "domain": "evolutionary optimization",
  "sourceConcept": "genetic-algorithm search over design hyper-parameters",
  "detectionConcept": "detector recipe, anchor and augmentation tuning",
  "mapping": "YOLOv4 and YOLOv4-large outsource design choices to evolution: genetic algorithms select anchor boxes and the bag-of-freebies hyper-parameters alongside k-means clustering, replacing hand-tuning of each training and architecture choice.",
  "paperIds": [
   "OD056",
   "OD064"
  ]
 },
 {
  "id": "language-modeling-as-detection",
  "domain": "natural language processing / language modeling",
  "sourceConcept": "autoregressive language modeling over discrete token sequences",
  "detectionConcept": "boxes and classes emitted as generated token sequences (Pix2Seq)",
  "mapping": "Pix2Seq casts object detection as a language modeling task: boxes and labels are quantized into discrete tokens and decoded autoregressively with a generic maximum-likelihood objective, so no detection-specific architecture or loss is needed.",
  "paperIds": [
   "OD079"
  ]
 },
 {
  "id": "phrase-grounding-vision-language",
  "domain": "computational linguistics / vision-language grounding",
  "sourceConcept": "phrase grounding, aligning regions to noun phrases in a text prompt",
  "detectionConcept": "open-vocabulary detection via unified region-language grounding",
  "mapping": "GLIP reformulates classification as grounding every region to phrases of a text prompt, and Grounding DINO and YOLOE extend the same language-grounding idea so arbitrary categories can be named by text or prompts at inference time.",
  "paperIds": [
   "OD081",
   "OD095",
   "OD114"
  ]
 }
];
