/* GENERATED by scripts/od_build.py — do not edit by hand. */
import type { MetricInfo } from "./types";

export const METRICS: MetricInfo[] = [
 {
  "id": "ap50",
  "name": "AP50",
  "paperCount": 91,
  "papers": [
   "OD001",
   "OD004",
   "OD006",
   "OD009",
   "OD010",
   "OD012",
   "OD013",
   "OD014",
   "OD015",
   "OD019",
   "OD020",
   "OD021",
   "OD025",
   "OD026",
   "OD029",
   "OD030",
   "OD033",
   "OD034",
   "OD035",
   "OD036",
   "OD037",
   "OD038",
   "OD039",
   "OD040",
   "OD041",
   "OD043",
   "OD044",
   "OD045",
   "OD046",
   "OD048",
   "OD049",
   "OD050",
   "OD052",
   "OD053",
   "OD054",
   "OD055",
   "OD056",
   "OD057",
   "OD058",
   "OD059",
   "OD060",
   "OD061",
   "OD062",
   "OD063",
   "OD064",
   "OD065",
   "OD066",
   "OD067",
   "OD068",
   "OD069",
   "OD070",
   "OD071",
   "OD072",
   "OD073",
   "OD074",
   "OD075",
   "OD076",
   "OD077",
   "OD078",
   "OD079",
   "OD080",
   "OD081",
   "OD082",
   "OD083",
   "OD084",
   "OD085",
   "OD087",
   "OD089",
   "OD090",
   "OD091",
   "OD092",
   "OD093",
   "OD094",
   "OD095",
   "OD096",
   "OD097",
   "OD098",
   "OD099",
   "OD100",
   "OD101",
   "OD102",
   "OD104",
   "OD105",
   "OD107",
   "OD108",
   "OD109",
   "OD112",
   "OD113",
   "OD115",
   "OD116",
   "OD117"
  ],
  "note": "Reported by 91 papers"
 },
 {
  "id": "ap",
  "name": "AP",
  "paperCount": 78,
  "papers": [
   "OD002",
   "OD003",
   "OD004",
   "OD006",
   "OD010",
   "OD014",
   "OD015",
   "OD017",
   "OD018",
   "OD020",
   "OD021",
   "OD026",
   "OD027",
   "OD029",
   "OD030",
   "OD034",
   "OD036",
   "OD037",
   "OD038",
   "OD039",
   "OD041",
   "OD043",
   "OD044",
   "OD045",
   "OD046",
   "OD047",
   "OD048",
   "OD049",
   "OD050",
   "OD051",
   "OD052",
   "OD053",
   "OD054",
   "OD055",
   "OD056",
   "OD057",
   "OD058",
   "OD059",
   "OD060",
   "OD062",
   "OD063",
   "OD064",
   "OD065",
   "OD066",
   "OD067",
   "OD068",
   "OD069",
   "OD070",
   "OD073",
   "OD075",
   "OD076",
   "OD078",
   "OD079",
   "OD080",
   "OD081",
   "OD082",
   "OD084",
   "OD085",
   "OD091",
   "OD092",
   "OD093",
   "OD095",
   "OD096",
   "OD097",
   "OD098",
   "OD099",
   "OD101",
   "OD103",
   "OD104",
   "OD106",
   "OD107",
   "OD108",
   "OD109",
   "OD112",
   "OD114",
   "OD115",
   "OD117",
   "OD121"
  ],
  "note": "Reported by 78 papers"
 },
 {
  "id": "ap75",
  "name": "AP75",
  "paperCount": 72,
  "papers": [
   "OD014",
   "OD020",
   "OD021",
   "OD026",
   "OD029",
   "OD030",
   "OD033",
   "OD034",
   "OD035",
   "OD036",
   "OD037",
   "OD038",
   "OD039",
   "OD040",
   "OD041",
   "OD043",
   "OD044",
   "OD045",
   "OD046",
   "OD047",
   "OD048",
   "OD049",
   "OD050",
   "OD053",
   "OD054",
   "OD055",
   "OD056",
   "OD057",
   "OD058",
   "OD059",
   "OD060",
   "OD061",
   "OD062",
   "OD063",
   "OD064",
   "OD065",
   "OD066",
   "OD067",
   "OD068",
   "OD069",
   "OD070",
   "OD071",
   "OD072",
   "OD073",
   "OD075",
   "OD076",
   "OD077",
   "OD078",
   "OD079",
   "OD080",
   "OD082",
   "OD084",
   "OD085",
   "OD087",
   "OD089",
   "OD090",
   "OD092",
   "OD093",
   "OD094",
   "OD095",
   "OD096",
   "OD097",
   "OD098",
   "OD100",
   "OD101",
   "OD102",
   "OD104",
   "OD109",
   "OD112",
   "OD113",
   "OD115",
   "OD117"
  ],
  "note": "Reported by 72 papers"
 },
 {
  "id": "fps",
  "name": "FPS",
  "paperCount": 67,
  "papers": [
   "OD001",
   "OD002",
   "OD004",
   "OD007",
   "OD008",
   "OD010",
   "OD011",
   "OD012",
   "OD014",
   "OD018",
   "OD019",
   "OD021",
   "OD023",
   "OD025",
   "OD027",
   "OD030",
   "OD032",
   "OD034",
   "OD038",
   "OD039",
   "OD044",
   "OD045",
   "OD047",
   "OD049",
   "OD052",
   "OD056",
   "OD057",
   "OD058",
   "OD060",
   "OD061",
   "OD062",
   "OD063",
   "OD064",
   "OD066",
   "OD067",
   "OD068",
   "OD071",
   "OD072",
   "OD073",
   "OD075",
   "OD077",
   "OD078",
   "OD080",
   "OD081",
   "OD085",
   "OD086",
   "OD087",
   "OD089",
   "OD091",
   "OD094",
   "OD095",
   "OD096",
   "OD098",
   "OD099",
   "OD101",
   "OD103",
   "OD105",
   "OD107",
   "OD109",
   "OD110",
   "OD111",
   "OD112",
   "OD114",
   "OD116",
   "OD117",
   "OD118",
   "OD119"
  ],
  "note": "Reported by 67 papers"
 },
 {
  "id": "map",
  "name": "mAP",
  "paperCount": 55,
  "papers": [
   "OD001",
   "OD002",
   "OD004",
   "OD005",
   "OD006",
   "OD008",
   "OD009",
   "OD011",
   "OD012",
   "OD013",
   "OD015",
   "OD016",
   "OD017",
   "OD018",
   "OD019",
   "OD021",
   "OD022",
   "OD023",
   "OD024",
   "OD025",
   "OD027",
   "OD028",
   "OD030",
   "OD031",
   "OD032",
   "OD035",
   "OD037",
   "OD038",
   "OD040",
   "OD041",
   "OD042",
   "OD043",
   "OD045",
   "OD047",
   "OD052",
   "OD061",
   "OD067",
   "OD068",
   "OD069",
   "OD070",
   "OD071",
   "OD074",
   "OD077",
   "OD087",
   "OD089",
   "OD090",
   "OD094",
   "OD100",
   "OD102",
   "OD105",
   "OD110",
   "OD116",
   "OD118",
   "OD119",
   "OD121"
  ],
  "note": "Reported by 55 papers"
 },
 {
  "id": "aps",
  "name": "APs",
  "paperCount": 52,
  "papers": [
   "OD009",
   "OD014",
   "OD020",
   "OD021",
   "OD026",
   "OD029",
   "OD033",
   "OD034",
   "OD036",
   "OD037",
   "OD038",
   "OD039",
   "OD041",
   "OD043",
   "OD046",
   "OD048",
   "OD051",
   "OD054",
   "OD062",
   "OD063",
   "OD064",
   "OD065",
   "OD066",
   "OD067",
   "OD068",
   "OD069",
   "OD070",
   "OD071",
   "OD072",
   "OD073",
   "OD075",
   "OD076",
   "OD078",
   "OD079",
   "OD080",
   "OD082",
   "OD084",
   "OD085",
   "OD087",
   "OD089",
   "OD090",
   "OD092",
   "OD093",
   "OD096",
   "OD097",
   "OD098",
   "OD100",
   "OD102",
   "OD104",
   "OD109",
   "OD112",
   "OD113"
  ],
  "note": "Reported by 52 papers"
 },
 {
  "id": "apm",
  "name": "APm",
  "paperCount": 51,
  "papers": [
   "OD014",
   "OD020",
   "OD026",
   "OD029",
   "OD033",
   "OD034",
   "OD036",
   "OD037",
   "OD038",
   "OD039",
   "OD041",
   "OD043",
   "OD046",
   "OD048",
   "OD051",
   "OD054",
   "OD062",
   "OD063",
   "OD064",
   "OD065",
   "OD066",
   "OD067",
   "OD068",
   "OD069",
   "OD070",
   "OD071",
   "OD072",
   "OD073",
   "OD075",
   "OD076",
   "OD078",
   "OD079",
   "OD080",
   "OD082",
   "OD084",
   "OD085",
   "OD087",
   "OD089",
   "OD090",
   "OD092",
   "OD093",
   "OD096",
   "OD097",
   "OD098",
   "OD100",
   "OD102",
   "OD104",
   "OD109",
   "OD112",
   "OD113",
   "OD114"
  ],
  "note": "Reported by 51 papers"
 },
 {
  "id": "apl",
  "name": "APL",
  "paperCount": 50,
  "papers": [
   "OD014",
   "OD020",
   "OD026",
   "OD029",
   "OD033",
   "OD034",
   "OD036",
   "OD037",
   "OD038",
   "OD039",
   "OD041",
   "OD043",
   "OD046",
   "OD048",
   "OD051",
   "OD054",
   "OD062",
   "OD063",
   "OD064",
   "OD065",
   "OD066",
   "OD067",
   "OD068",
   "OD069",
   "OD070",
   "OD071",
   "OD072",
   "OD073",
   "OD075",
   "OD076",
   "OD078",
   "OD079",
   "OD080",
   "OD082",
   "OD084",
   "OD085",
   "OD087",
   "OD089",
   "OD090",
   "OD092",
   "OD093",
   "OD096",
   "OD097",
   "OD098",
   "OD100",
   "OD102",
   "OD104",
   "OD109",
   "OD112",
   "OD113"
  ],
  "note": "Reported by 50 papers"
 },
 {
  "id": "latency-ms",
  "name": "latency (ms)",
  "paperCount": 25,
  "papers": [
   "OD009",
   "OD018",
   "OD020",
   "OD025",
   "OD031",
   "OD037",
   "OD039",
   "OD051",
   "OD053",
   "OD071",
   "OD075",
   "OD086",
   "OD087",
   "OD088",
   "OD096",
   "OD105",
   "OD106",
   "OD108",
   "OD109",
   "OD110",
   "OD112",
   "OD113",
   "OD115",
   "OD116",
   "OD117"
  ],
  "note": "Reported by 25 papers"
 },
 {
  "id": "parameters",
  "name": "parameters",
  "paperCount": 21,
  "papers": [
   "OD019",
   "OD028",
   "OD031",
   "OD053",
   "OD057",
   "OD071",
   "OD073",
   "OD075",
   "OD082",
   "OD088",
   "OD089",
   "OD091",
   "OD094",
   "OD096",
   "OD101",
   "OD102",
   "OD104",
   "OD110",
   "OD113",
   "OD115",
   "OD116"
  ],
  "note": "Reported by 21 papers"
 },
 {
  "id": "flops",
  "name": "FLOPs",
  "paperCount": 20,
  "papers": [
   "OD009",
   "OD028",
   "OD045",
   "OD047",
   "OD053",
   "OD056",
   "OD063",
   "OD064",
   "OD073",
   "OD080",
   "OD088",
   "OD089",
   "OD091",
   "OD094",
   "OD099",
   "OD102",
   "OD104",
   "OD105",
   "OD113",
   "OD116"
  ],
  "note": "Reported by 20 papers"
 },
 {
  "id": "gflops",
  "name": "GFLOPs",
  "paperCount": 17,
  "papers": [
   "OD057",
   "OD061",
   "OD068",
   "OD070",
   "OD071",
   "OD075",
   "OD076",
   "OD078",
   "OD082",
   "OD084",
   "OD085",
   "OD087",
   "OD096",
   "OD108",
   "OD109",
   "OD115",
   "OD117"
  ],
  "note": "Reported by 17 papers"
 },
 {
  "id": "ar",
  "name": "AR",
  "paperCount": 12,
  "papers": [
   "OD004",
   "OD005",
   "OD010",
   "OD026",
   "OD036",
   "OD044",
   "OD046",
   "OD050",
   "OD055",
   "OD079",
   "OD097",
   "OD105"
  ],
  "note": "Reported by 12 papers"
 },
 {
  "id": "aps-apm-apl",
  "name": "APs/APm/APL",
  "paperCount": 11,
  "papers": [
   "OD010",
   "OD012",
   "OD023",
   "OD055",
   "OD056",
   "OD057",
   "OD058",
   "OD059",
   "OD060",
   "OD077",
   "OD115"
  ],
  "note": "Reported by 11 papers"
 },
 {
  "id": "recall",
  "name": "recall",
  "paperCount": 9,
  "papers": [
   "OD003",
   "OD008",
   "OD011",
   "OD015",
   "OD066",
   "OD069",
   "OD070",
   "OD081",
   "OD116"
  ],
  "note": "Reported by 9 papers"
 },
 {
  "id": "mask-ap",
  "name": "mask AP",
  "paperCount": 8,
  "papers": [
   "OD014",
   "OD033",
   "OD040",
   "OD055",
   "OD072",
   "OD088",
   "OD101",
   "OD111"
  ],
  "note": "Reported by 8 papers"
 },
 {
  "id": "top-1-accuracy",
  "name": "top-1 accuracy",
  "paperCount": 7,
  "papers": [
   "OD011",
   "OD016",
   "OD026",
   "OD031",
   "OD034",
   "OD056",
   "OD095"
  ],
  "note": "Reported by 7 papers"
 },
 {
  "id": "latency",
  "name": "latency",
  "paperCount": 7,
  "papers": [
   "OD091",
   "OD094",
   "OD098",
   "OD099",
   "OD104",
   "OD118",
   "OD119"
  ],
  "note": "Reported by 7 papers"
 },
 {
  "id": "apr",
  "name": "APr",
  "paperCount": 6,
  "papers": [
   "OD081",
   "OD101",
   "OD103",
   "OD106",
   "OD111",
   "OD114"
  ],
  "note": "Reported by 6 papers"
 },
 {
  "id": "gpu-memory",
  "name": "GPU memory",
  "paperCount": 5,
  "papers": [
   "OD009",
   "OD051",
   "OD078",
   "OD088",
   "OD100"
  ],
  "note": "Reported by 5 papers"
 },
 {
  "id": "training-time",
  "name": "training time",
  "paperCount": 5,
  "papers": [
   "OD022",
   "OD072",
   "OD100",
   "OD112",
   "OD114"
  ],
  "note": "Reported by 5 papers"
 },
 {
  "id": "ap90",
  "name": "AP90",
  "paperCount": 5,
  "papers": [
   "OD029",
   "OD036",
   "OD037",
   "OD041",
   "OD060"
  ],
  "note": "Reported by 5 papers"
 },
 {
  "id": "box-ap",
  "name": "box AP",
  "paperCount": 5,
  "papers": [
   "OD033",
   "OD040",
   "OD072",
   "OD088",
   "OD111"
  ],
  "note": "Reported by 5 papers"
 },
 {
  "id": "apc",
  "name": "APc",
  "paperCount": 5,
  "papers": [
   "OD081",
   "OD101",
   "OD103",
   "OD106",
   "OD114"
  ],
  "note": "Reported by 5 papers"
 },
 {
  "id": "apf",
  "name": "APf",
  "paperCount": 5,
  "papers": [
   "OD081",
   "OD101",
   "OD103",
   "OD106",
   "OD114"
  ],
  "note": "Reported by 5 papers"
 },
 {
  "id": "miou",
  "name": "mIoU",
  "paperCount": 4,
  "papers": [
   "OD013",
   "OD031",
   "OD053",
   "OD099"
  ],
  "note": "Reported by 4 papers"
 },
 {
  "id": "keypoint-ap",
  "name": "keypoint AP",
  "paperCount": 4,
  "papers": [
   "OD014",
   "OD040",
   "OD049",
   "OD111"
  ],
  "note": "Reported by 4 papers"
 },
 {
  "id": "mmr",
  "name": "mMR",
  "paperCount": 4,
  "papers": [
   "OD024",
   "OD066",
   "OD070",
   "OD098"
  ],
  "note": "Reported by 4 papers"
 },
 {
  "id": "latency-s-img",
  "name": "latency (s/img)",
  "paperCount": 3,
  "papers": [
   "OD006",
   "OD029",
   "OD082"
  ],
  "note": "Reported by 3 papers"
 },
 {
  "id": "top-5-accuracy",
  "name": "top-5 accuracy",
  "paperCount": 3,
  "papers": [
   "OD011",
   "OD034",
   "OD056"
  ],
  "note": "Reported by 3 papers"
 },
 {
  "id": "ap80",
  "name": "AP80",
  "paperCount": 3,
  "papers": [
   "OD029",
   "OD041",
   "OD060"
  ],
  "note": "Reported by 3 papers"
 },
 {
  "id": "parameters-m",
  "name": "parameters (M)",
  "paperCount": 3,
  "papers": [
   "OD106",
   "OD107",
   "OD108"
  ],
  "note": "Reported by 3 papers"
 },
 {
  "id": "f1",
  "name": "F1",
  "paperCount": 2,
  "papers": [
   "OD002",
   "OD116"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "ap-by-object-size",
  "name": "AP by object size",
  "paperCount": 2,
  "papers": [
   "OD005",
   "OD006"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "top-1-error",
  "name": "top-1 error",
  "paperCount": 2,
  "papers": [
   "OD008",
   "OD045"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "madds",
  "name": "MAdds",
  "paperCount": 2,
  "papers": [
   "OD016",
   "OD031"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "ap60",
  "name": "AP60",
  "paperCount": 2,
  "papers": [
   "OD029",
   "OD060"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "ap70",
  "name": "AP70",
  "paperCount": 2,
  "papers": [
   "OD029",
   "OD060"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "pq",
  "name": "PQ",
  "paperCount": 2,
  "papers": [
   "OD057",
   "OD065"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "epochs",
  "name": "epochs",
  "paperCount": 2,
  "papers": [
   "OD070",
   "OD076"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "mask-map",
  "name": "mask mAP",
  "paperCount": 2,
  "papers": [
   "OD074",
   "OD090"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "precision",
  "name": "precision",
  "paperCount": 2,
  "papers": [
   "OD116",
   "OD120"
  ],
  "note": "Reported by 2 papers"
 },
 {
  "id": "recall-vs-iou",
  "name": "recall-vs-IoU",
  "paperCount": 1,
  "papers": [
   "OD001"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "true-positive-rate",
  "name": "true positive rate",
  "paperCount": 1,
  "papers": [
   "OD003"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "false-positives-per-image",
  "name": "false positives per image",
  "paperCount": 1,
  "papers": [
   "OD003"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "miss-rate",
  "name": "miss rate",
  "paperCount": 1,
  "papers": [
   "OD007"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "roc",
  "name": "ROC",
  "paperCount": 1,
  "papers": [
   "OD007"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "top-5-error",
  "name": "top-5 error",
  "paperCount": 1,
  "papers": [
   "OD008"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "gmacs",
  "name": "GMACs",
  "paperCount": 1,
  "papers": [
   "OD008"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "map-75",
  "name": "mAP@.75",
  "paperCount": 1,
  "papers": [
   "OD009"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "average-iou",
  "name": "average IOU",
  "paperCount": 1,
  "papers": [
   "OD011"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "map-0-7",
  "name": "mAP@0.7",
  "paperCount": 1,
  "papers": [
   "OD013"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "accuracy",
  "name": "accuracy",
  "paperCount": 1,
  "papers": [
   "OD016"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "iou-threshold",
  "name": "IoU threshold",
  "paperCount": 1,
  "papers": [
   "OD017"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "mmar",
  "name": "mmAR",
  "paperCount": 1,
  "papers": [
   "OD022"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "fppi",
  "name": "FPPI",
  "paperCount": 1,
  "papers": [
   "OD024"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "bep",
  "name": "BEP",
  "paperCount": 1,
  "papers": [
   "OD027"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "std-ap",
  "name": "STD AP",
  "paperCount": 1,
  "papers": [
   "OD027"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "std-as",
  "name": "STD AS",
  "paperCount": 1,
  "papers": [
   "OD027"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "map50",
  "name": "mAP50",
  "paperCount": 1,
  "papers": [
   "OD028"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "map75",
  "name": "mAP75",
  "paperCount": 1,
  "papers": [
   "OD028"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "iou",
  "name": "IoU",
  "paperCount": 1,
  "papers": [
   "OD035"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "ars",
  "name": "ARs",
  "paperCount": 1,
  "papers": [
   "OD044"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "arm",
  "name": "ARm",
  "paperCount": 1,
  "papers": [
   "OD044"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "arl",
  "name": "ARl",
  "paperCount": 1,
  "papers": [
   "OD044"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "bpr",
  "name": "BPR",
  "paperCount": 1,
  "papers": [
   "OD046"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "fp",
  "name": "FP",
  "paperCount": 1,
  "papers": [
   "OD047"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "tp",
  "name": "TP",
  "paperCount": 1,
  "papers": [
   "OD047"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "iou",
  "name": "IOU",
  "paperCount": 1,
  "papers": [
   "OD047"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "aos",
  "name": "AOS",
  "paperCount": 1,
  "papers": [
   "OD049"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "bev-ap",
  "name": "BEV AP",
  "paperCount": 1,
  "papers": [
   "OD049"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "fd-rate",
  "name": "FD rate",
  "paperCount": 1,
  "papers": [
   "OD050"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "sq",
  "name": "SQ",
  "paperCount": 1,
  "papers": [
   "OD057"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "rq",
  "name": "RQ",
  "paperCount": 1,
  "papers": [
   "OD057"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "iou-prediction-error",
  "name": "IoU prediction error",
  "paperCount": 1,
  "papers": [
   "OD059"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "pqth",
  "name": "PQth",
  "paperCount": 1,
  "papers": [
   "OD065"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "mr",
  "name": "MR",
  "paperCount": 1,
  "papers": [
   "OD069"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "map-0-75",
  "name": "mAP@0.75",
  "paperCount": 1,
  "papers": [
   "OD074"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "mmap-ap-iou-0-5-0-95",
  "name": "mmAP (AP IoU 0.5:0.95)",
  "paperCount": 1,
  "papers": [
   "OD077"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "ars-arm-arl",
  "name": "ARs/ARm/ARl",
  "paperCount": 1,
  "papers": [
   "OD077"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "ap50-small",
  "name": "AP50 (small)",
  "paperCount": 1,
  "papers": [
   "OD083"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "ap50-medium",
  "name": "AP50 (medium)",
  "paperCount": 1,
  "papers": [
   "OD083"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "ap50-large",
  "name": "AP50 (large)",
  "paperCount": 1,
  "papers": [
   "OD083"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "sap",
  "name": "sAP",
  "paperCount": 1,
  "papers": [
   "OD086"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "sap50",
  "name": "sAP50",
  "paperCount": 1,
  "papers": [
   "OD086"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "sap75",
  "name": "sAP75",
  "paperCount": 1,
  "papers": [
   "OD086"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "saps",
  "name": "sAPs",
  "paperCount": 1,
  "papers": [
   "OD086"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "sapm",
  "name": "sAPm",
  "paperCount": 1,
  "papers": [
   "OD086"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "sapl",
  "name": "sAPl",
  "paperCount": 1,
  "papers": [
   "OD086"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "apmask-rare",
  "name": "APmask rare",
  "paperCount": 1,
  "papers": [
   "OD088"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "nds",
  "name": "NDS",
  "paperCount": 1,
  "papers": [
   "OD090"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "apr-apc-apf",
  "name": "APr/APc/APf",
  "paperCount": 1,
  "papers": [
   "OD095"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "apaverage",
  "name": "APaverage",
  "paperCount": 1,
  "papers": [
   "OD095"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "apmedian",
  "name": "APmedian",
  "paperCount": 1,
  "papers": [
   "OD095"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "ji",
  "name": "JI",
  "paperCount": 1,
  "papers": [
   "OD098"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "macc",
  "name": "mAcc",
  "paperCount": 1,
  "papers": [
   "OD099"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "mask-map",
  "name": "Mask mAP",
  "paperCount": 1,
  "papers": [
   "OD100"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "apall",
  "name": "APall",
  "paperCount": 1,
  "papers": [
   "OD103"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "apavg",
  "name": "APavg",
  "paperCount": 1,
  "papers": [
   "OD103"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "mae",
  "name": "MAE",
  "paperCount": 1,
  "papers": [
   "OD111"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "rmse",
  "name": "RMSE",
  "paperCount": 1,
  "papers": [
   "OD111"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "pck-0-05",
  "name": "PCK@0.05",
  "paperCount": 1,
  "papers": [
   "OD111"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "cider",
  "name": "CIDEr",
  "paperCount": 1,
  "papers": [
   "OD111"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "meteor",
  "name": "METEOR",
  "paperCount": 1,
  "papers": [
   "OD111"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "semantic-similarity",
  "name": "Semantic Similarity",
  "paperCount": 1,
  "papers": [
   "OD111"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "s-iou",
  "name": "S-IoU",
  "paperCount": 1,
  "papers": [
   "OD111"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "map-ap50-95",
  "name": "mAP (AP50:95)",
  "paperCount": 1,
  "papers": [
   "OD113"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "fixed-ap",
  "name": "Fixed AP",
  "paperCount": 1,
  "papers": [
   "OD114"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "success",
  "name": "success",
  "paperCount": 1,
  "papers": [
   "OD120"
  ],
  "note": "Reported by 1 papers"
 },
 {
  "id": "auc",
  "name": "AUC",
  "paperCount": 1,
  "papers": [
   "OD120"
  ],
  "note": "Reported by 1 papers"
 }
];
