/* GENERATED by scripts/od_build.py — do not edit by hand. */
import type { Relation } from "./types";

/* paper -> paper links parsed from background.relatedWork
 * where the referenced work is itself in the corpus. */
export const RELATIONS: Relation[] = [
 {
  "from": "OD001",
  "to": "OD004",
  "kind": "buildsOn",
  "relation": "learned proposal network prior work; not fully convolutional and does not share features with the detector",
  "quote": "MultiBox does not share features between the proposal and detection networks."
 },
 {
  "from": "OD002",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "prior proposal-based pipeline; slow, stages tuned independently",
  "quote": "Selective Search [35] generates potential bounding boxes, a convolutional network extracts features, an SVM scores the boxes, a linear model adjusts the bounding boxes, and non-max suppression eliminates duplicate detections."
 },
 {
  "from": "OD002",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "neural proposal competitor; more accurate but slower variants",
  "quote": "The VGG-16 version of Faster R-CNN is 10 mAP higher but is also 6 times slower than YOLO."
 },
 {
  "from": "OD003",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "two-stage state of the art whose proposal/classification split blocks joint end-to-end training",
  "quote": "the second phase applies a CNN classifier to distinguish different objects for every proposal."
 },
 {
  "from": "OD003",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "closest proposal-network design; needs predefined anchors and multi-scale training",
  "quote": "However, The PRN needs predefined anchors while ours does not."
 },
 {
  "from": "OD003",
  "to": "OD011",
  "kind": "buildsOn",
  "relation": "contemporaneous unified detector with a coarse 7 x 7 output grid",
  "quote": "YOLO [29] also predicts bounding boxes and class probabilities directly from full images in one evaluation."
 },
 {
  "from": "OD003",
  "to": "OD004",
  "kind": "buildsOn",
  "relation": "learned proposal generator with non-translation-invariant anchors",
  "quote": "the MultiBox method generates 800 non-translation-invariant anchors, whereas our DenseBox output translation-invariant bounding boxes like RPN."
 },
 {
  "from": "OD004",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "accuracy state of the art and main baseline; SSD reuses its anchor-box idea without the two-stage merge",
  "quote": "Our SSD is very similar to the region proposal network (RPN) in Faster R-CNN in that we also use a fixed set of (default) boxes for prediction, similar to the anchor boxes in the RPN."
 },
 {
  "from": "OD004",
  "to": "OD011",
  "kind": "buildsOn",
  "relation": "fast single-shot baseline that predicts from a single topmost feature map",
  "quote": "YOLO [5] uses the whole topmost feature map to predict both confidences for multiple categories and bounding boxes (which are shared for these categories)."
 },
 {
  "from": "OD004",
  "to": "OD030",
  "kind": "buildsOn",
  "relation": "source of the default-box training objective and best-overlap matching",
  "quote": "The SSD training objective is derived from the MultiBox objective [7,8] but is extended to handle multiple object categories."
 },
 {
  "from": "OD005",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "prior detectors that pool only from the last convolutional layer, the limitation ION removes",
  "quote": "Recent successful detectors such as Fast R-CNN, Faster R-CNN [30], and SPPnet, all pool from the last convolutional layer (“conv5 3”) in VGG16 [35]."
 },
 {
  "from": "OD006",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "pioneered region proposals with deep networks but crops/warps each region without shared computation",
  "quote": "R-CNN [7] has demonstrated the effectiveness of using region proposals [27, 28] with deep networks."
 },
 {
  "from": "OD006",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "semi-convolutional predecessors: shared conv subnetwork plus per-region subnetwork",
  "quote": "SPPnet [8], Fast R-CNN [6], and Faster R-CNN [18] are “semiconvolutional”, in which a convolutional subnetwork performs shared computation on the entire image and another subnetwork evaluates individual regions."
 },
 {
  "from": "OD006",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "inserts RoI pooling between conv4 and conv5, deepening the RoI-wise subnetwork at a speed cost",
  "quote": "To remedy this issue, in the ResNet paper [9] the RoI pooling layer of the Faster R-CNN detector [18] is unnaturally inserted between two sets of convolutional layers"
 },
 {
  "from": "OD007",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "prior proposal mechanism whose fixed anchor scales/aspect ratios struggle with shape variation",
  "quote": "since the scales and aspect ratios of anchor boxes are pre-designed and fixed, the RPN shows difficult to handle the object candidates with large shape variations"
 },
 {
  "from": "OD007",
  "to": "OD003",
  "kind": "buildsOn",
  "relation": "closest pixel-wise fully convolutional baseline; regresses four distances independently under l2 loss",
  "quote": "However, DenseBox optimizes the four-side distances as four independent variables, under the simplistic `2 loss"
 },
 {
  "from": "OD008",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "detection framework that PVANet follows with modifications",
  "quote": "We basically follow the method of Faster R-CNN[11], but we introduce some modifications specialized for object detection."
 },
 {
  "from": "OD009",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "dominant two-stage meta-architecture and baseline",
  "quote": "half of the submissions to the COCO object detection server as of November 2016 are reported to be based on the Faster R-CNN system in some way."
 },
 {
  "from": "OD009",
  "to": "OD006",
  "kind": "buildsOn",
  "relation": "two-stage meta-architecture designed to minimize per-region computation",
  "quote": "the R-FCN model (using Resnet 101) could achieve comparable accuracy to Faster R-CNN often at faster running times."
 },
 {
  "from": "OD010",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "main baselines; use single-scale features by default",
  "quote": "Fast and Faster R-CNN [11, 29] opt to not use featurized image pyramids under default settings."
 },
 {
  "from": "OD011",
  "to": "OD034",
  "kind": "buildsOn",
  "relation": "the base detector that YOLOv2 improves",
  "quote": "YOLO suffers from a variety of shortcomings relative to state-of-the-art detection systems."
 },
 {
  "from": "OD011",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "source of the anchor-box prior design that YOLOv2 adopts",
  "quote": "Instead of predicting coordinates directly Faster R-CNN predicts bounding boxes using hand-picked priors [15]."
 },
 {
  "from": "OD012",
  "to": "OD006",
  "kind": "buildsOn",
  "relation": "state-of-the-art two-stage baseline and source of the stride-reduction trick",
  "quote": "Following R-FCN [3], we change the conv5 stage’s effective stride from 32 pixels to 16 pixels to increase feature map resolution."
 },
 {
  "from": "OD013",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "state-of-the-art detector used as a host architecture for the new modules",
  "quote": "Faster R-CNN [47] is the state-of-the-art detector."
 },
 {
  "from": "OD014",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "base detection framework extended with a parallel mask branch",
  "quote": "Faster R-CNN [36] advanced this stream by learning the attention mechanism with a Region Proposal Network (RPN)."
 },
 {
  "from": "OD015",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "state-of-the-art detectors used to evaluate Soft-NMS",
  "quote": "state-of-the-art detectors, namely, Faster-RCNN [24], RFCN [16] and Deformable-RFCN."
 },
 {
  "from": "OD017",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "two-stage reference whose RoI pooling supplies context-aware refinement",
  "quote": "In Faster R-CNN [16], it relies on the large receptive field of each overlapping 3x3 area of the last convolutional layer to detect both small and large objects."
 },
 {
  "from": "OD017",
  "to": "OD011",
  "kind": "buildsOn",
  "relation": "other fast single-stage method considered",
  "quote": "YOLO [14] is another fast single stage method which generated promising results, however, it's not as accurate as SSD though the customized version is faster."
 },
 {
  "from": "OD018",
  "to": "OD011",
  "kind": "buildsOn",
  "relation": "earlier single-stage method limited to highest-level features",
  "quote": "However, since YOLO uses only the highest-level1 feature maps to detect objects, there is a lack of lower-level information, which results in somewhat inaccurate detection, especially for small objects."
 },
 {
  "from": "OD018",
  "to": "OD012",
  "kind": "buildsOn",
  "relation": "ResNet-101 + deconvolution accuracy fix that degrades speed",
  "quote": "DSSD [6] could obtain higher accuracy by changing the base network to ResNet-101 [10] and combining the FPN [14] using deconvolution layers in combination with the existing multiple layers to reflect the large scale context."
 },
 {
  "from": "OD019",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "region-proposal-based detectors with integrated RPNs; failed to converge when trained from scratch",
  "quote": "Proposal based methods include R-CNN [5], Fast RCNN [4], Faster R-CNN [27] and R-FCN [19]."
 },
 {
  "from": "OD020",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "dominant two-stage framework that RPN integrated into a single convolution network",
  "quote": "Region Proposal Networks (RPN) integrated proposal generation with the second-stage classifier into a single convolution network, forming the Faster RCNN framework [28]."
 },
 {
  "from": "OD021",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "the two-stage family whose cascade structure and accuracy advantages RefineDet imitates",
  "quote": "the two-stage approach (e.g., R-CNN [16], SPPnet [18], Fast RCNN [15] to Faster R-CNN [36]) achieves dominated performance on several challenging datasets"
 },
 {
  "from": "OD022",
  "to": "OD014",
  "kind": "buildsOn",
  "relation": "state-of-the-art two-stage detector with ROIAlign, one of the large-accuracy references",
  "quote": "Mask R-CNN [14] introduces the ROIAlign and achieves state-of-the-art results for both object detection and instance segmentation."
 },
 {
  "from": "OD023",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "first to put deep neural network features into a detection system",
  "quote": "R-CNN [6] is among the first to utilize deep neural network features into detection system."
 },
 {
  "from": "OD023",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "milestone two-stage detector whose RPN generates proposals from network features",
  "quote": "Following Fast R-CNN, Faster R-CNN [28] introduces Region Proposal Network (RPN) to generate proposals by using network features."
 },
 {
  "from": "OD023",
  "to": "OD006",
  "kind": "buildsOn",
  "relation": "shares computation across RoIs to speed up inference with many proposals",
  "quote": "R-FCN [17] shares computations between RoI subnetworks, which speed up inference when a large number of proposals are utilized."
 },
 {
  "from": "OD024",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "linear regression on Euclidean coordinate distance to the target",
  "quote": "In R-CNN [10], a linear regression model is trained with respect to the Euclidean distance of coordinates of a proposal and its target."
 },
 {
  "from": "OD024",
  "to": "OD007",
  "kind": "buildsOn",
  "relation": "maximizes IoU between predicted and ground-truth box, inspiring the RepGT term",
  "quote": "IoU Loss is proposed in [29] to maximize the IoU between a ground-truth box and a predicted box."
 },
 {
  "from": "OD026",
  "to": "OD014",
  "kind": "buildsOn",
  "relation": "pyramidal feature combination prior work, criticized as unattractive for very small/large objects",
  "quote": "Methods like FPN, Mask-RCNN, RetinaNet [23, 13, 24], which use a pyramidal representation and combine features"
 },
 {
  "from": "OD026",
  "to": "OD015",
  "kind": "buildsOn",
  "relation": "post-processing used to merge detections from pyramid scales",
  "quote": "After classification and bounding-box regression, we use soft-NMS [2] to combine detections from multiple resolutions to obtain the final detection boxes"
 },
 {
  "from": "OD027",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "two-stage baseline benchmarked against DRBox",
  "quote": "Instead of using SS to generate region proposals, Faster R-CNN applies region proposal networks (RPNs) to generate the proposals [19]"
 },
 {
  "from": "OD028",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "base detection architecture that the module is embedded into",
  "quote": "Region proposal network (RPN) [44] is used to generate proposals."
 },
 {
  "from": "OD029",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "two-stage architecture that Cascade R-CNN extends",
  "quote": "the Faster-RCNN [27] achieved further speedsup by introducing a Region Proposal Network (RPN)"
 },
 {
  "from": "OD029",
  "to": "OD014",
  "kind": "buildsOn",
  "relation": "state-of-the-art single-model comparator (uses segmentation masks)",
  "quote": "Note that, unlike Mask R-CNN, no segmentation information is exploited in the Cascade R-CNN."
 },
 {
  "from": "OD030",
  "to": "OD012",
  "kind": "buildsOn",
  "relation": "deconvolution-augmented SSD that is accurate but slow",
  "quote": "In order to improve the accuracy, DSSD [7] suggests to augment SSD+ResNet-101 with deconvolution layers to introduce additional larges-scale context. However, the speed is slow because of the model complexity."
 },
 {
  "from": "OD030",
  "to": "OD019",
  "kind": "buildsOn",
  "relation": "trains detectors from scratch with a DenseNet architecture",
  "quote": "DSOD [30] investigates how to train a object detector from scratch and designs a DenseNet architecture to improve the parameter efficiency."
 },
 {
  "from": "OD032",
  "to": "OD012",
  "kind": "buildsOn",
  "relation": "closest prior method; adds deconvolutional context but loses too much speed",
  "quote": "the Deconvolutional Single Shot Detector (DSSD) [8] is currently one of the best models in terms of detection accuracy and speed at that time."
 },
 {
  "from": "OD033",
  "to": "OD014",
  "kind": "buildsOn",
  "relation": "framework that PANet is built on and improves",
  "quote": "Mask R-CNN [21] is an effective framework falling in this stream. Our work is built on Mask R-CNN and improves it from different aspects."
 },
 {
  "from": "OD034",
  "to": "OD011",
  "kind": "buildsOn",
  "relation": "immediate predecessor whose anchor-cluster formulation is kept",
  "quote": "Following YOLO9000 our system predicts bounding boxes using dimension clusters as anchor boxes [15]."
 },
 {
  "from": "OD034",
  "to": "OD010",
  "kind": "buildsOn",
  "relation": "prior multi-scale feature design mirrored by YOLOv3's three-scale predictions",
  "quote": "Our system extracts features from those scales using a similar concept to feature pyramid networks [8]."
 },
 {
  "from": "OD034",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "two-stage baseline whose dual IOU threshold training scheme was tried and rejected",
  "quote": "Faster RCNN uses two IOU thresholds during training."
 },
 {
  "from": "OD035",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "prior strategy of hand-crafted or clustered priors with per-anchor layers",
  "quote": "To model anchors with deep neural networks, one straight-forward strategy is via enumeration, which is adopted by most of the previous work [31, 38, 24, 29, 30, 22, 10, 21]."
 },
 {
  "from": "OD036",
  "to": "OD005",
  "kind": "buildsOn",
  "relation": "prior anchor-free detector",
  "quote": "DeNet (Tychsen-Smith and Petersson, 2017a) is a two-stage detector which generates RoIs without using anchor boxes."
 },
 {
  "from": "OD037",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "baseline two-stage detector the loss is plugged into",
  "quote": "Current state-of-the-art object detectors (e.g., Faster RCNN [42], Cascade R-CNN [2] and Mask R-CNN [17]) rely on bounding box regression to localize objects."
 },
 {
  "from": "OD037",
  "to": "OD015",
  "kind": "buildsOn",
  "relation": "prior post-processing method var voting composes with",
  "quote": "soft-NMS [1] decays the detection scores of all other neighbors as a continuous function of their overlap with the higher scored bounding box."
 },
 {
  "from": "OD037",
  "to": "OD007",
  "kind": "buildsOn",
  "relation": "prior IoU-based box regression loss",
  "quote": "UnitBox [50] introduced an Intersection over Union (IoU) loss function for bounding box prediction."
 },
 {
  "from": "OD038",
  "to": "OD019",
  "kind": "buildsOn",
  "relation": "prior train-from-scratch detector built on DenseNet deep supervision",
  "quote": "DSOD [32] is the first to train CNN detectors from scratch, in which the deep supervision plays a critical role."
 },
 {
  "from": "OD038",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "prior two-stage pretrained detectors",
  "quote": "With the gradual improvements from Faster R-CNN [28], R-FCN [4], FPN [21] to Mask R-CNN [11], the two-stage methods achieve top performance on several challenging datasets"
 },
 {
  "from": "OD039",
  "to": "OD026",
  "kind": "buildsOn",
  "relation": "image-pyramid strategy that is accurate but too costly for real time",
  "quote": "Despite the performance gain, such a strategy could be costly time-wise and memory-wise, which forbid its application in real-time tasks."
 },
 {
  "from": "OD040",
  "to": "OD019",
  "kind": "buildsOn",
  "relation": "prior from-scratch detector with a specialized architecture",
  "quote": "Shen et al. [41] argued for a set of new design principles to obtain a detector that is optimized for the accuracy when trained from scratch."
 },
 {
  "from": "OD040",
  "to": "OD036",
  "kind": "buildsOn",
  "relation": "other detection-specific from-scratch architectures",
  "quote": "DetNet [25] and CornerNet [22] also present results when training detectors from scratch."
 },
 {
  "from": "OD040",
  "to": "OD014",
  "kind": "buildsOn",
  "relation": "baseline system and hyper-parameters used throughout",
  "quote": "our baselines and hyper-parameters follow Mask R-CNN [13] in the publicly available code of Detectron [10]"
 },
 {
  "from": "OD041",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "base framework whose regression branch is replaced",
  "quote": "Later, FasterRCNN [3] was proposed to solve this problem by utilizing a light region proposal network(RPN) to generate a sparse set of RoIs."
 },
 {
  "from": "OD041",
  "to": "OD014",
  "kind": "buildsOn",
  "relation": "closest two-stage extension; differs by adding a mask branch instead of a grid branch",
  "quote": "Mask R-CNN [5] extended Faster R-CNN by adding a branch for predicting an pixel-wise object mask in parallel with the original bounding box recognition branch."
 },
 {
  "from": "OD041",
  "to": "OD036",
  "kind": "buildsOn",
  "relation": "prior keypoint-based detector, but one-stage bottom-up without instance definition",
  "quote": "CornerNet [9] is a single-stage object detector which uses paired key-points to locate the bounding box of the objects."
 },
 {
  "from": "OD041",
  "to": "OD006",
  "kind": "buildsOn",
  "relation": "prior fully convolutional region-based detector and VOC baseline",
  "quote": "R-FCN [12] proposed to use region-based fully convolution network to replace the original fully connected network."
 },
 {
  "from": "OD042",
  "to": "OD023",
  "kind": "buildsOn",
  "relation": "baseline architecture supplying the light-head efficiency design",
  "quote": "The Light-head R-CNN [34] is proposed to address this problem by using a larger separable convolution to get a thin feature."
 },
 {
  "from": "OD043",
  "to": "OD026",
  "kind": "buildsOn",
  "relation": "prior scale-normalization training scheme with the same motivation",
  "quote": "SNIP [38] proposes a scale normalization method to train objects that fall into the desired scale range for each resolution during multi-scale training."
 },
 {
  "from": "OD043",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "baseline detector framework",
  "quote": "Faster R-CNN [35] first proposes a unified end-to-end framework for object detection."
 },
 {
  "from": "OD044",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "canonical sliding-window anchor framework the paper modifies",
  "quote": "Faster RCNN [27] proposes the Region Proposal Network (RPN) to generates object proposals."
 },
 {
  "from": "OD044",
  "to": "OD035",
  "kind": "buildsOn",
  "relation": "prior work on learnable anchor generation",
  "quote": "MetaAnchor [32] introduces meta-learning to anchor generation."
 },
 {
  "from": "OD044",
  "to": "OD003",
  "kind": "buildsOn",
  "relation": "contrast: simpler pipelines that lack anchor-based refinement",
  "quote": "Anchor-free methods [14, 15, 25] usually have simple pipelines and produce final detection results within a single stage."
 },
 {
  "from": "OD045",
  "to": "OD023",
  "kind": "buildsOn",
  "relation": "detection-head design ThunderNet compresses further",
  "quote": "LightHead R-CNN [14] adopts a lightweight detection head and achieves real-time detection on GPU."
 },
 {
  "from": "OD045",
  "to": "OD016",
  "kind": "buildsOn",
  "relation": "prior lightweight one-stage detectors used as baselines",
  "quote": "lightweight one-stage detectors, such as MobileNet-SSD [11], MobileNetV2-SSDLite [28], Pelee [31] and Tiny-DSOD [13], achieve inference on mobile devices at low frame rates."
 },
 {
  "from": "OD046",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "mainstream anchor-based detectors this work replaces",
  "quote": "All current mainstream detectors such as Faster R-CNN [24], SSD [18] and YOLOv2, v3 [23] rely on a set of pre-defined anchor boxes and it has long been believed that the use of anchor boxes is the key to detectors’ success."
 },
 {
  "from": "OD046",
  "to": "OD003",
  "kind": "buildsOn",
  "relation": "prior FCN-based detector limited to special domains and image pyramids",
  "quote": "these methods are mainly used in special domain objection detection such as scene text detection [33, 10] or face detection [32, 12]"
 },
 {
  "from": "OD046",
  "to": "OD104",
  "kind": "buildsOn",
  "relation": "prior anchor-free point-prediction detector with low recall",
  "quote": "The most popular anchor-free detector might be YOLOv1 [21]."
 },
 {
  "from": "OD046",
  "to": "OD036",
  "kind": "buildsOn",
  "relation": "prior anchor-free one-stage detector with costly grouping post-processing",
  "quote": "An extra distance metric is learned for the purpose of grouping."
 },
 {
  "from": "OD047",
  "to": "OD034",
  "kind": "buildsOn",
  "relation": "baseline detector whose bbox head is re-modeled",
  "quote": "YOLOv3 consists of convolution layers, as shown in Figure 1a, and is constructed of a deep network for an improved accuracy."
 },
 {
  "from": "OD047",
  "to": "OD071",
  "kind": "buildsOn",
  "relation": "prior generation with anchors and multi-scale training",
  "quote": "YOLOv2 improves the detection accuracy compared to YOLO by using batch normalization for the convolution layer, and applying an anchor box, multi-scale training, and fine-grained features."
 },
 {
  "from": "OD047",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "accurate but slow alternative family",
  "quote": "conduct a first stage of region proposal generation, followed by a second stage of object classification and bbox regression."
 },
 {
  "from": "OD048",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "prior two-stage detector using a convolution head on a single feature level",
  "quote": "Faster RCNN [35] uses a convolution head (conv5) on a single level feature map (conv4)"
 },
 {
  "from": "OD048",
  "to": "OD014",
  "kind": "buildsOn",
  "relation": "prior head-extension and RoIAlign machinery the method reuses",
  "quote": "Mask RCNN [13] introduces an extra head for instance segmentation."
 },
 {
  "from": "OD049",
  "to": "OD036",
  "kind": "buildsOn",
  "relation": "prior keypoint-based detector that detects box corners and needs grouping",
  "quote": "CornerNet [30] detects two bounding box corners as keypoints"
 },
 {
  "from": "OD049",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "anchor/proposal based prior stage the paper contrasts with",
  "quote": "Faster RCNN [46] generates region proposal within the detection network."
 },
 {
  "from": "OD049",
  "to": "OD036",
  "kind": "buildsOn",
  "relation": "identified efficiency gap in related keypoint methods",
  "quote": "However, they require a combinatorial grouping stage after keypoint detection, which significantly slows down each algorithm."
 },
 {
  "from": "OD050",
  "to": "OD036",
  "kind": "buildsOn",
  "relation": "direct baseline that predicts a pair of corner keypoints",
  "quote": "This paper uses CornerNet [20] as the baseline."
 },
 {
  "from": "OD050",
  "to": "OD029",
  "kind": "buildsOn",
  "relation": "prior two-stage work on quality mismatch and IoU thresholds",
  "quote": "Cascade R-CNN [4] addresses the problem of overfitting at training and quality mismatch at inference by training a sequence of detectors with increasing IoU thresholds."
 },
 {
  "from": "OD051",
  "to": "OD036",
  "kind": "buildsOn",
  "relation": "the accurate but slow baseline being optimized",
  "quote": "CornerNet [27], the state-of-the-art among them, detects and groups the top-left and bottom-right corners of bounding boxes;"
 },
 {
  "from": "OD051",
  "to": "OD016",
  "kind": "buildsOn",
  "relation": "source of depth-wise separable convolutions for the compact backbone",
  "quote": "MobileNets [16] are a class of lightweight networks that use depth-wise separable convolutions [6], and proposes strategies to achieve a good trade-off between accuracy and latency."
 },
 {
  "from": "OD052",
  "to": "OD012",
  "kind": "buildsOn",
  "relation": "prior SSD refinement using a complex feature pyramid at higher computational cost",
  "quote": "DSSD [5] relies on a complex feature pyramid to encourage the information flow among different layers."
 },
 {
  "from": "OD052",
  "to": "OD030",
  "kind": "buildsOn",
  "relation": "prior fusion-module refinement with only marginal gains over SSD",
  "quote": "Another recent approach, FSSD [16], builds additional fusion modules for multi-scale feature aggregation, but only achieves marginal improvements upon SSD."
 },
 {
  "from": "OD052",
  "to": "OD042",
  "kind": "buildsOn",
  "relation": "source of the self-attention mechanism adapted to feature maps",
  "quote": "Transformer [29] draws global dependencies between input and output based solely on attention mechanisms."
 },
 {
  "from": "OD052",
  "to": "OD028",
  "kind": "buildsOn",
  "relation": "proposal-level attention prior work limited to two-stage detectors",
  "quote": "RelationNet correlates the geometry features and appearance information between proposals to generate and forward the attentive features, and it is designed specifically for the two-stage object detectors."
 },
 {
  "from": "OD054",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "canonical two-stage anchor-based detector",
  "quote": "The emergence of Faster R-CNN [47] establishes the dominant position of two-stage anchorbased detectors."
 },
 {
  "from": "OD054",
  "to": "OD046",
  "kind": "buildsOn",
  "relation": "center-based anchor-free detector used as the controlled counterpart of RetinaNet",
  "quote": "FCOS [56] regards all the locations inside the object bounding box as positives with four distances and a novel centerness score to detect objects."
 },
 {
  "from": "OD055",
  "to": "OD036",
  "kind": "buildsOn",
  "relation": "prior method that represents a box as a top-left/bottom-right corner pair grouped by associative embedding; the framework the paper extends",
  "quote": "the CornerNet [17] proposes a novel method to represent a bounding box as a pair of corners, i.e, top-left corner and bottom-right corner."
 },
 {
  "from": "OD055",
  "to": "OD050",
  "kind": "buildsOn",
  "relation": "adds a center detection branch to CornerNet and validates corners by center prediction, but cannot handle dense cases",
  "quote": "CenterNet [7] adds a center detection branch into CornerNet and largely improves the performance by center point validation."
 },
 {
  "from": "OD055",
  "to": "OD046",
  "kind": "buildsOn",
  "relation": "anchor-free center/point-based baseline treating all points inside a box as positives",
  "quote": "FCOS [31] treats all the points inside the bounding box of the object as positive samples."
 },
 {
  "from": "OD055",
  "to": "OD014",
  "kind": "buildsOn",
  "relation": "two-stage instance segmentation prior; its RoIAlign layer is reused in the proposed mask head",
  "quote": "Mask R-CNN [11] replaces the RoIPool layer with the RoIAlign layer using bilinear interpolation."
 },
 {
  "from": "OD056",
  "to": "OD034",
  "kind": "buildsOn",
  "relation": "direct predecessor whose SPP-equipped head and Darknet-53 backbone the architecture builds on",
  "quote": "YOLOv3-608 upgrades AP50 by 2.7% on the MS COCO object detection task at the cost of 0.5% extra computation."
 },
 {
  "from": "OD057",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "strong optimized baseline for COCO comparison",
  "quote": "Faster RCNN has undergone many design iterations and its performance was greatly improved since the original publication."
 },
 {
  "from": "OD058",
  "to": "OD020",
  "kind": "buildsOn",
  "relation": "prior loss for extreme foreground/background imbalance that only supports discrete {1,0} labels",
  "quote": "where an extreme imbalance between foreground and background classes often exists during training."
 },
 {
  "from": "OD060",
  "to": "OD044",
  "kind": "buildsOn",
  "relation": "enhances the single-point feature with deformable convolution but extracts from the whole object",
  "quote": "Guided Anchor [24] is proposed to enhance the single point feature representation by utilizing the deformable convolution."
 },
 {
  "from": "OD061",
  "to": "OD034",
  "kind": "buildsOn",
  "relation": "base detector that PP-YOLO extends",
  "quote": "Considering that YOLOv3 has been widely used in practice, we develop a new object detector based on YOLOv3."
 },
 {
  "from": "OD061",
  "to": "OD056",
  "kind": "buildsOn",
  "relation": "contemporaneous competitor exploring bag of freebies/specials on YOLOv3",
  "quote": "YOLOv4 discusses a large number of tricks including many “bag of freebies” which not increase the infer time, and several “bag of specials” that increase the inference cost by a small amount but can significantly improve the accuracy of object detection."
 },
 {
  "from": "OD062",
  "to": "OD058",
  "kind": "buildsOn",
  "relation": "concurrent work on joint localization-quality and classification prediction",
  "quote": "The most similar work to ours is a concurrent work, Generalized Focal Loss (GFL) [32]."
 },
 {
  "from": "OD062",
  "to": "OD020",
  "kind": "buildsOn",
  "relation": "loss the Varifocal Loss is designed from",
  "quote": "The Varifocal Loss, inspired by the focal loss [8], is a dynamically scaled binary cross entropy loss."
 },
 {
  "from": "OD063",
  "to": "OD065",
  "kind": "buildsOn",
  "relation": "base end-to-end detector whose attention modules are replaced",
  "quote": "DETR has been recently proposed to eliminate the need for many hand-designed components in object detection while demonstrating good performance."
 },
 {
  "from": "OD063",
  "to": "OD013",
  "kind": "buildsOn",
  "relation": "inspiration for sparse spatial sampling in the proposed attention",
  "quote": "In the image domain, deformable convolution (Dai et al., 2017) is of a powerful and efficient mechanism to attend to sparse spatial locations."
 },
 {
  "from": "OD063",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "convergence and speed reference baseline",
  "quote": "which is around 10 to 20 times slower than Faster R-CNN (Ren et al., 2015)"
 },
 {
  "from": "OD064",
  "to": "OD056",
  "kind": "buildsOn",
  "relation": "base detector that is re-designed and scaled",
  "quote": "In this paper, we developed our model scaling methods based on YOLOv4 [1]."
 },
 {
  "from": "OD064",
  "to": "OD053",
  "kind": "buildsOn",
  "relation": "prior NAS-based compound scaling competitor",
  "quote": "The main design concept of EfficientDet [35] is to disassemble the modules with different functions of object detector, and then perform scaling on the image size, width, #BiFPN layers, and #box/class layer."
 },
 {
  "from": "OD065",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "base architecture whose transformer is pre-trained",
  "quote": "DETR [1] is a recent object detection framework that is conceptually simpler without hand-crafted process by direct set prediction [25], which assigns the positive and negative samples automatically."
 },
 {
  "from": "OD066",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "dense-to-sparse baseline whose RPN is replaced",
  "quote": "Two-stage detector is another mainstream pipeline and has dominated modern object detection for years [2, 6, 13, 14, 37]."
 },
 {
  "from": "OD066",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior end-to-end set-prediction method, but not purely sparse",
  "quote": "Recently, DETR [3] is proposed to directly output the predictions without any hand-crafted components, achieving promising performance."
 },
 {
  "from": "OD066",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "concurrent work restricting each query to local sampling points",
  "quote": "Concurrently, Deformable-DETR [63] is introduced to restrict each object query to attend to a small set of key sampling points around the reference points, instead of all points in feature map."
 },
 {
  "from": "OD067",
  "to": "OD026",
  "kind": "buildsOn",
  "relation": "prior scale-normalisation treatment of train/infer scale mismatch",
  "quote": "SNIP [18] probes into the scale variance in object detection. To avoid scale mismatch between training and inference, SNIP proposes a scale normalisation method to train objects that fall into the desired scale range."
 },
 {
  "from": "OD067",
  "to": "OD043",
  "kind": "buildsOn",
  "relation": "parallel-branch scale-specific prior art, but two-stage and dilated-convolution based",
  "quote": "TridentNet [19] generates scale-specific features through multiple parallel branches using dilated convolution to endow their network the same representational power for all objects of different scales."
 },
 {
  "from": "OD068",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior single-C5-feature detector, but with transformers and slow convergence",
  "quote": "Recently, DETR [4] introduces the transformer [39] to detection and shows that it could achieve state-of-the-art results only use a single C5 feature."
 },
 {
  "from": "OD069",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "fixed IoU-threshold label assignment",
  "quote": "Anchor-based detectors usually adopt IoU at a certain threshold as the assigning criterion. For example, RPN in Faster R-CNN [33] uses 0.7 and 0.3 as the positive and negative thresholds, respectively."
 },
 {
  "from": "OD069",
  "to": "OD046",
  "kind": "buildsOn",
  "relation": "anchor-free center-region assignment treated as positives",
  "quote": "Anchor-free detectors like FCOS [38] treat the anchors within the center/bbox region of any gt object as the corresponding positives."
 },
 {
  "from": "OD069",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior global-view assignment, but restricted to one-to-one matching",
  "quote": "DeTR [3] is the first work that attempts to consider label assignment from global view. It replaces the detection head with transformer layers [39] and considers one-to-one assignment using the Hungarian algorithm that matches only one query for each gt with global minimum loss."
 },
 {
  "from": "OD070",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior end-to-end set-prediction detector with bipartite matching, but very slow to converge",
  "quote": "Recently, DETR [2] proposed to build an end-to-end framework based on an encoder-decoder transformer [34] architecture and bipartite matching, which directly predicts a set of bounding boxes without post-processing."
 },
 {
  "from": "OD070",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior work that speeds convergence with local attention and multi-scale feature maps",
  "quote": "Deformable DETR [43] solves the two problems in the following two aspects: (i). replacing global scoped attention with local spatial attention, which accelerates the convergence of training."
 },
 {
  "from": "OD070",
  "to": "OD066",
  "kind": "buildsOn",
  "relation": "sparse-proposal detector with learnable proposals that converges in 36 epochs",
  "quote": "The RoI layer limits the proposal feature to only interact with a few local features and makes Sparse RCNN have a fast converging speed (36 epochs)."
 },
 {
  "from": "OD071",
  "to": "OD061",
  "kind": "buildsOn",
  "relation": "the baseline this paper incrementally refines",
  "quote": "Our baseline model is PP-YOLO which is an enhanced version of YOLOv3. Specifically, it first replaces the backbone to ResNet50-vd[9]."
 },
 {
  "from": "OD071",
  "to": "OD034",
  "kind": "buildsOn",
  "relation": "still the most widely used detector in industry under resource constraints",
  "quote": "YOLOv3 [20] is still one of the most widely used detector in industry. Because, in various practical applications, not only the computation resources are limited, but also the software support is insufficient."
 },
 {
  "from": "OD071",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "more accurate two-stage alternatives that are too slow for practical use",
  "quote": "Without necessary technique support, two stage object detector(e.g. Faster RCNN [21], Cascade RCNN [2]) may excruciatingly slow. Meanwhile, a significant gap exists between the accuracy of YOLOv3 and two stage object detectors."
 },
 {
  "from": "OD072",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "introduced query based direct set prediction for object detection",
  "quote": "Recently, DETR [7] is proposed to reformulate object detection as a query based direct set prediction problem, whose input is mere 100 learned object queries."
 },
 {
  "from": "OD072",
  "to": "OD066",
  "kind": "buildsOn",
  "relation": "the query based detector chosen as QueryInst's default six-stage instantiation",
  "quote": "QueryInst can be built on any multi-stage query based object detector [7, 62, 42]. We choose Sparse R-CNN [42] as our default instantiation, which has six query stages."
 },
 {
  "from": "OD072",
  "to": "OD014",
  "kind": "buildsOn",
  "relation": "the most successful multi-stage instance segmentation paradigm this work departs from",
  "quote": "mentation methods are based on high performing object detectors and follow a multi-stage paradigm. Among which, the Mask R-CNN family [21, 24, 30, 5, 9, 42] is the most"
 },
 {
  "from": "OD073",
  "to": "OD042",
  "kind": "buildsOn",
  "relation": "explicit deep learning via query/key/value self-attention",
  "quote": "Transformer [14, 5, 20] is one way, and it mainly uses query, key, or value to obtain self-attention."
 },
 {
  "from": "OD073",
  "to": "OD010",
  "kind": "buildsOn",
  "relation": "target of the proposed feature-alignment application",
  "quote": "the feature alignment of large objects and small objects in feature pyramid networks (FPN) [8]"
 },
 {
  "from": "OD073",
  "to": "OD056",
  "kind": "buildsOn",
  "relation": "baseline architecture for all experiments",
  "quote": "We choose YOLOv4CSP [15] as the baseline model in the experiments"
 },
 {
  "from": "OD074",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "default detection framework used to illustrate the method",
  "quote": "we use Faster R-CNN [22] as our default detection framework to illustrate our method."
 },
 {
  "from": "OD075",
  "to": "OD116",
  "kind": "buildsOn",
  "relation": "best prior YOLO trade-off and the scaling/architecture source for YOLOX-S/M/L/X",
  "quote": "Currently, YOLOv5 [7] holds the best trade-off performance with 48.2% AP on COCO at 13.7 ms."
 },
 {
  "from": "OD076",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "base architecture being accelerated",
  "quote": "It effectively eliminates the need for many hand-crafted components, including non-maximum suppression and anchor generation."
 },
 {
  "from": "OD076",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "addresses DETR with sparse deformable attention and a high-resolution encoder instead of a new cross-attention",
  "quote": "handles this issue by replacing the global dense attention (self-attention and cross-attention) with deformable attention that attends to a small set of key sampling points"
 },
 {
  "from": "OD077",
  "to": "OD012",
  "kind": "buildsOn",
  "relation": "adds extra deconvolution layers at the end of SSD to inject contextual information",
  "quote": "DSSD [17] adds extra deconvolution layers at the end of SSD and the contextual information is injected by integrating every prediction layer and its deconvolution layer."
 },
 {
  "from": "OD077",
  "to": "OD030",
  "kind": "buildsOn",
  "relation": "recombines multi-layer VGG-16 features into a feature pyramid",
  "quote": "FSSD [18] combines the multi-layer features from VGG-16 [6] and then generates a feature pyramid like the original SSD detection part."
 },
 {
  "from": "OD077",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "two-stage reference that is accurate but slower",
  "quote": "it is hard for two-stage approaches to detect images fast."
 },
 {
  "from": "OD078",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "base paradigm whose learned object queries are uninterpretable",
  "quote": "It uses a set of learned object queries to reason about the relations of the objects and the global image context to output the final predictions set."
 },
 {
  "from": "OD078",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "uses deformable sampling and multi-level features to fix slow convergence",
  "quote": "Zhu et al. (Zhu et al. 2020) propose the Deformable DETR with sampling deformable points of value to the query and using multiple level features to solve the slowly converge speed of the transformer detector."
 },
 {
  "from": "OD078",
  "to": "OD076",
  "kind": "buildsOn",
  "relation": "concurrent; encodes reference point as position embedding but object queries remain learned embeddings",
  "quote": "the object queries are still the learned embeddings."
 },
 {
  "from": "OD078",
  "to": "OD049",
  "kind": "buildsOn",
  "relation": "anchor points in CNN detectors that inspire the query design",
  "quote": "the anchors are highly related to the position and contain interpretable physical meanings."
 },
 {
  "from": "OD079",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "well-established two-stage baseline with FPN-optimized architecture",
  "quote": "Faster R-CNN is a well established method, with optimized architectures such as feature-pyramid networks (FPN) (Lin et al., 2017a)."
 },
 {
  "from": "OD079",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior transformer detector that removes NMS but still needs learned object queries and detection heads",
  "quote": "While DETR (Carion et al., 2020) avoids sophisticated bounding box proposals and non-maximum suppression, it still requires a set of learned \"object queries\", specially for object binding."
 },
 {
  "from": "OD080",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "end-to-end baseline that removes NMS via a set-based Hungarian objective",
  "quote": "Recently, Carion et al. (2020) has introduced a fully end-to-end detector DETR by eliminating the need for NMS post-processing through a set-based objective."
 },
 {
  "from": "OD080",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "closest baseline; sparsifies keys with deformable attention but keeps dense queries",
  "quote": "It can be viewed as a key sparsification method but with dense queries, while our approach further reduces the query set pursuing even more sparsity."
 },
 {
  "from": "OD081",
  "to": "OD112",
  "kind": "buildsOn",
  "relation": "prior phrase-grounding model whose fine-grained contrastive loss inspired the grounding loss",
  "quote": "Our grounding formulation is inspired by MDETR [23], and our grounding loss shares the same spirit of MDETR's fine-grained contrastive loss."
 },
 {
  "from": "OD082",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "base end-to-end anchor-free detector using learnable vectors as queries",
  "quote": "DETR (Carion et al., 2020) is a fully anchor-free detector using a set of learnable vectors as queries."
 },
 {
  "from": "OD082",
  "to": "OD076",
  "kind": "buildsOn",
  "relation": "closest prior stage; generates positional queries from reference coordinates but cannot adapt to object scales",
  "quote": "Conditional DETR (Meng et al., 2021) decouples the attention formulation and generates positional queries based on reference coordinates."
 },
 {
  "from": "OD082",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "treats 2D reference points as queries with deformable sampling, no explicit anchor formulation",
  "quote": "Deformable DETR directly treats 2D reference points as queries and performs deformable cross-attention operation at each reference points"
 },
 {
  "from": "OD082",
  "to": "OD078",
  "kind": "buildsOn",
  "relation": "concurrent work learning 2D anchor points, but discarding width and height information",
  "quote": "A concurrent work Anchor DETR (Wang et al., 2021) also suggests learning anchor points directly, while it ignores the anchor width and height information as in other prior works."
 },
 {
  "from": "OD083",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "representative two-stage region-proposal baseline for general detection",
  "quote": "region proposal based methods, such as Fast R-CNN [11], Faster R-CNN [1], Cascade R-CNN [3], involve an initial region proposal stage."
 },
 {
  "from": "OD083",
  "to": "OD046",
  "kind": "buildsOn",
  "relation": "anchor-free one-stage detector used as an experimental baseline",
  "quote": "FCOS [13] is the first object detector eliminating the need for predefined set of anchor boxes and entailing computational need."
 },
 {
  "from": "OD084",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior transformer detector that removes anchors and NMS but converges very slowly",
  "quote": "Carion et al. [1] proposed an end-to-end object detector based on Transformers [20] named DETR (DEtection TRansformer) without using anchors."
 },
 {
  "from": "OD084",
  "to": "OD082",
  "kind": "buildsOn",
  "relation": "baseline architecture whose 4D anchor-box queries DN-DETR is built on",
  "quote": "DAB-DETR [14] uses 4-D box coordinates as queries and updates boxes layer by layer in a cascade manner."
 },
 {
  "from": "OD084",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior query designs that bind each query to a spatial position",
  "quote": "Deformable DETR [25] and Anchor DETR [21] directly treat 2D reference points as queries to perform cross-attention."
 },
 {
  "from": "OD084",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "classical two-stage anchor-based baseline used for convergence comparison",
  "quote": "Ren et al. [18] proposed an end-to-end method that utilizes a Region Proposal Network to predict anchor boxes."
 },
 {
  "from": "OD085",
  "to": "OD084",
  "kind": "buildsOn",
  "relation": "direct base: denoising training that stabilizes bipartite matching",
  "quote": "DN-DETR [17] introduces a denoising training method to speed up DETR training. It feeds noise-added ground-truth labels and boxes into the decoder and trains the model to reconstruct the original ones."
 },
 {
  "from": "OD085",
  "to": "OD082",
  "kind": "buildsOn",
  "relation": "base that formulates queries as dynamic 4D anchor boxes",
  "quote": "DAB-DETR [21] further extends 2D anchor points to 4D anchor box coordinates to represent queries and dynamically update boxes in each decoder layer."
 },
 {
  "from": "OD085",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "source of deformable attention, query selection and iterative box refinement",
  "quote": "Deformable DETR [41] predicts 2D anchor points and designs a deformable attention module that only attends to certain sampling points around a reference point."
 },
 {
  "from": "OD085",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "prior art that relies on hand-designed components and cannot be end-to-end optimized",
  "quote": "Moreover, they need hand-designed components like NMS to remove duplicate boxes, and hence cannot perform end-to-end optimization."
 },
 {
  "from": "OD086",
  "to": "OD075",
  "kind": "buildsOn",
  "relation": "base real-time anchor-free detector of the proposed model",
  "quote": "Our work is based on the recent real-time detector YOLOX [13] which achieves strong performance among real-time detectors."
 },
 {
  "from": "OD087",
  "to": "OD071",
  "kind": "buildsOn",
  "relation": "one-stage baseline that PP-YOLOE evolves from",
  "quote": "PP-YOLOv2 is a high-performance one-stage detector with 49.5 mAP at the speed of 68.9 FPS on Tesla V100."
 },
 {
  "from": "OD087",
  "to": "OD075",
  "kind": "buildsOn",
  "relation": "anchor-free competitor with SimOTA dynamic label assignment",
  "quote": "YOLOX uses SimOTA as the label assignment strategy to improve performance."
 },
 {
  "from": "OD087",
  "to": "OD046",
  "kind": "buildsOn",
  "relation": "anchor-free anchor-point tiling with upper/lower bounds for assignment",
  "quote": "Following FCOS[26], which tiles one anchor point on each pixel, we set upper and lower bounds for three detection heads to assign ground truths to corresponding feature map."
 },
 {
  "from": "OD090",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "base end-to-end detector relying on bipartite one-to-one matching",
  "quote": "DETR [4] relies on one-to-one assignment, where each ground-truth object is assigned to a single prediction through building a bipartite matching between the predictions and the ground-truth objects."
 },
 {
  "from": "OD090",
  "to": "OD084",
  "kind": "buildsOn",
  "relation": "prior work that stabilizes one-to-one assignment with noisy queries",
  "quote": "DN-DETR [29] finds the assignment process is unstable and attributes the slow convergence issue to the instabilities."
 },
 {
  "from": "OD090",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "cross-attention modification line that samples informative positions",
  "quote": "Deformable attention [70] selects the highly informative positions dynamically according to the previous decoder embedding."
 },
 {
  "from": "OD090",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "non-end-to-end detectors where one-to-many assignment succeeds",
  "quote": "One ground-truth object is assigned to multiple anchors or multiple pixels."
 },
 {
  "from": "OD091",
  "to": "OD075",
  "kind": "buildsOn",
  "relation": "lineage the work extends for industrial use",
  "quote": "YOLO series have been the most popular detection frameworks in industrial applications, for its excellent balance between speed and accuracy."
 },
 {
  "from": "OD092",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior end-to-end detector that replaced hand-designed candidates with learnable queries",
  "quote": "Recently, DETR [10] proposes learnable object queries to eliminate the hand-designed components and set up an end-to-end detection pipeline"
 },
 {
  "from": "OD092",
  "to": "OD066",
  "kind": "buildsOn",
  "relation": "source of the 6-stage detection decoder, but with fixed learned proposals instead of random boxes",
  "quote": "DiffusionDet begins from random boxes while Sparse R-CNN uses a fixed set of learned boxes in inference"
 },
 {
  "from": "OD093",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "base method whose one-to-one matching causes the sparse supervision",
  "quote": "DEtection TRansformer (DETR) [1] is proposed to view the object detection as a set prediction problem and introduce the one-to-one set matching scheme"
 },
 {
  "from": "OD093",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "traditional detectors whose dense supervision the encoder lacks",
  "quote": "One-to-many label assignment is the core scheme of them, where each groundtruth box is assigned to multiple coordinates in the detector's output as the supervised target cooperated with proposals [11, 27], anchors [21] or window centers [32]."
 },
 {
  "from": "OD093",
  "to": "OD084",
  "kind": "buildsOn",
  "relation": "prior fix attributing slow convergence to unstable one-to-one matching",
  "quote": "DNDETR [18] demonstrates the slow convergence results from the instability of one-to-one set matching, thus introducing denoising training to eliminate this issue."
 },
 {
  "from": "OD093",
  "to": "OD065",
  "kind": "buildsOn",
  "relation": "concurrent works adding more positive queries via group or hybrid matching",
  "quote": "Group-DETR [5] constructs group-wise one-to-many label assignment to exploit multiple positive object queries, which is similar to the hybrid matching scheme in H-DETR [16]."
 },
 {
  "from": "OD094",
  "to": "OD061",
  "kind": "buildsOn",
  "relation": "industrial real-time baselines the report aims to surpass",
  "quote": "YOLOv5/6/7 [18, 32, 34], YOLOX [9] and PP-YOLOE [38] have achieved significant AP-Latency trade-offs on COCO, making YOLO series object detection methods widely used in the industry."
 },
 {
  "from": "OD095",
  "to": "OD085",
  "kind": "buildsOn",
  "relation": "base closed-set transformer detector that Grounding DINO extends",
  "quote": "Grounding DINO is built upon the DETR-like model DINO [57], which is an end-to-end Transformer-based detector."
 },
 {
  "from": "OD096",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "origin of the end-to-end one-to-one set prediction pipeline RT-DETR builds on",
  "quote": "Particularly, DETR eliminates the hand-crafted anchor and NMS components."
 },
 {
  "from": "OD096",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior work adding multi-scale features and query selection, whose encoder cost RT-DETR redesigns",
  "quote": "Deformable-DETR [45] accelerates training convergence with multi-scale features by enhancing the efficiency of the attention mechanism."
 },
 {
  "from": "OD096",
  "to": "OD053",
  "kind": "buildsOn",
  "relation": "prior attempts at reducing DETR computational cost",
  "quote": "Efficient DETR [42] and Sparse DETR [33] reduce the computational cost by reducing the number of encoder and decoder layers or the number of updated queries."
 },
 {
  "from": "OD096",
  "to": "OD075",
  "kind": "buildsOn",
  "relation": "real-time baselines RT-DETR aims to outperform in both speed and accuracy",
  "quote": "YOLOv1 [31] is the first CNN-based one-stage object detector to achieve true real-time object detection."
 },
 {
  "from": "OD096",
  "to": "OD085",
  "kind": "buildsOn",
  "relation": "source of mixed query selection and of RT-DETR's decoder training recipe",
  "quote": "DINO [44] suggests the mixed query selection to help better initialize queries."
 },
 {
  "from": "OD097",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior DETR variant with multi-scale deformable attention",
  "quote": "Deformable-DETR (Zhu et al., 2020) proposes a novel multi-scale deformable self/cross-attention to focus on a sparse set of important sampling points around a reference point."
 },
 {
  "from": "OD097",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "strongest downstream detector used as the test bed",
  "quote": "and Group-DETR (Chen et al., 2022) propose to train with more queries in the transformer decoder with an additional one-to-many matching scheme"
 },
 {
  "from": "OD098",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "transformer-based real-time alternative that removes NMS",
  "quote": "RT-DETR [80] constructs the first transformer-based model to avoid the negative impact of NMS at inference time."
 },
 {
  "from": "OD099",
  "to": "OD091",
  "kind": "buildsOn",
  "relation": "contemporary reparameterized YOLO baseline",
  "quote": "YOLOv6 [32, 31] brings the reparameterization method to YOLO-series models for the first time, proposing EfficientRep Backbone and Rep-PAN Neck."
 },
 {
  "from": "OD100",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "training-efficient baseline that replaces cross-attention with deformable attention",
  "quote": "Deformable DETR [48] uses deformable attention, an extension of deformable convolution [7], that selects the highly informative regions, to replace the original crossattention architecture."
 },
 {
  "from": "OD100",
  "to": "OD065",
  "kind": "buildsOn",
  "relation": "one-to-many supervision variants that rely on additional parallel decoders",
  "quote": "Group DETR [4, 5] instead learns the object queries of the additional decoders."
 },
 {
  "from": "OD100",
  "to": "OD022",
  "kind": "buildsOn",
  "relation": "closest prior work doing one-to-many supervision on a single decoder, but drops one-to-one supervision and reintroduces NMS",
  "quote": "The mixture of one-to-one and one-to-many supervisions on the single decoder without using NMS is underexplored."
 },
 {
  "from": "OD101",
  "to": "OD095",
  "kind": "buildsOn",
  "relation": "integrates grounded pre-training into detection transformers with cross-modality fusion",
  "quote": "Grounding DINO [30] incorporates the grounded pre-training [24] into detection transformers [60] with cross-modality fusions."
 },
 {
  "from": "OD101",
  "to": "OD075",
  "kind": "buildsOn",
  "relation": "efficient one-stage architecture that YOLO-World extends to open vocabulary",
  "quote": "Several works [10, 23, 33, 52, 55] propose various architectures or designs for YOLO, including path aggregation networks [29], cross-stage partial networks [51], and re-parameterization [6], which further improve both speed and accuracy."
 },
 {
  "from": "OD102",
  "to": "OD089",
  "kind": "buildsOn",
  "relation": "base detector that YOLOv9 builds on",
  "quote": "This paper chooses YOLOv7 [63], which has been proven effective in a variety of computer vision tasks and various scenarios, as a base to develop the proposed method."
 },
 {
  "from": "OD103",
  "to": "OD095",
  "kind": "buildsOn",
  "relation": "direct predecessor whose architecture is scaled and extended",
  "quote": "Grounding DINO [18] represents a significant advancement in this area."
 },
 {
  "from": "OD103",
  "to": "OD085",
  "kind": "buildsOn",
  "relation": "Transformer-based detection architecture underlying Grounding DINO",
  "quote": "Building on the Transformerbased DINO [33] architecture, it incorporates linguistic information to enable open-set object detection in various scenarios."
 },
 {
  "from": "OD104",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "prior end-to-end transformer detector with one-to-one Hungarian matching",
  "quote": "DETR [4] introduces the transformer architecture and adopts Hungarian loss to achieve one-to-one matching prediction, thereby eliminating hand-crafted components and post-processing."
 },
 {
  "from": "OD104",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "prior real-time DETR and main end-to-end baseline",
  "quote": "RT-DETR [78] further designs the efficient hybrid encoder and proposes the uncertainty-minimal query selection to improve both the accuracy and latency."
 },
 {
  "from": "OD104",
  "to": "OD116",
  "kind": "buildsOn",
  "relation": "baseline model for YOLOv10",
  "quote": "YOLOv8 [21] presents C2f building block for effective feature extraction and fusion."
 },
 {
  "from": "OD104",
  "to": "OD099",
  "kind": "buildsOn",
  "relation": "prior YOLO with GD feature-fusion mechanism, used as comparison",
  "quote": "Gold-YOLO [60] provides the advanced GD mechanism to boost the multi-scale feature fusion capability."
 },
 {
  "from": "OD105",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "base end-to-end framework the method extends",
  "quote": "Detection Transformer (DETR) is an end-to-end detection method, with removing the necessity of many hand-crafted components, such as anchor generation [51] and non-maximum suppression (NMS) [24]."
 },
 {
  "from": "OD105",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "concurrent real-time DETR baseline using a CNN encoder",
  "quote": "Concurrent with our work, RT-DETR [45] also applies the DETR framework to construct real-time detectors with a focus on the CNN backbone forming the encoder."
 },
 {
  "from": "OD106",
  "to": "OD105",
  "kind": "buildsOn",
  "relation": "detector the work is built upon",
  "quote": "This work is built upon the recent LW-DETRChen et al. [2024], a light-weight real-time DETR baseline."
 },
 {
  "from": "OD106",
  "to": "OD095",
  "kind": "buildsOn",
  "relation": "prior approaches adding deep fusion modules between image and language encoders",
  "quote": "introduce deep fusion module between the image and language encoders."
 },
 {
  "from": "OD106",
  "to": "OD101",
  "kind": "buildsOn",
  "relation": "state-of-the-art real-time open-vocabulary baseline used for comparison",
  "quote": "the recent state-of-the art real-time open-vocabulary method."
 },
 {
  "from": "OD107",
  "to": "OD108",
  "kind": "buildsOn",
  "relation": "baseline that RT-DETRv2 improves",
  "quote": "The advent of RT-DETR (Zhao et al. [2024]) opens up a new technological avenue for real-time object detection, breaking the dependency on the YOLO in this field."
 },
 {
  "from": "OD107",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "original end-to-end transformer detector the family builds on",
  "quote": "RT-DETR proposes an efficient hybrid encoder to replace the vanilla Transformer encoder in DETR (Carion et al. [2020]), which significantly improves the inference speed by decoupling the intra-scale interaction and cross-scale fusion of multi-scale features."
 },
 {
  "from": "OD107",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "source of the deformable attention module used by the decoder",
  "quote": "Current DETRs utilize the deformable attention module (Zhu et al. [2020]) to alleviate the high computational overhead caused by the long sequence of inputs composed of multi-scale features."
 },
 {
  "from": "OD108",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "framework that RT-DETRv3 keeps and extends",
  "quote": "RT-DETR [32] is the first real-time end-to-end transformer-based object detection algorithm."
 },
 {
  "from": "OD108",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "immediate predecessor optimizing training strategy",
  "quote": "RT-DETRv2 [19] further enhances the flexibility and practicality of RT-DETR [32] by optimizing the training strategy to improve performance without sacrificing speed, although requires longer training time."
 },
 {
  "from": "OD108",
  "to": "OD075",
  "kind": "buildsOn",
  "relation": "dominant CNN-based real-time baselines",
  "quote": "The current CNN-based real-time object detectors are mainly the YOLO series."
 },
 {
  "from": "OD109",
  "to": "OD075",
  "kind": "buildsOn",
  "relation": "dominant real-time baselines with strong efficiency and community",
  "quote": "The YOLO series has led the way in real-time object detection, evolving through innovations in architecture, data augmentation, and training techniques"
 },
 {
  "from": "OD109",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "real-time end-to-end DETR variant that D-FINE builds on",
  "quote": "RT-DETR (Zhao et al., 2024) addresses these limitations by developing a real-time variant, offering an end-to-end alternative to YOLO detectors."
 },
 {
  "from": "OD109",
  "to": "OD105",
  "kind": "buildsOn",
  "relation": "evidence that DETR surpasses YOLO ceilings with large-scale pretraining",
  "quote": "Moreover, LW-DETR (Chen et al., 2024) has shown that DETR can achieve higher performance ceilings than YOLO, especially when trained on large-scale datasets like Objects365 (Shao et al., 2019)."
 },
 {
  "from": "OD110",
  "to": "OD116",
  "kind": "buildsOn",
  "relation": "direct architectural foundation extended by YOLOv11",
  "quote": "YOLO11 extends and enhances the foundation laid by YOLOv8, introducing architectural innovations and parameter optimizations to achieve superior detection performance"
 },
 {
  "from": "OD110",
  "to": "OD102",
  "kind": "buildsOn",
  "relation": "immediate 2024 predecessors YOLOv11 builds on",
  "quote": "YOLOv11 represents a significant advancement in object detection technology, building upon the foundations laid by its predecessors, YOLOv9 and YOLOv10, which were introduced earlier in 2024."
 },
 {
  "from": "OD111",
  "to": "OD103",
  "kind": "buildsOn",
  "relation": "direct architectural base and main prior system",
  "quote": "DINO-X employs the same Transformer-based encoder-decoder architecture as Grounding DINO 1.5 [47] to pursue an object-level representation for open-world object understanding."
 },
 {
  "from": "OD112",
  "to": "OD065",
  "kind": "buildsOn",
  "relation": "prior ways to add positive samples inside O2O training, but with extra decoders/heads",
  "quote": "Although these approaches successfully increase the number of positive samples, they also require additional decoders, which increases computational overhead and risks generating redundant high-quality predictions as traditional detectors."
 },
 {
  "from": "OD112",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "real-time DETR baseline and host framework for DEIM",
  "quote": "RT-DETR is the first real-time object detection model within the DETR framework."
 },
 {
  "from": "OD112",
  "to": "OD109",
  "kind": "buildsOn",
  "relation": "the detector that DEIM boosts to its headline numbers",
  "quote": "This approach enables D-FINE to achieve a more favorable trade-off between latency and performance, slightly surpassing recent YOLO models."
 },
 {
  "from": "OD113",
  "to": "OD104",
  "kind": "buildsOn",
  "relation": "immediate prior real-time YOLO with NMS-free training",
  "quote": "YOLOv10 [53] apply NMSfree training with dual assignments for efficiency gains."
 },
 {
  "from": "OD113",
  "to": "OD110",
  "kind": "buildsOn",
  "relation": "the baseline YOLOv12 is built on and scaled with",
  "quote": "YOLOv11 [28] further reduces latency and increases accuracy by adopting the C3K2 module (a specification of GELAN [58]) and lightweight depthwise separable convolution in the detection head."
 },
 {
  "from": "OD113",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "end-to-end DETR-based real-time competitor",
  "quote": "an end-to-end object detection method, namely RT-DETR [66], improved traditional end-to-end detectors [7, 33, 37, 42, 71] to meet realtime requirements by designing an efficient encoder and an uncertainty-minimal query selection mechanism."
 },
 {
  "from": "OD114",
  "to": "OD075",
  "kind": "buildsOn",
  "relation": "efficient closed-set real-time baseline YOLOE starts from",
  "quote": "Traditional approaches like YOLO series [1, 3, 21, 47], have leveraged convolutional neural networks to achieve real-time remarkable performance"
 },
 {
  "from": "OD114",
  "to": "OD101",
  "kind": "buildsOn",
  "relation": "prior open-vocabulary YOLO and the direct comparison baseline",
  "quote": "YOLO-World [5] further shows the potential of pretraining small detectors with open recognition capabilities based on the YOLO architecture"
 },
 {
  "from": "OD114",
  "to": "OD111",
  "kind": "buildsOn",
  "relation": "only prior unified multi-prompt architecture, but resource-intensive",
  "quote": "DINOX [49] features a unified architecture, which, however, incurs resource-intensive training and inference overhead"
 },
 {
  "from": "OD115",
  "to": "OD112",
  "kind": "buildsOn",
  "relation": "the authors' prior method whose Dense O2O training DEIMv2 extends",
  "quote": "In our previous DEIM [7], we proposed Dense O2O, which increases the number of objects per training image to provide stronger supervision, improving convergence and performance"
 },
 {
  "from": "OD115",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "overall architecture template DEIMv2 follows (backbone, hybrid encoder, decoder)",
  "quote": "Our overall architecture follows the design of RT-DETR [14]"
 },
 {
  "from": "OD116",
  "to": "OD001",
  "kind": "buildsOn",
  "relation": "prior two-stage baseline that YOLO's single forward-pass formulation departed from",
  "quote": "where region proposal generation and subsequent object classification are treated as distinct stages"
 },
 {
  "from": "OD116",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "query-based set-prediction precedent for the query-based YOLO27m/l decoders",
  "quote": "Detection Transformers (DETR) demonstrated the potential of query-based set prediction, although early implementations suffered from slow optimization and substantial computational requirements."
 },
 {
  "from": "OD117",
  "to": "OD107",
  "kind": "buildsOn",
  "relation": "base architecture the method is applied to; first real-time DETR",
  "quote": "RT-DETR [38] marked a milestone as the first real-time DETR, introducing the DETR family to the real-time community by outperforming YOLO models in both speed and accuracy."
 },
 {
  "from": "OD117",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "set-prediction paradigm that removed anchor design and NMS",
  "quote": "the DETR series has reshaped the detection paradigm through its unified modeling of object queries and set-based prediction."
 },
 {
  "from": "OD117",
  "to": "OD115",
  "kind": "buildsOn",
  "relation": "frozen semantic teacher used by the Deep Semantic Injector",
  "quote": "DINOv3 [31] demonstrates the scalability and efficacy of large-scale self-supervised learning, achieving rich and robust representations without human annotations."
 },
 {
  "from": "OD118",
  "to": "OD063",
  "kind": "buildsOn",
  "relation": "foundation",
  "quote": "Rather than simply fine-tuning a heavyweight vision-language model (VLM) for new domains, we introduce RF-DETR,\na light-weight specialist detection transformer that discovers accuracy-latency\nPareto curves for any target dataset with weight-sharing neural architecture search\n(NAS)."
 },
 {
  "from": "OD119",
  "to": "OD116",
  "kind": "buildsOn",
  "relation": "lineage baseline",
  "quote": "Abstract\n\naccuracy while reducing cost: MuSGD, a hybrid Muon–\nSGD optimizer adapted from large language model training; Progressive Loss, which shifts supervision toward the\ninference-time head; and STAL, a label assignment strategy that guarantees positive coverage for small objects."
 },
 {
  "from": "OD119",
  "to": "OD113",
  "kind": "buildsOn",
  "relation": "recent variants",
  "quote": "Beyond detection, YOLO26 introduces task-specific head and\nloss designs for instance segmentation, pose estimation,\nand oriented detection, producing consistent gains across\ntasks and scales."
 }
];
