/* GENERATED by scripts/od_build.py — do not edit by hand. */
import type { Solution } from "./types";

export const SOLUTIONS: Solution[] = [
 {
  "id": "one-stage",
  "name": "One Stage",
  "category": "architecture",
  "summary": "The image is split into an S x S grid whose cells predict B boxes with confidences and C conditional class probabilities, decoded at test time into class-specific scores and filtered with non-max suppression.",
  "firstYear": 2015,
  "paperCount": 47,
  "paperIds": [
   "OD002",
   "OD003",
   "OD004",
   "OD007",
   "OD009",
   "OD011",
   "OD012",
   "OD018",
   "OD019",
   "OD020",
   "OD021",
   "OD025",
   "OD030",
   "OD031",
   "OD032",
   "OD034",
   "OD035",
   "OD036",
   "OD038",
   "OD039",
   "OD046",
   "OD047",
   "OD050",
   "OD051",
   "OD052",
   "OD053",
   "OD056",
   "OD058",
   "OD059",
   "OD060",
   "OD061",
   "OD064",
   "OD067",
   "OD068",
   "OD069",
   "OD071",
   "OD077",
   "OD086",
   "OD087",
   "OD089",
   "OD091",
   "OD094",
   "OD101",
   "OD110",
   "OD114",
   "OD116",
   "OD119"
  ],
  "addresses": [
   "speed-latency",
   "deployability",
   "one-stage-accuracy",
   "small-objects",
   "real-time-edge",
   "localization"
  ]
 },
 {
  "id": "feature-fusion",
  "name": "Feature Fusion",
  "category": "architecture",
  "summary": "A small sliding-window network over the shared feature map regresses k anchor-referenced boxes and objectness scores per location, whose proposals then feed the Fast R-CNN detector inside a single unified network.",
  "firstYear": 2015,
  "paperCount": 39,
  "paperIds": [
   "OD001",
   "OD003",
   "OD005",
   "OD008",
   "OD010",
   "OD012",
   "OD017",
   "OD018",
   "OD019",
   "OD022",
   "OD025",
   "OD030",
   "OD032",
   "OD033",
   "OD039",
   "OD045",
   "OD052",
   "OD053",
   "OD056",
   "OD060",
   "OD067",
   "OD071",
   "OD077",
   "OD081",
   "OD086",
   "OD096",
   "OD098",
   "OD099",
   "OD101",
   "OD102",
   "OD103",
   "OD105",
   "OD110",
   "OD111",
   "OD113",
   "OD115",
   "OD117",
   "OD120",
   "OD121"
  ],
  "addresses": [
   "speed-latency",
   "deployability",
   "scale-variance",
   "small-objects",
   "one-stage-accuracy",
   "real-time-edge"
  ]
 },
 {
  "id": "multi-scale",
  "name": "Multi Scale",
  "category": "architecture",
  "summary": "Small 3x3 convolutional predictors applied at several progressively smaller feature maps emit scores and offsets for default boxes, so detections at multiple scales are produced in a single forward pass followed by NMS.",
  "firstYear": 2015,
  "paperCount": 32,
  "paperIds": [
   "OD004",
   "OD005",
   "OD008",
   "OD009",
   "OD010",
   "OD011",
   "OD012",
   "OD017",
   "OD018",
   "OD020",
   "OD023",
   "OD025",
   "OD026",
   "OD027",
   "OD030",
   "OD032",
   "OD033",
   "OD034",
   "OD043",
   "OD045",
   "OD053",
   "OD063",
   "OD064",
   "OD067",
   "OD068",
   "OD095",
   "OD096",
   "OD098",
   "OD099",
   "OD103",
   "OD104",
   "OD107"
  ],
  "addresses": [
   "speed-latency",
   "scale-variance",
   "small-objects",
   "deployability",
   "one-stage-accuracy",
   "real-time-edge"
  ],
  "simulator": "pyramid"
 },
 {
  "id": "transformer-query",
  "name": "Transformer Query",
  "category": "architecture",
  "summary": "Predict a fixed-size set of boxes and classes in one pass with a transformer decoder over learned object queries, supervised by a Hungarian-matching set loss, removing anchors and NMS entirely.",
  "firstYear": 2020,
  "paperCount": 25,
  "paperIds": [
   "OD057",
   "OD063",
   "OD065",
   "OD070",
   "OD072",
   "OD076",
   "OD078",
   "OD082",
   "OD084",
   "OD085",
   "OD090",
   "OD093",
   "OD095",
   "OD096",
   "OD097",
   "OD100",
   "OD103",
   "OD105",
   "OD106",
   "OD107",
   "OD109",
   "OD111",
   "OD115",
   "OD116",
   "OD118"
  ],
  "addresses": [
   "convergence",
   "speed-latency",
   "deployability",
   "label-assignment",
   "open-vocabulary",
   "real-time-edge"
  ],
  "simulator": "transformer-query"
 },
 {
  "id": "anchors",
  "name": "Anchors",
  "category": "architecture",
  "summary": "A small sliding-window network over the shared feature map regresses k anchor-referenced boxes and objectness scores per location, whose proposals then feed the Fast R-CNN detector inside a single unified network.",
  "firstYear": 2015,
  "paperCount": 23,
  "paperIds": [
   "OD001",
   "OD004",
   "OD008",
   "OD010",
   "OD011",
   "OD012",
   "OD019",
   "OD020",
   "OD021",
   "OD027",
   "OD034",
   "OD035",
   "OD044",
   "OD054",
   "OD056",
   "OD059",
   "OD061",
   "OD064",
   "OD068",
   "OD071",
   "OD082",
   "OD084",
   "OD085"
  ],
  "addresses": [
   "speed-latency",
   "deployability",
   "one-stage-accuracy",
   "localization",
   "small-objects",
   "scale-variance"
  ],
  "simulator": "anchors"
 },
 {
  "id": "attention",
  "name": "Attention",
  "category": "architecture",
  "summary": "Extend scaled dot-product attention with a geometric weight over relative box coordinates, apply it in-place to all RoI features for recognition, and reuse it with rank features to classify duplicates instead of runni…",
  "firstYear": 2017,
  "paperCount": 23,
  "paperIds": [
   "OD028",
   "OD039",
   "OD045",
   "OD048",
   "OD051",
   "OD052",
   "OD057",
   "OD065",
   "OD072",
   "OD081",
   "OD082",
   "OD095",
   "OD096",
   "OD098",
   "OD101",
   "OD103",
   "OD104",
   "OD105",
   "OD108",
   "OD110",
   "OD113",
   "OD115",
   "OD117"
  ],
  "addresses": [
   "speed-latency",
   "deployability",
   "real-time-edge",
   "nms",
   "one-stage-accuracy",
   "open-vocabulary"
  ],
  "simulator": "attention"
 },
 {
  "id": "real-time-backbone",
  "name": "Real Time Backbone",
  "category": "architecture",
  "summary": "Design a thin-but-deep VGG-style backbone (mCReLU + Inception + residuals) and concatenate multi-scale features into a lightweight RPN/classifier pipeline.",
  "firstYear": 2016,
  "paperCount": 19,
  "paperIds": [
   "OD008",
   "OD009",
   "OD011",
   "OD016",
   "OD031",
   "OD045",
   "OD051",
   "OD053",
   "OD064",
   "OD091",
   "OD094",
   "OD102",
   "OD103",
   "OD105",
   "OD113",
   "OD114",
   "OD115",
   "OD118",
   "OD119"
  ],
  "addresses": [
   "deployability",
   "real-time-edge",
   "speed-latency",
   "training-instability",
   "open-vocabulary",
   "one-stage-accuracy"
  ]
 },
 {
  "id": "feature-pyramid",
  "name": "Feature Pyramid",
  "category": "architecture",
  "summary": "Small 3x3 convolutional predictors applied at several progressively smaller feature maps emit scores and offsets for default boxes, so detections at multiple scales are produced in a single forward pass followed by NMS.",
  "firstYear": 2015,
  "paperCount": 18,
  "paperIds": [
   "OD004",
   "OD010",
   "OD014",
   "OD017",
   "OD018",
   "OD025",
   "OD030",
   "OD033",
   "OD034",
   "OD039",
   "OD044",
   "OD046",
   "OD048",
   "OD053",
   "OD061",
   "OD064",
   "OD098",
   "OD099"
  ],
  "addresses": [
   "scale-variance",
   "speed-latency",
   "one-stage-accuracy",
   "small-objects",
   "localization",
   "deployability"
  ],
  "simulator": "pyramid"
 },
 {
  "id": "set-prediction",
  "name": "Set Prediction",
  "category": "architecture",
  "summary": "Predict a fixed-size set of boxes and classes in one pass with a transformer decoder over learned object queries, supervised by a Hungarian-matching set loss, removing anchors and NMS entirely.",
  "firstYear": 2020,
  "paperCount": 18,
  "paperIds": [
   "OD057",
   "OD063",
   "OD065",
   "OD066",
   "OD070",
   "OD076",
   "OD078",
   "OD082",
   "OD084",
   "OD085",
   "OD090",
   "OD092",
   "OD093",
   "OD095",
   "OD096",
   "OD100",
   "OD108",
   "OD112"
  ],
  "addresses": [
   "convergence",
   "label-assignment",
   "speed-latency",
   "anchor-design",
   "training-instability",
   "nms"
  ],
  "simulator": "hungarian"
 },
 {
  "id": "two-stage",
  "name": "Two Stage",
  "category": "architecture",
  "summary": "A small sliding-window network over the shared feature map regresses k anchor-referenced boxes and objectness scores per location, whose proposals then feed the Fast R-CNN detector inside a single unified network.",
  "firstYear": 2015,
  "paperCount": 17,
  "paperIds": [
   "OD001",
   "OD005",
   "OD006",
   "OD008",
   "OD009",
   "OD010",
   "OD014",
   "OD023",
   "OD029",
   "OD037",
   "OD040",
   "OD041",
   "OD042",
   "OD043",
   "OD045",
   "OD048",
   "OD080"
  ],
  "addresses": [
   "speed-latency",
   "localization",
   "deployability",
   "small-objects",
   "scale-variance",
   "real-time-edge"
  ]
 },
 {
  "id": "post-processing-nms",
  "name": "Post Processing NMS",
  "category": "postprocessing",
  "summary": "A small sliding-window network over the shared feature map regresses k anchor-referenced boxes and objectness scores per location, whose proposals then feed the Fast R-CNN detector inside a single unified network.",
  "firstYear": 2015,
  "paperCount": 16,
  "paperIds": [
   "OD001",
   "OD002",
   "OD004",
   "OD015",
   "OD021",
   "OD024",
   "OD026",
   "OD027",
   "OD037",
   "OD050",
   "OD055",
   "OD059",
   "OD061",
   "OD067",
   "OD071",
   "OD083"
  ],
  "addresses": [
   "localization",
   "one-stage-accuracy",
   "small-objects",
   "speed-latency",
   "deployability",
   "nms"
  ],
  "simulator": "nms"
 },
 {
  "id": "dense-prediction",
  "name": "Dense Prediction",
  "category": "architecture",
  "summary": "The image is split into an S x S grid whose cells predict B boxes with confidences and C conditional class probabilities, decoded at test time into class-specific scores and filtered with non-max suppression.",
  "firstYear": 2015,
  "paperCount": 15,
  "paperIds": [
   "OD002",
   "OD006",
   "OD007",
   "OD012",
   "OD013",
   "OD014",
   "OD017",
   "OD019",
   "OD031",
   "OD046",
   "OD052",
   "OD058",
   "OD060",
   "OD062",
   "OD070"
  ],
  "addresses": [
   "localization",
   "one-stage-accuracy",
   "speed-latency",
   "small-objects",
   "scale-variance",
   "deployability"
  ],
  "simulator": "box-regression"
 },
 {
  "id": "anchor-free",
  "name": "Anchor Free",
  "category": "architecture",
  "summary": "A VGG-19-derived fully convolutional network upsamples a fused conv3_4/conv4_4 feature map to a dense 5-channel output (score and box distances), with non-max suppression as the only non-network step.",
  "firstYear": 2015,
  "paperCount": 14,
  "paperIds": [
   "OD003",
   "OD007",
   "OD036",
   "OD046",
   "OD049",
   "OD055",
   "OD062",
   "OD075",
   "OD086",
   "OD087",
   "OD091",
   "OD092",
   "OD109",
   "OD116"
  ],
  "addresses": [
   "anchor-design",
   "speed-latency",
   "localization",
   "label-assignment",
   "small-objects",
   "deployability"
  ],
  "simulator": "anchors-vs-free"
 },
 {
  "id": "nms-free",
  "name": "NMS Free",
  "category": "postprocessing",
  "summary": "Extend scaled dot-product attention with a geometric weight over relative box coordinates, apply it in-place to all RoI features for recognition, and reuse it with rank features to classify duplicates instead of runni…",
  "firstYear": 2017,
  "paperCount": 14,
  "paperIds": [
   "OD028",
   "OD049",
   "OD057",
   "OD070",
   "OD072",
   "OD082",
   "OD090",
   "OD093",
   "OD096",
   "OD104",
   "OD105",
   "OD106",
   "OD116",
   "OD118"
  ],
  "addresses": [
   "speed-latency",
   "nms",
   "deployability",
   "convergence",
   "label-assignment",
   "anchor-design"
  ]
 },
 {
  "id": "dynamic-assignment",
  "name": "Dynamic Assignment",
  "category": "training",
  "summary": "Sample images at multiple pyramid resolutions, mark RoIs/anchors outside a per-scale validity range as invalid, zero their gradients during training, classify each resolution independently at inference, and fuse detec…",
  "firstYear": 2017,
  "paperCount": 12,
  "paperIds": [
   "OD026",
   "OD029",
   "OD054",
   "OD059",
   "OD062",
   "OD068",
   "OD069",
   "OD087",
   "OD092",
   "OD094",
   "OD108",
   "OD112"
  ],
  "addresses": [
   "label-assignment",
   "speed-latency",
   "anchor-design",
   "one-stage-accuracy",
   "localization",
   "deployability"
  ],
  "simulator": "dynamic-assignment"
 },
 {
  "id": "iou-loss",
  "name": "IOU Loss",
  "category": "training",
  "summary": "Regress all four bounds jointly with an IoU-based loss L = -ln(IoU) inside a two-branch fully convolutional network that predicts pixel-wise confidence and box heatmaps.",
  "firstYear": 2016,
  "paperCount": 8,
  "paperIds": [
   "OD007",
   "OD024",
   "OD027",
   "OD046",
   "OD059",
   "OD061",
   "OD062",
   "OD120"
  ],
  "addresses": [
   "localization",
   "nms",
   "one-stage-accuracy",
   "label-assignment",
   "scale-variance",
   "anchor-design"
  ],
  "simulator": "iou"
 },
 {
  "id": "distillation",
  "name": "Distillation",
  "category": "training",
  "summary": "Stack existing training, loss, decoding and post-processing tricks on a YOLOv3 architecture so accuracy improves with almost no extra parameters or FLOPs.",
  "firstYear": 2020,
  "paperCount": 8,
  "paperIds": [
   "OD061",
   "OD091",
   "OD094",
   "OD097",
   "OD109",
   "OD111",
   "OD115",
   "OD117"
  ],
  "addresses": [
   "speed-latency",
   "deployability",
   "real-time-edge",
   "training-instability",
   "label-assignment",
   "localization"
  ]
 },
 {
  "id": "reparameterization",
  "name": "Reparameterization",
  "category": "architecture",
  "summary": "Drop anchors and hardware-unfriendly operators, replace the backbone/neck with re-parameterizable RepResBlocks scaled by multipliers, align classification and localization via TAL, and train with quality-aware VFL/DFL…",
  "firstYear": 2022,
  "paperCount": 7,
  "paperIds": [
   "OD087",
   "OD089",
   "OD091",
   "OD094",
   "OD101",
   "OD104",
   "OD114"
  ],
  "addresses": [
   "speed-latency",
   "deployability",
   "real-time-edge",
   "open-vocabulary",
   "label-assignment",
   "convergence"
  ]
 },
 {
  "id": "focal-loss",
  "name": "Focal Loss",
  "category": "training",
  "summary": "Reshape cross-entropy with a modulating factor (1 − pt)^γ (α-balanced in practice) that decays the loss of easy examples to zero, so training on all ~100k anchors is dominated by hard examples without any sampling heu…",
  "firstYear": 2017,
  "paperCount": 6,
  "paperIds": [
   "OD020",
   "OD044",
   "OD046",
   "OD049",
   "OD063",
   "OD095"
  ],
  "addresses": [
   "speed-latency",
   "anchor-design",
   "background-false-positives",
   "label-assignment",
   "class-imbalance",
   "convergence"
  ],
  "simulator": "focal"
 },
 {
  "id": "self-attention",
  "name": "Self Attention",
  "category": "architecture",
  "summary": "Extend scaled dot-product attention with a geometric weight over relative box coordinates, apply it in-place to all RoI features for recognition, and reuse it with rank features to classify duplicates instead of runni…",
  "firstYear": 2017,
  "paperCount": 6,
  "paperIds": [
   "OD028",
   "OD052",
   "OD057",
   "OD099",
   "OD104",
   "OD113"
  ],
  "addresses": [
   "speed-latency",
   "nms",
   "training-instability",
   "one-stage-accuracy",
   "small-objects",
   "label-assignment"
  ],
  "simulator": "attention"
 },
 {
  "id": "keypoint-based",
  "name": "Keypoint Based",
  "category": "architecture",
  "summary": "Replace anchor boxes by predicting two corner heatmaps grouped via associative embeddings and refined by offsets, with corner pooling extending feature evidence toward object boundaries.",
  "firstYear": 2018,
  "paperCount": 6,
  "paperIds": [
   "OD036",
   "OD041",
   "OD049",
   "OD050",
   "OD051",
   "OD055"
  ],
  "addresses": [
   "anchor-design",
   "localization",
   "speed-latency",
   "label-assignment",
   "background-false-positives",
   "regression-limits"
  ],
  "simulator": "edge-scenarios"
 },
 {
  "id": "open-vocabulary-clip",
  "name": "Open Vocabulary CLIP",
  "category": "architecture",
  "summary": "Ground every region against phrases in a text prompt with a unified loss, fuse vision and language deeply across encoder layers, and self-train on detection, gold grounding, and pseudo-labeled image-text data.",
  "firstYear": 2021,
  "paperCount": 6,
  "paperIds": [
   "OD081",
   "OD101",
   "OD106",
   "OD111",
   "OD114",
   "OD121"
  ],
  "addresses": [
   "open-vocabulary",
   "annotation-cost",
   "deployability",
   "speed-latency",
   "long-tail",
   "real-time-edge"
  ]
 },
 {
  "id": "gaussian-heatmap",
  "name": "Gaussian Heatmap",
  "category": "mathematics",
  "summary": "A VGG-19-derived fully convolutional network upsamples a fused conv3_4/conv4_4 feature map to a dense 5-channel output (score and box distances), with non-max suppression as the only non-network step.",
  "firstYear": 2015,
  "paperCount": 5,
  "paperIds": [
   "OD003",
   "OD036",
   "OD049",
   "OD050",
   "OD055"
  ],
  "addresses": [
   "anchor-design",
   "localization",
   "small-objects",
   "label-assignment",
   "background-false-positives",
   "speed-latency"
  ],
  "simulator": "edge-scenarios"
 },
 {
  "id": "sparse-sampling",
  "name": "Sparse Sampling",
  "category": "architecture",
  "summary": "Sample images at multiple pyramid resolutions, mark RoIs/anchors outside a per-scale validity range as invalid, zero their gradients during training, classify each resolution independently at inference, and fuse detec…",
  "firstYear": 2017,
  "paperCount": 4,
  "paperIds": [
   "OD026",
   "OD044",
   "OD051",
   "OD072"
  ],
  "addresses": [
   "speed-latency",
   "deployability",
   "background-false-positives",
   "small-objects",
   "scale-variance",
   "real-time-edge"
  ]
 },
 {
  "id": "focal-loss-quality",
  "name": "Focal Loss Quality",
  "category": "training",
  "summary": "Merge localization quality into the class-score vector and learn a discretized probability distribution over box coordinates, optimizing both with a continuous-label generalization of Focal Loss.",
  "firstYear": 2020,
  "paperCount": 4,
  "paperIds": [
   "OD058",
   "OD062",
   "OD087",
   "OD112"
  ],
  "addresses": [
   "speed-latency",
   "localization",
   "background-false-positives",
   "convergence",
   "one-stage-accuracy",
   "label-assignment"
  ],
  "simulator": "focal"
 },
 {
  "id": "deformable-attention",
  "name": "Deformable Attention",
  "category": "architecture",
  "summary": "Attend only to a small fixed set of learned sampling locations around a reference point (deformable style) instead of all pixels, aggregated across four feature levels inside a DETR encoder-decoder.",
  "firstYear": 2020,
  "paperCount": 3,
  "paperIds": [
   "OD063",
   "OD080",
   "OD107"
  ],
  "addresses": [
   "speed-latency",
   "small-objects",
   "convergence",
   "scale-variance",
   "deployability",
   "real-time-edge"
  ],
  "simulator": "deformable-attention"
 },
 {
  "id": "mosaic-augmentation",
  "name": "Mosaic Augmentation",
  "category": "training",
  "summary": "Combine a CSP backbone with a PAN path-aggregation neck and YOLOv3 head, then add empirically validated free training tricks and low-cost inference plugins to maximize COCO AP at real-time FPS on a conventional GPU.",
  "firstYear": 2020,
  "paperCount": 3,
  "paperIds": [
   "OD056",
   "OD075",
   "OD112"
  ],
  "addresses": [
   "speed-latency",
   "label-assignment",
   "convergence",
   "deployability",
   "real-time-edge",
   "anchor-design"
  ],
  "simulator": "mosaic"
 },
 {
  "id": "self-training",
  "name": "Self Training",
  "category": "training",
  "summary": "Replace multi-stage pseudo-labeling with online teacher-student training whose pseudo boxes are softly weighted for classification and variance-filtered for regression.",
  "firstYear": 2021,
  "paperCount": 3,
  "paperIds": [
   "OD074",
   "OD081",
   "OD097"
  ],
  "addresses": [
   "weak-supervision",
   "annotation-cost",
   "pseudo-label-quality",
   "long-tail",
   "open-vocabulary",
   "label-assignment"
  ]
 },
 {
  "id": "anchor-design",
  "name": "Anchor Design",
  "category": "architecture",
  "summary": "Improve a single-stage detector with a set of design changes and then train it jointly on detection and classification data whose labels are merged through a hierarchical WordTree.",
  "firstYear": 2016,
  "paperCount": 2,
  "paperIds": [
   "OD011",
   "OD054"
  ],
  "addresses": [
   "weak-supervision",
   "annotation-cost",
   "open-vocabulary",
   "one-stage-accuracy",
   "label-assignment",
   "localization"
  ],
  "simulator": "anchors"
 },
 {
  "id": "cascade",
  "name": "Cascade",
  "category": "architecture",
  "summary": "Chain a binary anchor-refinement stage and a multi-class detection stage inside one one-stage network, linked by transfer connection blocks, giving two-step cascade regression and negative-anchor filtering at single-s…",
  "firstYear": 2017,
  "paperCount": 2,
  "paperIds": [
   "OD021",
   "OD029"
  ],
  "addresses": [
   "localization",
   "background-false-positives",
   "training-instability",
   "one-stage-accuracy",
   "small-objects",
   "label-assignment"
  ],
  "simulator": "cascade"
 },
 {
  "id": "center-based",
  "name": "Center Based",
  "category": "architecture",
  "summary": "Detect objects as center points on a keypoint heatmap and regress their size and other attributes from image features at those points, with peak extraction replacing NMS.",
  "firstYear": 2019,
  "paperCount": 2,
  "paperIds": [
   "OD049",
   "OD050"
  ],
  "addresses": [
   "anchor-design",
   "background-false-positives",
   "speed-latency",
   "small-objects",
   "label-assignment",
   "localization"
  ]
 },
 {
  "id": "dilated-convolution",
  "name": "Dilated Convolution",
  "category": "architecture",
  "summary": "A weight-sharing multi-branch trident block with distinct dilation rates per branch, trained with scale-aware sampling of object sizes and approximated at inference by the middle branch only.",
  "firstYear": 2019,
  "paperCount": 2,
  "paperIds": [
   "OD043",
   "OD077"
  ],
  "addresses": [
   "small-objects",
   "speed-latency",
   "receptive-field",
   "semantic-gap",
   "scale-variance",
   "thermal-imaging"
  ]
 },
 {
  "id": "distribution-fl",
  "name": "Distribution Fl",
  "category": "mathematics",
  "summary": "Merge localization quality into the class-score vector and learn a discretized probability distribution over box coordinates, optimizing both with a continuous-label generalization of Focal Loss.",
  "firstYear": 2020,
  "paperCount": 2,
  "paperIds": [
   "OD058",
   "OD109"
  ],
  "addresses": [
   "localization",
   "background-false-positives",
   "convergence",
   "speed-latency",
   "class-imbalance",
   "anchor-design"
  ],
  "simulator": "box-regression"
 },
 {
  "id": "self-supervised-pretraining",
  "name": "Self Supervised Pretraining",
  "category": "training",
  "summary": "Turn pre-training into an unsupervised set-prediction problem in which randomly cropped query patches are found in the image by the transformer decoder without any human annotations.",
  "firstYear": 2020,
  "paperCount": 2,
  "paperIds": [
   "OD065",
   "OD088"
  ],
  "addresses": [
   "backbone-design",
   "weak-supervision",
   "convergence",
   "annotation-cost",
   "scale-variance",
   "deployability"
  ]
 },
 {
  "id": "label-assignment-simota",
  "name": "Label Assignment Simota",
  "category": "training",
  "summary": "Make YOLO anchor-free with one direct box prediction per location, decouple classification/regression heads, and assign positives globally with the simplified SimOTA strategy.",
  "firstYear": 2021,
  "paperCount": 2,
  "paperIds": [
   "OD075",
   "OD100"
  ],
  "addresses": [
   "speed-latency",
   "label-assignment",
   "convergence",
   "anchor-design"
  ],
  "simulator": "dynamic-assignment"
 },
 {
  "id": "contrastive-learning",
  "name": "Contrastive Learning",
  "category": "data",
  "summary": "Train dynamic anchor-box queries with contrastive denoising (positives must reconstruct their box, negatives must predict background), initialize positional queries from encoder top-K features while keeping content qu…",
  "firstYear": 2022,
  "paperCount": 2,
  "paperIds": [
   "OD085",
   "OD121"
  ],
  "addresses": [
   "convergence",
   "training-instability",
   "annotation-cost",
   "open-vocabulary",
   "class-confusion"
  ]
 },
 {
  "id": "denoising-training",
  "name": "Denoising Training",
  "category": "training",
  "summary": "Feed noised GT box-label pairs as extra decoder queries and reconstruct them with a matching-free reconstruction loss added to the standard Hungarian loss.",
  "firstYear": 2022,
  "paperCount": 2,
  "paperIds": [
   "OD084",
   "OD085"
  ],
  "addresses": [
   "convergence",
   "training-instability",
   "label-assignment",
   "class-confusion"
  ],
  "simulator": "query-denoising"
 },
 {
  "id": "group-wise-one-to-many",
  "name": "Group Wise One To Many",
  "category": "architecture",
  "summary": "Replicate object queries into K groups with one-to-one assignment inside each group and isolated self-attention, turning group-wise one-to-many supervision into extra training signal without changing inference.",
  "firstYear": 2022,
  "paperCount": 2,
  "paperIds": [
   "OD090",
   "OD093"
  ],
  "addresses": [
   "convergence",
   "label-assignment",
   "training-instability",
   "sparse-supervision"
  ]
 },
 {
  "id": "nas",
  "name": "NAS",
  "category": "architecture",
  "summary": "Search a latency-constrained backbone and shift capacity from head to neck (large neck, small head), then close the gap with aligned label assignment (AlignOTA) and carefully balanced distillation.",
  "firstYear": 2022,
  "paperCount": 2,
  "paperIds": [
   "OD094",
   "OD118"
  ],
  "addresses": [
   "speed-latency",
   "deployability",
   "real-time-edge",
   "label-assignment",
   "nas"
  ]
 },
 {
  "id": "cross-gpu-batch-norm",
  "name": "Cross Gpu Batch Norm",
  "category": "training",
  "summary": "Scale the learning rate linearly with a gradual warmup and compute batch-normalization statistics across all GPUs instead of per device, making large-mini-batch detector training converge quickly and accurately.",
  "firstYear": 2017,
  "paperCount": 1,
  "paperIds": [
   "OD022"
  ],
  "addresses": [
   "speed-latency",
   "convergence",
   "class-imbalance",
   "training-instability"
  ]
 },
 {
  "id": "deformable-sampling",
  "name": "Deformable Sampling",
  "category": "architecture",
  "summary": "Learn task-driven 2D offsets for convolution sampling locations and RoI-pooling bin positions so that receptive fields adapt to object scale and shape.",
  "firstYear": 2017,
  "paperCount": 1,
  "paperIds": [
   "OD013"
  ],
  "addresses": [
   "scale-variance",
   "localization",
   "small-objects"
  ]
 },
 {
  "id": "dense-positive-supervision",
  "name": "Dense Positive Supervision",
  "category": "training",
  "summary": "Add differentiable penalties that repel each proposal from surrounding non-target ground-truth boxes and from other proposals with different targets, on top of the standard attraction loss.",
  "firstYear": 2017,
  "paperCount": 1,
  "paperIds": [
   "OD024"
  ],
  "addresses": [
   "crowded-scenes",
   "localization",
   "nms",
   "occlusion"
  ]
 },
 {
  "id": "hard-negative-mining",
  "name": "Hard Negative Mining",
  "category": "training",
  "summary": "Chain a binary anchor-refinement stage and a multi-class detection stage inside one one-stage network, linked by transfer connection blocks, giving two-step cascade regression and negative-anchor filtering at single-s…",
  "firstYear": 2017,
  "paperCount": 1,
  "paperIds": [
   "OD021"
  ],
  "addresses": [
   "localization",
   "one-stage-accuracy",
   "class-imbalance",
   "small-objects"
  ]
 },
 {
  "id": "large-mini-batch-training",
  "name": "Large Mini Batch Training",
  "category": "training",
  "summary": "Scale the learning rate linearly with a gradual warmup and compute batch-normalization statistics across all GPUs instead of per device, making large-mini-batch detector training converge quickly and accurately.",
  "firstYear": 2017,
  "paperCount": 1,
  "paperIds": [
   "OD022"
  ],
  "addresses": [
   "speed-latency",
   "convergence",
   "class-imbalance",
   "training-instability"
  ]
 },
 {
  "id": "light-head-design",
  "name": "Light Head Design",
  "category": "architecture",
  "summary": "Shrink the channels available to the RoI-wise subnetwork with thin feature maps from large separable convolutions and replace the heavy per-region subnetwork with a single cheap fully connected layer.",
  "firstYear": 2017,
  "paperCount": 1,
  "paperIds": [
   "OD023"
  ],
  "addresses": [
   "two-stage-speed",
   "speed-latency"
  ]
 },
 {
  "id": "warmup-learning-rate",
  "name": "Warmup Learning Rate",
  "category": "training",
  "summary": "Scale the learning rate linearly with a gradual warmup and compute batch-normalization statistics across all GPUs instead of per device, making large-mini-batch detector training converge quickly and accurately.",
  "firstYear": 2017,
  "paperCount": 1,
  "paperIds": [
   "OD022"
  ],
  "addresses": [
   "speed-latency",
   "convergence",
   "class-imbalance",
   "training-instability"
  ]
 },
 {
  "id": "batchnorm-stabilization",
  "name": "Batchnorm Stabilization",
  "category": "training",
  "summary": "Insert BatchNorm throughout the SSD backbone and detection head to make from-scratch training converge stably, then remove the first-layer downsampling and replace the 7x7 stem conv with a stack of 3x3 convs (root blo…",
  "firstYear": 2018,
  "paperCount": 1,
  "paperIds": [
   "OD038"
  ],
  "addresses": [
   "pretraining-dependence",
   "convergence",
   "training-instability"
  ]
 },
 {
  "id": "grid-point-localization",
  "name": "Grid Point Localization",
  "category": "architecture",
  "summary": "Predict N-by-N heatmap locations of grid points for each RoI with an FCN branch, fuse neighbor grid-point features in two orders, and take probability-weighted averages of grid points on each box edge as the box coord…",
  "firstYear": 2018,
  "paperCount": 1,
  "paperIds": [
   "OD041"
  ],
  "addresses": [
   "regression-limits",
   "localization"
  ]
 },
 {
  "id": "long-schedule",
  "name": "Long Schedule",
  "category": "training",
  "summary": "Train unmodified baseline detectors from random initialization with batch-size-independent normalization and 5x-6x longer schedules, then compare against identical ImageNet-pretrained systems under controlled hyper-pa…",
  "firstYear": 2018,
  "paperCount": 1,
  "paperIds": [
   "OD040"
  ],
  "addresses": [
   "benchmark-inconsistency",
   "pretraining-dependence",
   "convergence"
  ]
 },
 {
  "id": "random-init-training",
  "name": "Random Init Training",
  "category": "training",
  "summary": "Train unmodified baseline detectors from random initialization with batch-size-independent normalization and 5x-6x longer schedules, then compare against identical ImageNet-pretrained systems under controlled hyper-pa…",
  "firstYear": 2018,
  "paperCount": 1,
  "paperIds": [
   "OD040"
  ],
  "addresses": [
   "benchmark-inconsistency",
   "pretraining-dependence",
   "convergence"
  ]
 },
 {
  "id": "root-block-stem",
  "name": "Root Block Stem",
  "category": "architecture",
  "summary": "Insert BatchNorm throughout the SSD backbone and detection head to make from-scratch training converge stably, then remove the first-layer downsampling and replace the 7x7 stem conv with a stack of 3x3 convs (root blo…",
  "firstYear": 2018,
  "paperCount": 1,
  "paperIds": [
   "OD038"
  ],
  "addresses": [
   "pretraining-dependence",
   "convergence",
   "training-instability"
  ]
 },
 {
  "id": "rotated-bboxes",
  "name": "Rotated Bboxes",
  "category": "architecture",
  "summary": "Transform each horizontal RoI into a rotated RoI with a small fully connected regressor, then extract position-sensitive features by rotating the sampling grid accordingly.",
  "firstYear": 2018,
  "paperCount": 1,
  "paperIds": [
   "OD042"
  ],
  "addresses": [
   "crowded-scenes",
   "localization",
   "anchor-design"
  ]
 },
 {
  "id": "uncertainty-regression",
  "name": "Uncertainty Regression",
  "category": "mathematics",
  "summary": "Predict a per-coordinate Gaussian localization distribution trained with a KL-divergence regression loss, then use the predicted variances to vote the location of each kept box during NMS.",
  "firstYear": 2018,
  "paperCount": 1,
  "paperIds": [
   "OD037"
  ],
  "addresses": [
   "localization",
   "nms",
   "occlusion"
  ]
 },
 {
  "id": "weight-prediction",
  "name": "Weight Prediction",
  "category": "architecture",
  "summary": "Predict anchor-function weights from a log-encoded box prior with a two-layer residual MLP so that anchor functions are generated on demand instead of enumerated and fixed.",
  "firstYear": 2018,
  "paperCount": 1,
  "paperIds": [
   "OD035"
  ],
  "addresses": [
   "domain-shift",
   "anchor-design",
   "label-assignment"
  ]
 },
 {
  "id": "uncertainty-modeling",
  "name": "Uncertainty Modeling",
  "category": "mathematics",
  "summary": "Emit mean and variance for every bbox coordinate, train with an NLL loss that attenuates inconsistent data, and use the predicted uncertainty as an extra score factor during detection.",
  "firstYear": 2019,
  "paperCount": 1,
  "paperIds": [
   "OD047"
  ],
  "addresses": [
   "real-time-edge",
   "localization",
   "background-false-positives",
   "speed-latency"
  ]
 },
 {
  "id": "ciou",
  "name": "Ciou",
  "category": "mathematics",
  "summary": "Combine a CSP backbone with a PAN path-aggregation neck and YOLOv3 head, then add empirically validated free training tricks and low-cost inference plugins to maximize COCO AP at real-time FPS on a conventional GPU.",
  "firstYear": 2020,
  "paperCount": 1,
  "paperIds": [
   "OD056"
  ],
  "addresses": [
   "real-time-edge",
   "deployability",
   "speed-latency"
  ],
  "simulator": "iou"
 },
 {
  "id": "dynamic-head",
  "name": "Dynamic Head",
  "category": "architecture",
  "summary": "Move from dense or dense-to-sparse detection to purely sparse detection by learning a small fixed set of proposals and conditioning each detection head on its own proposal feature instead of dense candidates and share…",
  "firstYear": 2020,
  "paperCount": 1,
  "paperIds": [
   "OD066"
  ],
  "addresses": [
   "convergence",
   "nms",
   "anchor-design",
   "label-assignment"
  ]
 },
 {
  "id": "edge-detection-based",
  "name": "Edge Detection Based",
  "category": "architecture",
  "summary": "Explicitly pool representative border features (extreme points) from border-sensitive channels and fuse them with the single-point feature to refine classification and regression.",
  "firstYear": 2020,
  "paperCount": 1,
  "paperIds": [
   "OD060"
  ],
  "addresses": [
   "localization",
   "one-stage-accuracy"
  ]
 },
 {
  "id": "learnable-proposals",
  "name": "Learnable Proposals",
  "category": "architecture",
  "summary": "Move from dense or dense-to-sparse detection to purely sparse detection by learning a small fixed set of proposals and conditioning each detection head on its own proposal feature instead of dense candidates and share…",
  "firstYear": 2020,
  "paperCount": 1,
  "paperIds": [
   "OD066"
  ],
  "addresses": [
   "convergence",
   "nms",
   "anchor-design",
   "label-assignment"
  ]
 },
 {
  "id": "sparse-prior",
  "name": "Sparse Prior",
  "category": "architecture",
  "summary": "Move from dense or dense-to-sparse detection to purely sparse detection by learning a small fixed set of proposals and conditioning each detection head on its own proposal feature instead of dense candidates and share…",
  "firstYear": 2020,
  "paperCount": 1,
  "paperIds": [
   "OD066"
  ],
  "addresses": [
   "convergence",
   "nms",
   "anchor-design",
   "label-assignment"
  ]
 },
 {
  "id": "anchor-points",
  "name": "Anchor Points",
  "category": "architecture",
  "summary": "Encode anchor-point coordinates as query position embeddings with shared position encoding, add pattern embeddings for multiple predictions per position, and use row-column decoupled attention to cut memory cost.",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD078"
  ],
  "addresses": [
   "query-interpretability",
   "attention-memory",
   "convergence"
  ]
 },
 {
  "id": "autoregressive-generation",
  "name": "Autoregressive Generation",
  "category": "architecture",
  "summary": "Quantize each box into coordinate tokens plus a class token, serialize all objects of an image (with synthetic noise objects), and train an image-encoder/sequence-decoder transformer to emit the token sequence one tok…",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD079"
  ],
  "addresses": [
   "detector-specialization",
   "deployability"
  ]
 },
 {
  "id": "cross-attention",
  "name": "Cross Attention",
  "category": "architecture",
  "summary": "Predict a conditional spatial query from the decoder embedding and reference point, and form cross-attention from concatenated content and spatial queries/keys so localization range is narrowed per head.",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD076"
  ],
  "addresses": [
   "localization",
   "convergence"
  ],
  "simulator": "attention"
 },
 {
  "id": "deconvolution",
  "name": "Deconvolution",
  "category": "architecture",
  "summary": "Fuse a dilated-convolution branch over Conv4_3 with a deconvolution branch over fc_7 by concatenation, replacing the shallow prediction feature with context- and semantics-enriched features.",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD077"
  ],
  "addresses": [
   "receptive-field",
   "small-objects",
   "thermal-imaging",
   "semantic-gap"
  ]
 },
 {
  "id": "decoupled-head",
  "name": "Decoupled Head",
  "category": "architecture",
  "summary": "Make YOLO anchor-free with one direct box prediction per location, decouple classification/regression heads, and assign positives globally with the simplified SimOTA strategy.",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD075"
  ],
  "addresses": [
   "speed-latency",
   "anchor-design",
   "label-assignment"
  ]
 },
 {
  "id": "ema-teacher",
  "name": "Ema Teacher",
  "category": "training",
  "summary": "Replace multi-stage pseudo-labeling with online teacher-student training whose pseudo boxes are softly weighted for classification and variance-filtered for regression.",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD074"
  ],
  "addresses": [
   "annotation-cost",
   "weak-supervision",
   "pseudo-label-quality"
  ]
 },
 {
  "id": "implicit-knowledge",
  "name": "Implicit Knowledge",
  "category": "architecture",
  "summary": "Model an implicit latent code jointly with the explicit features and merge them with operators chosen for the physical meaning of each layer, giving a single multi-purpose representation at almost no extra inference c…",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD073"
  ],
  "addresses": [
   "multi-task-interference",
   "single-task-models"
  ]
 },
 {
  "id": "kernel-space-alignment",
  "name": "Kernel Space Alignment",
  "category": "architecture",
  "summary": "Model an implicit latent code jointly with the explicit features and merge them with operators chosen for the physical meaning of each layer, giving a single multi-purpose representation at almost no extra inference c…",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD073"
  ],
  "addresses": [
   "multi-task-interference",
   "single-task-models"
  ]
 },
 {
  "id": "language-modeling",
  "name": "Language Modeling",
  "category": "architecture",
  "summary": "Quantize each box into coordinate tokens plus a class token, serialize all objects of an image (with synthetic noise objects), and train an image-encoder/sequence-decoder transformer to emit the token sequence one tok…",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD079"
  ],
  "addresses": [
   "detector-specialization",
   "deployability"
  ]
 },
 {
  "id": "multi-task-learning",
  "name": "Multi Task Learning",
  "category": "architecture",
  "summary": "Model an implicit latent code jointly with the explicit features and merge them with operators chosen for the physical meaning of each layer, giving a single multi-purpose representation at almost no extra inference c…",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD073"
  ],
  "addresses": [
   "multi-task-interference",
   "single-task-models"
  ]
 },
 {
  "id": "optimal-transport",
  "name": "Optimal Transport",
  "category": "mathematics",
  "summary": "Solve a global linear-programming assignment (min total pairwise cls+reg transport cost with supply/demand constraints) via entropic-regularised Sinkhorn-Knopp iteration instead of per-ground-truth hand-crafted rules.",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD069"
  ],
  "addresses": [
   "crowded-scenes",
   "occlusion",
   "label-assignment"
  ]
 },
 {
  "id": "reliability-weighting",
  "name": "Reliability Weighting",
  "category": "architecture",
  "summary": "Replace multi-stage pseudo-labeling with online teacher-student training whose pseudo boxes are softly weighted for classification and variance-filtered for regression.",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD074"
  ],
  "addresses": [
   "annotation-cost",
   "weak-supervision",
   "pseudo-label-quality"
  ]
 },
 {
  "id": "row-column-attention",
  "name": "Row Column Attention",
  "category": "architecture",
  "summary": "Encode anchor-point coordinates as query position embeddings with shared position encoding, add pattern embeddings for multiple predictions per position, and use row-column decoupled attention to cut memory cost.",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD078"
  ],
  "addresses": [
   "query-interpretability",
   "attention-memory",
   "convergence"
  ]
 },
 {
  "id": "sequence-augmentation",
  "name": "Sequence Augmentation",
  "category": "training",
  "summary": "Quantize each box into coordinate tokens plus a class token, serialize all objects of an image (with synthetic noise objects), and train an image-encoder/sequence-decoder transformer to emit the token sequence one tok…",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD079"
  ],
  "addresses": [
   "detector-specialization",
   "deployability"
  ]
 },
 {
  "id": "sparse-attention",
  "name": "Sparse Attention",
  "category": "architecture",
  "summary": "A learned saliency scorer (trained to predict the binarized decoder cross-attention map) selects the top-rho% encoder tokens to be refined by deformable self-attention, with auxiliary detection heads on those selected…",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD080"
  ],
  "addresses": [
   "real-time-edge",
   "small-objects",
   "speed-latency"
  ]
 },
 {
  "id": "token-sparsification",
  "name": "Token Sparsification",
  "category": "architecture",
  "summary": "A learned saliency scorer (trained to predict the binarized decoder cross-attention map) selects the top-rho% encoder tokens to be refined by deformable self-attention, with auxiliary detection heads on those selected…",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD080"
  ],
  "addresses": [
   "real-time-edge",
   "small-objects",
   "speed-latency"
  ]
 },
 {
  "id": "transformer-decoder",
  "name": "Transformer Decoder",
  "category": "architecture",
  "summary": "Quantize each box into coordinate tokens plus a class token, serialize all objects of an image (with synthetic noise objects), and train an image-encoder/sequence-decoder transformer to emit the token sequence one tok…",
  "firstYear": 2021,
  "paperCount": 1,
  "paperIds": [
   "OD079"
  ],
  "addresses": [
   "detector-specialization",
   "deployability"
  ]
 },
 {
  "id": "compound-scaling",
  "name": "Compound Scaling",
  "category": "architecture",
  "summary": "Increase training-time capacity and label-assignment quality (deep supervision guided by lead-head soft labels, planned re-parameterization, compound scaling) while keeping inference cost fixed, then scale the family…",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD089"
  ],
  "addresses": [
   "model-scaling",
   "convergence",
   "speed-latency",
   "label-assignment"
  ]
 },
 {
  "id": "deep-supervision",
  "name": "Deep Supervision",
  "category": "training",
  "summary": "Increase training-time capacity and label-assignment quality (deep supervision guided by lead-head soft labels, planned re-parameterization, compound scaling) while keeping inference cost fixed, then scale the family…",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD089"
  ],
  "addresses": [
   "model-scaling",
   "convergence",
   "speed-latency",
   "label-assignment"
  ]
 },
 {
  "id": "diffusion-noise-to-box",
  "name": "Diffusion Noise To Box",
  "category": "architecture",
  "summary": "Cast object detection as a generative denoising process from noisy boxes to object boxes, refined iteratively at inference by a reusable detection decoder conditioned on once-computed image features.",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD092"
  ],
  "addresses": [
   "crowded-scenes",
   "anchor-design"
  ]
 },
 {
  "id": "label-assignment-decoupled",
  "name": "Label Assignment Decoupled",
  "category": "training",
  "summary": "Increase training-time capacity and label-assignment quality (deep supervision guided by lead-head soft labels, planned re-parameterization, compound scaling) while keeping inference cost fixed, then scale the family…",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD089"
  ],
  "addresses": [
   "model-scaling",
   "convergence",
   "speed-latency",
   "label-assignment"
  ]
 },
 {
  "id": "plain-backbone",
  "name": "Plain Backbone",
  "category": "architecture",
  "summary": "Keep the original ViT architecture untouched by pre-training, then add only minimal fine-tuning-time modules: a simple single-scale-origin pyramid, window attention with sparse cross-window propagation, and convention…",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD088"
  ],
  "addresses": [
   "scale-variance",
   "backbone-design",
   "deployability"
  ]
 },
 {
  "id": "quantization-pruning",
  "name": "Quantization Pruning",
  "category": "architecture",
  "summary": "Rebuild the one-stage YOLO pipeline around hardware-friendly reparameterizable networks and deployment-aware training (TAL assignment, self-distillation, quantization-aware training) so accuracy and real serving laten…",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD091"
  ],
  "addresses": [
   "deployability",
   "speed-latency",
   "training-instability"
  ]
 },
 {
  "id": "reparameterization-free",
  "name": "Reparameterization Free",
  "category": "architecture",
  "summary": "Keep the original ViT architecture untouched by pre-training, then add only minimal fine-tuning-time modules: a simple single-scale-origin pyramid, window attention with sparse cross-window propagation, and convention…",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD088"
  ],
  "addresses": [
   "scale-variance",
   "backbone-design",
   "deployability"
  ]
 },
 {
  "id": "simple-pyramid",
  "name": "Simple Pyramid",
  "category": "architecture",
  "summary": "Keep the original ViT architecture untouched by pre-training, then add only minimal fine-tuning-time modules: a simple single-scale-origin pyramid, window attention with sparse cross-window propagation, and convention…",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD088"
  ],
  "addresses": [
   "scale-variance",
   "backbone-design",
   "deployability"
  ]
 },
 {
  "id": "sliding-window-cnns",
  "name": "Sliding Window Cnns",
  "category": "architecture",
  "summary": "Slice high-resolution images into overlapping patches, run the detector per patch (and optionally on the full image), then merge the predictions with NMS in original coordinates.",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD083"
  ],
  "addresses": [
   "tiny-objects",
   "small-objects",
   "deployability"
  ]
 },
 {
  "id": "trend-aware-loss",
  "name": "Trend Aware Loss",
  "category": "training",
  "summary": "Directly forecast the next frame's boxes from the last and current frames with a dual-flow FPN feature fusion and an IoU-based trend-aware regression weighting, while keeping single-frame inference cost via a cached f…",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD086"
  ],
  "addresses": [
   "real-time-edge",
   "deployability",
   "speed-latency"
  ]
 },
 {
  "id": "window-attention",
  "name": "Window Attention",
  "category": "architecture",
  "summary": "Keep the original ViT architecture untouched by pre-training, then add only minimal fine-tuning-time modules: a simple single-scale-origin pyramid, window attention with sparse cross-window propagation, and convention…",
  "firstYear": 2022,
  "paperCount": 1,
  "paperIds": [
   "OD088"
  ],
  "addresses": [
   "scale-variance",
   "backbone-design",
   "deployability"
  ]
 },
 {
  "id": "auxiliary-supervision",
  "name": "Auxiliary Supervision",
  "category": "training",
  "summary": "Generate reliable gradients through an auxiliary reversible branch (used only during training) plus multi-level auxiliary information, and plan gradient paths with the GELAN backbone so both lightweight and deep model…",
  "firstYear": 2024,
  "paperCount": 1,
  "paperIds": [
   "OD102"
  ],
  "addresses": [
   "class-confusion",
   "convergence",
   "training-instability"
  ]
 },
 {
  "id": "reversible-branch",
  "name": "Reversible Branch",
  "category": "architecture",
  "summary": "Generate reliable gradients through an auxiliary reversible branch (used only during training) plus multi-level auxiliary information, and plan gradient paths with the GELAN backbone so both lightweight and deep model…",
  "firstYear": 2024,
  "paperCount": 1,
  "paperIds": [
   "OD102"
  ],
  "addresses": [
   "class-confusion",
   "convergence",
   "training-instability"
  ]
 }
];

export const SOLUTION_BY_ID: Record<string, Solution> = Object.fromEntries(SOLUTIONS.map((s) => [s.id, s]));

/* solution tag -> simulator label (view glue) */
export const SIMULATOR_INDEX: Record<string, string> = {
 "multi-scale": "Multi Scale",
 "transformer-query": "Transformer Query",
 "anchors": "Anchors",
 "attention": "Attention",
 "feature-pyramid": "Feature Pyramid",
 "set-prediction": "Set Prediction",
 "post-processing-nms": "Post Processing NMS",
 "dense-prediction": "Dense Prediction",
 "anchor-free": "Anchor Free",
 "dynamic-assignment": "Dynamic Assignment",
 "iou-loss": "IOU Loss",
 "focal-loss": "Focal Loss",
 "self-attention": "Self Attention",
 "keypoint-based": "Keypoint Based",
 "gaussian-heatmap": "Gaussian Heatmap",
 "focal-loss-quality": "Focal Loss Quality",
 "deformable-attention": "Deformable Attention",
 "mosaic-augmentation": "Mosaic Augmentation",
 "anchor-design": "Anchor Design",
 "cascade": "Cascade",
 "distribution-fl": "Distribution Fl",
 "label-assignment-simota": "Label Assignment Simota",
 "denoising-training": "Denoising Training",
 "ciou": "Ciou",
 "cross-attention": "Cross Attention"
};
