/* Object Detection Research Lab — data model (pipeline v2, 121 papers).
 *
 * Provenance rules (audited by __tests__/audit.test.ts):
 *  - Data files are generated by scripts/od_build.py from
 *    papers/object_detection/harvest/*.json (quote-verified against the
 *    PDF text) plus analysis files authored by review passes.
 *  - Every `quote` in any data file must be verbatim-present in that
 *    paper's harvest record (which was itself verified against the PDF).
 *  - evidence.kind: "paperSays" (grounded in listed papers),
 *    "crossPaper" (consistent across 2+ corpus papers),
 *    "labInterpretation" (analytic synthesis — never shown as fact).
 */

export type EvidenceKind = "paperSays" | "crossPaper" | "labInterpretation";
export type Confidence = "HIGH" | "MEDIUM" | "LOW";

export type Evidence = {
  paperIds: string[];
  kind: EvidenceKind;
  confidence: Confidence;
  /** e.g. "Abstract", "Sec 3.1", "Table 2" */
  location?: string;
  quote?: string;
};

export type QuotedText = { quote: string; location?: string };

export type BenchmarkRow = {
  dataset: string;
  metric: string;
  value: string;
  split?: string;
  location?: string;
};

export type IndustryApplication = {
  domain: string;
  detail: string;
  quote?: string;
  location?: string;
};

/** harvest futureDirections entry (verbatim quote + paraphrase) */
export type PaperFutureDirection = {
  direction: string;
  quote: string;
  location?: string;
};

export type PaperEquation = {
  name?: string;
  expr: string;
  location?: string;
};

export type RelatedWorkEntry = {
  name: string;
  relation: string;
  quote?: string;
  location?: string;
};

/** Every remaining field of a harvest record, verbatim and uncapped,
 *  keyed by paper id in data/harvest-records.ts (lazy-loaded by the
 *  paper explorer). Sections already carried in full on Paper
 *  (futureDirections, industryApplications, deploymentClaims,
 *  benchmarks, datasets, metrics) are not repeated here. */
export type PaperHarvest = {
  problem: { summary: string; statements: string[]; evidence: QuotedText[] };
  background: {
    summary: string;
    relatedWork: RelatedWorkEntry[];
    evidence: QuotedText[];
  };
  solution: {
    summary: string;
    approach: string;
    components: string[];
    evidence: QuotedText[];
  };
  experiments: { summary: string; baselines: string[]; evidence: QuotedText[] };
  limitations: { summary: string; items: string[]; evidence: QuotedText[] };
  industry: { evidence: QuotedText[] };
  technical: {
    algorithms: string[];
    backbones: string[];
    models: string[];
    equations: PaperEquation[];
  };
};

export type Paper = {
  id: string;
  arxiv?: string | null;
  title: string;
  shortTitle: string;
  year: number;
  authors: string[];
  fileName: string;
  /** all corpus PDFs for this paper (deduped downloads) */
  files: string[];
  venue?: string | null;
  doi?: string | null;
  pdfUrl?: string | null;
  /** OpenAlex citation count (null when unresolved) */
  citations?: number | null;
  pages?: number;
  /** combined problem+solution tag slugs (first 8) */
  tags: string[];
  problemTags: string[];
  solutionTags: string[];
  /** one-line method paraphrase (harvest solution.summary) */
  summary: string;
  problemSummary: string;
  contributions: string[];
  limitations: string[];
  datasets: string[];
  metrics: string[];
  benchmarks: BenchmarkRow[];
  futureDirections: PaperFutureDirection[];
  industryApplications: IndustryApplication[];
  deploymentClaims: string[];
  /** corpus ids the paper evidences (= problemTags ∪ solutionTags) */
  evidences: string[];
  /** relative path of the harvest JSON (source of truth) */
  harvestFile: string;
};

/* ------------------------------------------------------------------ problems */

export type ProblemStatus =
  | "resolved"
  | "reduced"
  | "persistent"
  | "transformed"
  | "uncertain";

export type AttemptedSolution = {
  paperId: string;
  shortTitle: string;
  year: number;
  /** one-line approach paraphrase (harvest) */
  approach: string;
  solutionTags: string[];
  quote?: string;
};

export type ProblemEvidence = { paperId: string; quote: string; location?: string };

export type ProblemOccurrence = {
  year: number;
  papers: string[];
  attemptedSolutions: AttemptedSolution[];
  evidence: ProblemEvidence[];
};

export type ProblemLifecycle = {
  id: string;
  shortLabel: string;
  /** consolidated problem statement across papers */
  problem: string;
  statements: string[];
  firstObservedYear: number;
  lastObservedYear: number;
  paperCount: number;
  occurrences: ProblemOccurrence[];
  /** from papers/object_detection/judgments.json (review pass) */
  currentStatus: ProblemStatus;
  statusEvidence: string;
  statusPapers: string[];
};

/* ----------------------------------------------------------------- solutions */

export type SolutionCategory =
  | "architecture"
  | "mathematics"
  | "training"
  | "postprocessing"
  | "data";

export type Solution = {
  id: string;
  name: string;
  category: SolutionCategory;
  /** one-line description (from the corpus's own usage of the tag) */
  summary: string;
  firstYear: number;
  paperCount: number;
  paperIds: string[];
  /** problem ids this solution is attempted against (co-occurrence) */
  addresses: string[];
  /** linked simulator id (sims registry), when one exists */
  simulator?: string;
};

/* ------------------------------------------------------------------- datasets */

export type DatasetInfo = {
  id: string;
  name: string;
  years: number[];
  paperIds: string[];
  note: string;
};

export type MetricInfo = {
  id: string;
  name: string;
  paperCount: number;
  papers: string[];
  note: string;
};

/* ---------------------------------------------------------------- benchmarks */

export type BenchmarkObservation = {
  paperId: string;
  year: number;
  dataset: string;
  metric: string;
  value: number;
  raw: string;
  split?: string;
  location?: string;
};

export type BenchmarkBest = {
  dataset: string;
  metric: string;
  year: number;
  paperId: string;
  value: number;
};

/* -------------------------------------------------------------- yearly state */

export type YearResearchState = {
  year: number;
  paperCount: number;
  dominantApproaches: string[];
  emergingIdeas: string[];
  decliningIdeas: string[];
  persistentProblems: string[];
  newProblems: string[];
  solvedOrReducedProblems: string[];
  unsolvedProblems: string[];
  mathematicalDevelopments: string[];
  architecturalDevelopments: string[];
  computationalDevelopments: string[];
  applications: string[];
  edgeCases: string[];
  researchDirections: string[];
  supportingPapers: string[];
};

export type YearDelta = {
  from: number;
  to: number;
  added: string[];
  removed: string[];
  persisted: string[];
  newProblems: string[];
  summary: string;
  supportingPapers: string[];
};

/* ----------------------------------------------------------------- relations */

export type Relation = {
  from: string;
  to: string;
  kind: "buildsOn" | "contrasts" | "sameProblem" | "sameSolution";
  relation: string;
  quote?: string;
};

/* ------------------------------------------------------------------- clusters */

export type ProblemCluster = {
  id: string;
  name: string;
  description: string;
  problemTags: string[];
  solutionTags: string[];
  papers: string[];
  firstYear: number;
  lastYear: number;
  evidence: Evidence[];
  /** simulator component id implementing this cluster, if any */
  simulator?: string;
};

/* -------------------------------------------------------- future directions */

export type DirectionStatus = "realized" | "partial" | "unresolved";

export type FutureDirection = {
  id: string;
  sourcePaperId: string;
  sourceYear: number;
  direction: string;
  quote: string;
  location?: string;
  status: DirectionStatus;
  /** papers that moved on this direction after the source paper */
  followUps: string[];
  /** the paper (or corpus evidence) that best realizes it */
  realizingPaperId?: string;
  realizationNote: string;
};

/* ------------------------------------------------------ industry vs academic */

export type DomainAdoption = {
  domain: string;
  firstYear: number;
  paperIds: string[];
  /** strength of academic evidence for this domain */
  academicEvidence: number;
  /** "high" | "medium" | "low" — review-pass judgment */
  industryAdoption: Confidence;
  note: string;
};

export type Gap = {
  id: string;
  kind: "academicOnly" | "industryOnly" | "lowAdoption";
  title: string;
  detail: string;
  paperIds: string[];
};

export type IndustryAnalysis = {
  domains: DomainAdoption[];
  gaps: Gap[];
  lowAdoption: { solutionId: string; paperCount: number; reason: string }[];
};

/* --------------------------------------------------------------- saturation */

export type SaturationEntry = {
  problemId: string;
  firstYear: number;
  paperCount: number;
  attemptCount: number;
  /** attempts per year — attention intensity */
  intensity: number;
  status: ProblemStatus;
  saturation: "saturated" | "active" | "dormant" | "emerging";
  remainingGap: string;
  evidence: Evidence[];
};

/* ------------------------------------------------------------ cross-domain */

export type Analogy = {
  id: string;
  domain: string;
  sourceConcept: string;
  detectionConcept: string;
  mapping: string;
  paperIds: string[];
};

/* ---------------------------------------------------------------- audit API */

export type AuditCheck = {
  id: string;
  label: string;
  pass: boolean;
  detail: string;
};

export type ReportSection = {
  id: string;
  label: string;
  kind: string;
};

export type SectionId =
  | "overview"
  | "year"
  | "evolution"
  | "problems"
  | "clusters"
  | "directions"
  | "industry"
  | "saturation"
  | "benchmark"
  | "explorer"
  | "papers"
  | "simulators"
  | "analogy"
  | "ask"
  | "audit";

export const SECTIONS: { id: SectionId; label: string; blurb: string }[] = [
  { id: "overview", label: "Overview", blurb: "The lab at a glance" },
  { id: "year", label: "Year-by-Year", blurb: "Field state per year" },
  { id: "evolution", label: "Evolution", blurb: "Year-over-year deltas" },
  { id: "problems", label: "Problem Matrix", blurb: "Problems across years" },
  { id: "clusters", label: "Problem Clusters", blurb: "Identical-problem clusters" },
  { id: "directions", label: "Future Tracker", blurb: "Stated futures vs later papers" },
  { id: "industry", label: "Academic ↔ Industry", blurb: "Adoption, gaps, applications" },
  { id: "saturation", label: "Saturation", blurb: "Attention vs progress" },
  { id: "benchmark", label: "Benchmark Maps", blurb: "Dataset × metric × year" },
  { id: "explorer", label: "Corpus Explorer", blurb: "Cross-filter the evidence" },
  { id: "papers", label: "Paper Explorer", blurb: "121 papers, evidence-tagged" },
  { id: "simulators", label: "Simulators", blurb: "Interactive learning sims" },
  { id: "analogy", label: "Cross-Domain", blurb: "Physics/chemistry analogies" },
  { id: "ask", label: "Ask the Corpus", blurb: "Questions answered from evidence only" },
  { id: "audit", label: "Research Audit", blurb: "Traceability checks" },
];
