/* GENERATED by scripts/od_build.py — do not edit by hand. */
import type { YearDelta } from "./types";

export const YEAR_DELTAS: YearDelta[] = [
 {
  "from": 2015,
  "to": 2016,
  "added": [
   "real-time-backbone"
  ],
  "removed": [
   "anchor-free",
   "feature-fusion",
   "feature-pyramid",
   "gaussian-heatmap",
   "post-processing-nms"
  ],
  "persisted": [
   "anchors",
   "dense-prediction",
   "multi-scale",
   "one-stage",
   "two-stage"
  ],
  "newProblems": [
   "two-stage-speed",
   "benchmark-inconsistency",
   "annotation-cost",
   "open-vocabulary",
   "weak-supervision"
  ],
  "summary": "2016: 6 papers. +1 approaches (real-time-backbone). −5 approaches. New problems: two-stage-speed, benchmark-inconsistency, annotation-cost.",
  "supportingPapers": [
   "OD001",
   "OD002",
   "OD003",
   "OD004",
   "OD005",
   "OD006",
   "OD007",
   "OD008",
   "OD009",
   "OD010",
   "OD011"
  ]
 },
 {
  "from": 2016,
  "to": 2017,
  "added": [
   "feature-fusion",
   "feature-pyramid"
  ],
  "removed": [
   "anchor-design",
   "iou-loss",
   "real-time-backbone",
   "two-stage"
  ],
  "persisted": [
   "anchors",
   "dense-prediction",
   "multi-scale",
   "one-stage"
  ],
  "newProblems": [
   "crowded-scenes",
   "class-confusion",
   "nms",
   "background-false-positives",
   "training-instability",
   "domain-shift",
   "class-imbalance",
   "convergence",
   "tiny-objects",
   "label-assignment"
  ],
  "summary": "2017: 19 papers. +2 approaches (feature-fusion, feature-pyramid). −4 approaches. New problems: crowded-scenes, class-confusion, nms.",
  "supportingPapers": [
   "OD006",
   "OD007",
   "OD008",
   "OD009",
   "OD010",
   "OD011",
   "OD012",
   "OD013",
   "OD014",
   "OD015",
   "OD016",
   "OD017",
   "OD018",
   "OD019",
   "OD020",
   "OD021",
   "OD022",
   "OD023",
   "OD024",
   "OD025",
   "OD026",
   "OD027",
   "OD028",
   "OD029",
   "OD030"
  ]
 },
 {
  "from": 2017,
  "to": 2018,
  "added": [
   "two-stage"
  ],
  "removed": [
   "attention",
   "cascade",
   "cross-gpu-batch-norm",
   "deformable-sampling",
   "dense-positive-supervision",
   "dense-prediction",
   "dynamic-assignment",
   "focal-loss",
   "hard-negative-mining",
   "large-mini-batch-training",
   "light-head-design",
   "nms-free",
   "post-processing-nms",
   "self-attention",
   "sparse-sampling",
   "warmup-learning-rate"
  ],
  "persisted": [
   "anchors",
   "feature-fusion",
   "feature-pyramid",
   "multi-scale",
   "one-stage"
  ],
  "newProblems": [
   "anchor-design",
   "pretraining-dependence",
   "backbone-mismatch",
   "regression-limits"
  ],
  "summary": "2018: 12 papers. +1 approaches (two-stage). −16 approaches. New problems: anchor-design, pretraining-dependence, backbone-mismatch.",
  "supportingPapers": [
   "OD012",
   "OD013",
   "OD014",
   "OD015",
   "OD016",
   "OD017",
   "OD018",
   "OD019",
   "OD020",
   "OD021",
   "OD022",
   "OD023",
   "OD024",
   "OD025",
   "OD026",
   "OD027",
   "OD028",
   "OD029",
   "OD030",
   "OD031",
   "OD032",
   "OD033",
   "OD034",
   "OD035",
   "OD036",
   "OD037",
   "OD038",
   "OD039",
   "OD040",
   "OD041",
   "OD042"
  ]
 },
 {
  "from": 2018,
  "to": 2019,
  "added": [
   "attention",
   "focal-loss"
  ],
  "removed": [
   "anchor-free",
   "anchors",
   "batchnorm-stabilization",
   "feature-fusion",
   "gaussian-heatmap",
   "grid-point-localization",
   "keypoint-based",
   "long-schedule",
   "random-init-training",
   "root-block-stem",
   "rotated-bboxes",
   "uncertainty-regression",
   "weight-prediction"
  ],
  "persisted": [
   "feature-pyramid",
   "multi-scale",
   "one-stage",
   "two-stage"
  ],
  "newProblems": [],
  "summary": "2019: 12 papers. +2 approaches (attention, focal-loss). −13 approaches. No new problem tags.",
  "supportingPapers": [
   "OD031",
   "OD032",
   "OD033",
   "OD034",
   "OD035",
   "OD036",
   "OD037",
   "OD038",
   "OD039",
   "OD040",
   "OD041",
   "OD042",
   "OD043",
   "OD044",
   "OD045",
   "OD046",
   "OD047",
   "OD048",
   "OD049",
   "OD050",
   "OD051",
   "OD052",
   "OD053",
   "OD054"
  ]
 },
 {
  "from": 2019,
  "to": 2020,
  "added": [
   "anchors",
   "feature-fusion",
   "post-processing-nms",
   "set-prediction",
   "transformer-query"
  ],
  "removed": [
   "anchor-design",
   "attention",
   "center-based",
   "dilated-convolution",
   "dynamic-assignment",
   "feature-pyramid",
   "focal-loss",
   "iou-loss",
   "multi-scale",
   "nms-free",
   "self-attention",
   "sparse-sampling",
   "two-stage",
   "uncertainty-modeling"
  ],
  "persisted": [
   "one-stage"
  ],
  "newProblems": [],
  "summary": "2020: 13 papers. +5 approaches (anchors, feature-fusion, post-processing-nms, set-prediction). −14 approaches. No new problem tags.",
  "supportingPapers": [
   "OD043",
   "OD044",
   "OD045",
   "OD046",
   "OD047",
   "OD048",
   "OD049",
   "OD050",
   "OD051",
   "OD052",
   "OD053",
   "OD054",
   "OD055",
   "OD056",
   "OD057",
   "OD058",
   "OD059",
   "OD060",
   "OD061",
   "OD062",
   "OD063",
   "OD064",
   "OD065",
   "OD066",
   "OD067"
  ]
 },
 {
  "from": 2020,
  "to": 2021,
  "added": [
   "dynamic-assignment"
  ],
  "removed": [
   "ciou",
   "deformable-attention",
   "distillation",
   "distribution-fl",
   "dynamic-head",
   "edge-detection-based",
   "focal-loss-quality",
   "learnable-proposals",
   "mosaic-augmentation",
   "post-processing-nms",
   "self-supervised-pretraining",
   "sparse-prior"
  ],
  "persisted": [
   "anchors",
   "feature-fusion",
   "one-stage",
   "set-prediction",
   "transformer-query"
  ],
  "newProblems": [
   "multi-task-interference",
   "single-task-models",
   "pseudo-label-quality",
   "semantic-gap",
   "receptive-field",
   "thermal-imaging",
   "query-interpretability",
   "attention-memory",
   "detector-specialization",
   "long-tail"
  ],
  "summary": "2021: 14 papers. +1 approaches (dynamic-assignment). −12 approaches. New problems: multi-task-interference, single-task-models, pseudo-label-quality.",
  "supportingPapers": [
   "OD055",
   "OD056",
   "OD057",
   "OD058",
   "OD059",
   "OD060",
   "OD061",
   "OD062",
   "OD063",
   "OD064",
   "OD065",
   "OD066",
   "OD067",
   "OD068",
   "OD069",
   "OD070",
   "OD071",
   "OD072",
   "OD073",
   "OD074",
   "OD075",
   "OD076",
   "OD077",
   "OD078",
   "OD079",
   "OD080",
   "OD081"
  ]
 },
 {
  "from": 2021,
  "to": 2022,
  "added": [
   "anchor-free",
   "reparameterization"
  ],
  "removed": [
   "anchor-points",
   "autoregressive-generation",
   "cross-attention",
   "deconvolution",
   "decoupled-head",
   "dilated-convolution",
   "dynamic-assignment",
   "ema-teacher",
   "feature-fusion",
   "implicit-knowledge",
   "kernel-space-alignment",
   "label-assignment-simota",
   "language-modeling",
   "multi-task-learning",
   "open-vocabulary-clip",
   "optimal-transport",
   "reliability-weighting",
   "row-column-attention",
   "self-training",
   "sequence-augmentation",
   "sparse-attention",
   "sparse-sampling",
   "token-sparsification",
   "transformer-decoder",
   "two-stage"
  ],
  "persisted": [
   "anchors",
   "one-stage",
   "set-prediction",
   "transformer-query"
  ],
  "newProblems": [
   "backbone-design",
   "model-scaling",
   "sparse-supervision"
  ],
  "summary": "2022: 13 papers. +2 approaches (anchor-free, reparameterization). −25 approaches. New problems: backbone-design, model-scaling, sparse-supervision.",
  "supportingPapers": [
   "OD068",
   "OD069",
   "OD070",
   "OD071",
   "OD072",
   "OD073",
   "OD074",
   "OD075",
   "OD076",
   "OD077",
   "OD078",
   "OD079",
   "OD080",
   "OD081",
   "OD082",
   "OD083",
   "OD084",
   "OD085",
   "OD086",
   "OD087",
   "OD088",
   "OD089",
   "OD090",
   "OD091",
   "OD092",
   "OD093",
   "OD094"
  ]
 },
 {
  "from": 2022,
  "to": 2023,
  "added": [
   "attention",
   "feature-fusion",
   "feature-pyramid",
   "multi-scale"
  ],
  "removed": [
   "anchor-free",
   "anchors",
   "compound-scaling",
   "contrastive-learning",
   "deep-supervision",
   "denoising-training",
   "diffusion-noise-to-box",
   "distillation",
   "focal-loss-quality",
   "group-wise-one-to-many",
   "label-assignment-decoupled",
   "nas",
   "one-stage",
   "plain-backbone",
   "quantization-pruning",
   "real-time-backbone",
   "reparameterization",
   "reparameterization-free",
   "self-supervised-pretraining",
   "simple-pyramid",
   "sliding-window-cnns",
   "trend-aware-loss",
   "window-attention"
  ],
  "persisted": [
   "set-prediction",
   "transformer-query"
  ],
  "newProblems": [
   "information-fusion-loss"
  ],
  "summary": "2023: 5 papers. +4 approaches (attention, feature-fusion, feature-pyramid, multi-scale). −23 approaches. New problems: information-fusion-loss.",
  "supportingPapers": [
   "OD082",
   "OD083",
   "OD084",
   "OD085",
   "OD086",
   "OD087",
   "OD088",
   "OD089",
   "OD090",
   "OD091",
   "OD092",
   "OD093",
   "OD094",
   "OD095",
   "OD096",
   "OD097",
   "OD098",
   "OD099"
  ]
 },
 {
  "from": 2023,
  "to": 2024,
  "added": [
   "open-vocabulary-clip",
   "real-time-backbone"
  ],
  "removed": [
   "feature-pyramid",
   "focal-loss",
   "multi-scale",
   "self-attention",
   "self-training"
  ],
  "persisted": [
   "attention",
   "feature-fusion",
   "set-prediction",
   "transformer-query"
  ],
  "newProblems": [],
  "summary": "2024: 13 papers. +2 approaches (open-vocabulary-clip, real-time-backbone). −5 approaches. No new problem tags.",
  "supportingPapers": [
   "OD095",
   "OD096",
   "OD097",
   "OD098",
   "OD099",
   "OD100",
   "OD101",
   "OD102",
   "OD103",
   "OD104",
   "OD105",
   "OD106",
   "OD107",
   "OD108",
   "OD109",
   "OD110",
   "OD111",
   "OD112"
  ]
 },
 {
  "from": 2024,
  "to": 2025,
  "added": [
   "distillation"
  ],
  "removed": [
   "anchor-free",
   "auxiliary-supervision",
   "deformable-attention",
   "distribution-fl",
   "dynamic-assignment",
   "focal-loss-quality",
   "label-assignment-simota",
   "mosaic-augmentation",
   "open-vocabulary-clip",
   "reparameterization",
   "reversible-branch",
   "set-prediction"
  ],
  "persisted": [
   "attention",
   "feature-fusion",
   "one-stage",
   "real-time-backbone",
   "transformer-query"
  ],
  "newProblems": [
   "nas"
  ],
  "summary": "2025: 6 papers. +1 approaches (distillation). −12 approaches. New problems: nas.",
  "supportingPapers": [
   "OD100",
   "OD101",
   "OD102",
   "OD103",
   "OD104",
   "OD105",
   "OD106",
   "OD107",
   "OD108",
   "OD109",
   "OD110",
   "OD111",
   "OD112",
   "OD113",
   "OD114",
   "OD115",
   "OD116",
   "OD117",
   "OD118"
  ]
 },
 {
  "from": 2025,
  "to": 2026,
  "added": [
   "contrastive-learning",
   "iou-loss",
   "open-vocabulary-clip"
  ],
  "removed": [
   "attention",
   "distillation",
   "nas",
   "transformer-query"
  ],
  "persisted": [
   "feature-fusion",
   "one-stage",
   "real-time-backbone"
  ],
  "newProblems": [],
  "summary": "2026: 3 papers. +3 approaches (contrastive-learning, iou-loss, open-vocabulary-clip). −4 approaches. No new problem tags.",
  "supportingPapers": [
   "OD113",
   "OD114",
   "OD115",
   "OD116",
   "OD117",
   "OD118",
   "OD119",
   "OD120",
   "OD121"
  ]
 }
];
