/* GENERATED by scripts/wifi_kb.py — do not edit by hand.
 *
 * Metric definitions are standard and shared across the field; each `paperIds`
 * list is resolved from corpus text so the metric page links only to papers
 * that report it.
 */

import type { MetricRecord } from "./types";

export const METRICS: MetricRecord[] = [
  {
    id: "acc",
    name: "Accuracy",
    family: "classification",
    formula: "accuracy = (TP + TN) / (TP + TN + FP + FN)",
    meaning: "Fraction of all decisions that were correct.",
    intuition: "A single number that is only honest when classes are balanced and the wrong answers are equally costly.",
    example: "70% accuracy on 3 balanced classes against a 33% chance floor.",
    limitations: ["Collapses toward chance as class count grows, which reads as progress.", "Says nothing about which class is being confused with which.", "A majority-class predictor looks strong on imbalanced data."],
    simulator: "activity-clf",
    paperIds: ["W001", "W002", "W003", "W004", "W007", "W009"],
  },
  {
    id: "macro-f1",
    name: "Macro-averaged F1",
    family: "classification",
    formula: "F1_k = 2·P_k·R_k/(P_k+R_k) ;  macro = (1/K)·Σ_k F1_k",
    meaning: "Unweighted mean of per-class F1 scores.",
    intuition: "Asks how well the model does on the rare classes too, which accuracy hides.",
    example: "Macro-F1 of 0.62 when overall accuracy is 0.85 signals the model is failing on a minority class.",
    limitations: ["Requires predicted labels, so it costs a full inference pass.", "Sensitive to the threshold, which is rarely reported."],
    simulator: "activity-clf",
    paperIds: ["W002", "W005", "W020", "W033", "W036", "W049"],
  },
  {
    id: "mae",
    name: "Mean absolute error",
    family: "vital-sign",
    formula: "MAE = (1/N)·Σ|yᵢ − ŷᵢ|",
    meaning: "Average absolute distance between estimate and truth.",
    intuition: "The natural unit for anything measured in bpm or metres: 'off by 0.6 bpm on average' needs no interpretation.",
    example: "MAE of 0.6 bpm on a 15 bpm respiration rate is roughly a 4% error.",
    limitations: ["Hides the tail — a method with a few catastrophic misses can still post a good MAE.", "Uninterpretable without the scale of the target quantity."],
    simulator: "vital-signs",
    paperIds: ["W053", "W123", "W147", "W198", "W200", "W205"],
  },
  {
    id: "rmse",
    name: "Root-mean-square error",
    family: "vital-sign",
    formula: "RMSE = √( (1/N)·Σ(yᵢ − ŷᵢ)² )",
    meaning: "Same as MAE but penalises large misses more heavily.",
    intuition: "Use it when a big miss is much worse than a small one; otherwise MAE is the safer summary.",
    example: "RMSE 0.9 vs MAE 0.6 usually means a handful of large failures.",
    limitations: ["Does not report which sample failed.", "Easy to accidentally compute over a different window than MAE."],
    simulator: "kalman-trajectory",
    paperIds: ["W023", "W043", "W053", "W062", "W068", "W080"],
  },
  {
    id: "median-err",
    name: "Median absolute error",
    family: "vital-sign",
    formula: "median(|y − ŷ|)",
    meaning: "The typical error, ignoring outliers.",
    intuition: "The standard in vital-sign work because body movement produces outliers that wreck a mean.",
    example: "Reporting a median error alongside the mean exposes movement-induced failures.",
    limitations: ["Can look good while a meaningful fraction of windows fail completely.", "Pairs badly with an accuracy claim that ignores failures."],
    simulator: "vital-signs",
    paperIds: ["W011", "W024", "W158", "W162", "W271", "W272"],
  },
  {
    id: "mse",
    name: "Mean position error",
    family: "localization",
    formula: "e = ‖p̂ − p‖₂ ;  report mean / median / 90th percentile",
    meaning: "Euclidean distance between estimated and true position.",
    intuition: "The spatial analogue of MAE, and the only honest way to report a room-scale result.",
    example: "A mean error of 0.6 m with a 90th percentile of 2.1 m tells a very different story from 0.6 m flat.",
    limitations: ["Sensitive to the room size chosen for testing.", "Averages hide regions of the room where the estimate fails."],
    simulator: "rssi-fingerprint",
    paperIds: ["W002", "W004", "W012", "W024", "W043", "W045"],
  },
  {
    id: "auc",
    name: "Detection / occupancy AUC and rate",
    family: "detection",
    formula: "TPR = TP/(TP+FN) at a threshold; AUC = ∫ TPR dFPR",
    meaning: "How reliably presence or motion is detected as a threshold varies.",
    intuition: "Threshold-free, so it separates 'the method works' from 'the threshold was tuned well'.",
    example: "An occupancy detector at 0.9 TPR and 0.05 FPR is usable; 0.9/0.4 is not.",
    limitations: ["Hides whether either class is rare.", "Says nothing about latency, which dominates a fall alarm."],
    simulator: "snr-margin",
    paperIds: ["W005", "W011", "W012", "W013", "W014", "W015"],
  },
  {
    id: "params",
    name: "Parameter count and inference cost",
    family: "efficiency",
    formula: "cost ≈ params × 2 bytes (fp16) ; latency ≈ layers × window / throughput",
    meaning: "Model size and on-device feasibility.",
    intuition: "A 99% paper that needs a GPU server is a different contribution from one that runs on the router.",
    example: "Reporting params and inference time is what makes a 'lightweight' claim checkable.",
    limitations: ["Not comparable across hardware without latency measurements.", "Ignores data-preprocessing cost, which for CSI is often larger."],
    paperIds: ["W001", "W002", "W003", "W004", "W006", "W007"],
  },
];

export const METRIC_BY_ID: Record<string, MetricRecord> = Object.fromEntries(
  METRICS.map((m) => [m.id, m]),
);
