#!/usr/bin/env python3
"""Emit the typed paper-record corpus for the networking lab.

Reads papers/networking/validated.json (post KB validation) and writes
  src/labs/networking/data/records.ts      const PAPERS: PaperRecord[]
  src/labs/networking/data/records.json    same data for test/audit tooling

Record shape mirrors the other labs: every prose field is a quote from the
paper or the honest NOT_STATED marker; `source` says which text depth the
quote came from (full-text / abstract / metadata-only) so the UI can badge it.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CORPUS = ROOT / "papers" / "networking"
OUTDIR = ROOT / "src" / "labs" / "networking" / "data"
NOT_STATED = "not stated in the retrieved text"


def build(r: dict) -> dict:
    # A fileName is only honest if the PDF actually exists on disk; otherwise
    # the UI would emit dead /papers/ links.
    file_name = r.get("fileName", "")
    if file_name and not (CORPUS / file_name).is_file():
        file_name = ""
    links = dict(r.get("links", {}))
    if not file_name:
        links["pdf"] = ""
    return {
        "id": r["id"],
        "title": r["title"],
        "year": r.get("year"),
        "authors": r.get("authors", []),
        "venue": r.get("venue") or "",
        "citations": r.get("citations", 0),
        "doi": r.get("doi", ""),
        "fileName": file_name,
        "links": links,
        "linksStatus": r.get("linksStatus", ""),
        "source": r["source"],
        "hasFullText": r.get("hasFullText", False),
        "domains": r.get("domains", []),
        "solutionFamilies": r.get("solutionFamilies", []),
        "problem": r.get("problem", NOT_STATED),
        "background": r.get("background", NOT_STATED),
        "solution": r.get("solution", NOT_STATED),
        "experiments": r.get("experiments", NOT_STATED),
        "limitations": r.get("limitations", NOT_STATED),
        "futureDirections": r.get("futureDirections", NOT_STATED),
        "industryEvidence": r.get("industryEvidence", NOT_STATED),
        "datasets": r.get("datasets", []),
        "metrics": r.get("metrics", []),
        "algorithms": r.get("algorithms", []),
        "evidence": r.get("evidenceQuotes", {}),
    }


def main() -> int:
    validated = CORPUS / "validated.json"
    if not validated.exists():
        print("run networking_kb.py first", file=sys.stderr)
        return 1
    recs = [build(r) for r in json.loads(validated.read_text())]
    recs.sort(key=lambda x: (-(x["citations"] or 0), -(x["year"] or 0)))
    OUTDIR.mkdir(parents=True, exist_ok=True)
    (OUTDIR / "records.json").write_text(
        json.dumps(recs, indent=1, ensure_ascii=False)
    )
    (OUTDIR / "records.ts").write_text(
        "// GENERATED by scripts/networking_records.py — do not edit by hand.\n"
        f"export const PAPERS = {json.dumps(recs, indent=1, ensure_ascii=False)};\n"
        "export type PapersJson = typeof PAPERS;\n"
    )
    print(f"emitted {len(recs)} paper records")
    return 0


if __name__ == "__main__":
    sys.exit(main())
