#!/usr/bin/env python3
"""Emit src/labs/networking/data/manifest.ts from the corpus manifest.json.

The PDF-serving route (/papers/[file]) allowlists fileNames from this module,
so it must stay in sync with papers/networking/manifest.json.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CORPUS = ROOT / "papers" / "networking"
OUT = ROOT / "src" / "labs" / "networking" / "data" / "manifest.ts"


def main() -> int:
    m = json.loads((CORPUS / "manifest.json").read_text())
    years = [x["year"] for x in m if x.get("year")]
    payload = {
        "total": len(m),
        "window": f"{min(years)}–{max(years)}" if years else "—",
        "totalCitations": sum(x.get("citations", 0) for x in m),
        "papers": [
            {
                "id": x["id"],
                "title": x["title"],
                "year": x.get("year"),
                "citations": x.get("citations", 0),
                # only claim a file we can actually serve
                "fileName": (
                    f
                    if (f := x.get("fileName", "")) and (CORPUS / f).is_file()
                    else ""
                ),
                "doi": x.get("doi", ""),
                "venue": x.get("venue", ""),
            }
            for x in m
        ],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by scripts/networking_manifest.py — do not edit by hand.\n"
        f"export const MANIFEST = {json.dumps(payload, indent=1, ensure_ascii=False)};\n"
    )
    print(f"manifest: {payload['total']} papers, {payload['window']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
