#!/usr/bin/env python3
"""Index the Neuroevolution corpus and emit the typed manifest.

For every downloaded PDF this extracts text once (cached), counts pages, and
classifies the paper along axes the lab actually needs:

  phenotype  what the search produced (MLP, CNN, neurocontroller, program, ...)
  family     which evolutionary algorithm (GA, GP, ES, QD, novelty search, ...)
  encoding   how a genome maps to that phenotype (direct, indirect, ...)
  loci       *which part of the candidate the operators change*
  layers     the evolved network's layer list, when the paper enumerates it
  relevance  neuroevolution / adjacent / off-topic, from the paper's own text

The layer list is the lab's centrepiece — a neuroevolution paper is hard to
read without it — so it is extracted with explicit, quoted evidence rather than
guessed. When a paper does not enumerate its network, `layers` stays empty and
the UI says so.

Unlike scripts/wifi_index.py this writes no architecture into the manifest: the
layer list and operator set are record-level, not corpus-level, and live in
data/papers/*.ts (generated by scripts/neuro_records.py).
"""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from html import unescape

ROOT = pathlib.Path(__file__).resolve().parents[1]
CORPUS = ROOT / "papers" / "neuroevolution"
CACHE = ROOT / ".cache" / "neuro_text"
OUT_TS = ROOT / "src" / "labs" / "neuroevolution" / "data" / "manifest.ts"
HEAD_CHARS = 22000

# ------------------------------------------------------------------ pdf text


def pdf_text(path: pathlib.Path) -> str:
    """Extracted body text, cached per PDF.

    Raw `pdftotext` (no -layout): -layout interleaves the two-column body of
    IEEE/ACM papers line by line, which shreds every sentence this lab quotes.
    """
    if not path.exists():
        return ""
    CACHE.mkdir(parents=True, exist_ok=True)
    out = CACHE / (path.stem + ".txt")
    if out.exists() and out.stat().st_size > 200:
        return out.read_text(errors="replace")
    try:
        r = subprocess.run(
            ["pdftotext", "-q", str(path), "-"],
            capture_output=True,
            timeout=120,
        )
        text = r.stdout.decode("utf-8", "replace")
    except Exception:
        text = ""
    out.write_text(text)
    return text


def pdf_pages(path: pathlib.Path) -> int:
    if not path.exists():
        return 0
    try:
        r = subprocess.run(
            ["pdfinfo", str(path)], capture_output=True, timeout=60, text=True
        )
        m = re.search(r"^Pages:\s+(\d+)", r.stdout, re.M)
        return int(m.group(1)) if m else 0
    except Exception:
        return 0


def head_text(text: str) -> str:
    return text[:HEAD_CHARS]


# ------------------------------------------------------------ vocabularies

# Words that put a paper in this field at all.
NEURO_CUES = (
    "neuroevolution", "neuro-evolution", "evolutionary neural", "evolutionary deep",
    "genetic programming", "genetic algorithm", "evolution strategy", "evolution strategies",
    "quality-diversity", "quality diversity", "map-elites", "map elites", "illumination search",
    "novelty search", "open-ended evolution", "open ended evolution", "behavioral diversity",
    "behavioural diversity", "neat", "hyper-neat", "strongly typed genetic programming",
    "cma-es", "covariance matrix adaptation", "natural evolution strategies",
    "neurocontroller", "evolved controller", "evolved policy", "evolutionary robot",
    "evolutionary architecture search", "mutation operator", "crossover operator",
    "population-based training", "evolving neural network", "evolve neural network",
    "evolutionary algorithm", "evolutionary computation", "evolutionary search",
    "unified novelty search", "novelty archive", "illuminating", "lineage-based",
    "gradient-based hyperheuristic", "age of structure", "aging evolution",
)

# …and words that mean it is not this field.
OFF_TOPIC_CUES = (
    # classical evolutionary optimisation with no neural subject
    "traveling salesman", "vehicle routing", "nurse scheduling", "job shop",
    "knapsack", "bin packing", "supply chain", "test suite prioritization",
    "test suite prioritisation", "program repair", "semantic patch",
    # evolutionary optimisation of physical design
    "antenna design", "structural optimization", "topology optimization of",
    "wind farm layout", "crashworthiness",
    # protein / drug / molecule
    "protein folding", "protein design", "drug discovery", "molecular design",
    "rna folding", "dna design", "molecule generation",
    # evolutionary arts / text gimmicks
    "evolutionary poetry", "evolutionary music", "turing test",
    # non-neuro evolutionary computing that this lab does not cover
    "evolutionary data mining", "genetic algorithm for feature selection",
    "evolutionary fuzzy", "evolving fuzzy",
)

# What the search produces.
PHENOTYPE_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("neurocontroller", ("neurocontroller", "neuro-controller", "neural controller", "evolved controller", "motor controller")),
    ("policy", ("policy network", "evolved policy", "policy search", "controller policy", "behavioural policy", "behavioral policy", "skill policy")),
    ("cnn", ("convolutional neural network", "cnn architecture", "convolutional network", "convnet", "convolutional layer")),
    ("rnn", ("recurrent neural network", "lstm", "gru network", "recurrent layer", "recurrent network", "temporal convolution")),
    ("architecture-search", ("architecture search", "neural architecture search", "architecture optimization", "network architecture search", "topology search", "macro architecture")),
    ("program", ("genetic programming", "symbolic regression", "program synthesis", "evolved program", "genetic programming tree")),
    ("modular", ("modular neural network", "modular evolution", "modularity", "module selection", "multi-module")),
    ("ensemble", ("ensemble of", "mixture of evolved", "population of networks", "multiple experts")),
    ("mlp", ("multilayer perceptron", "multi-layer perceptron", "feedforward network", "feed-forward network", "fully connected network", "fully-connected network", "dense network", "ann ")),
]

# Which evolutionary algorithm family.
FAMILY_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("qd", ("quality-diversity", "quality diversity", "map-elites", "map elites", "illumination search", "archive of elites", "novelty-based diversity")),
    ("novelty-search", ("novelty search", "unified novelty search", "novelty archive", "behavioral novelty", "behavioural novelty", "novelty measure")),
    ("neat", ("neat", "hyper-neat", "neuroevolution of augmenting topologies", "augmenting topologies")),
    ("gp", ("genetic programming", "strongly typed genetic programming", "stgp", "typed genetic programming")),
    ("es", ("natural evolution strategies", "evolution strategy", "evolution strategies", "cma-es", "covariance matrix adaptation", "sep-cma", "mirrored sampling", "cross-entropy method")),
    ("swarm", ("particle swarm", "ant colony", "differential evolution", "artificial bee colony", "firefly algorithm", "self-organizing", "swarm intelligence")),
    ("ga", ("genetic algorithm", "genetic search", "tournament selection", "truncation selection", "genetic operator", "elitism")),
]

# How the genome maps to the phenotype.
ENCODING_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("developmental", ("developmental encoding", "growth rule", "grammatical evolution", "indirect encoding of development", "ontogenetic program")),
    ("graph", ("graph encoding", "network graph", "connection genes", "node genes", "topology encoding", "mutate graph")),
    ("modular", ("modular encoding", "module encoding", "mutable module", "module genome")),
    ("indirect", ("indirect encoding", "grammar", "rule-based encoding", "symbolic encoding", "encoding tree", "primitives")),
    ("direct", ("direct encoding", "genome directly encodes", "each gene is a weight", "weight vector", "genotype is the network")),
]

# ---------------------------------------------------------------- operators

MUTATION_RULES: list[tuple[str, str, tuple[str, ...]]] = [
    ("gaussian", "Gaussian noise on weights", ("gaussian mutation", "gaussian perturbation", "gaussian noise", "additive gaussian", "perturb.*gaussian")),
    ("cauchy", "Cauchy noise (heavy-tailed)", ("cauchy mutation", "cauchy noise", "cauchy perturbation")),
    ("polynomial", "Polynomial mutation", ("polynomial mutation", "polymut", "polynomial bounded")),
    ("sbx", "SBX / simulated binary crossover", ("simulated binary crossover", "sbx", "blx-alpha")),
    ("point", "Point mutation", ("point mutation", "bit-flip", "randomly flip", "resample a gene", "gene reset")),
    ("structural", "Structural mutation (add/remove layer or node)", ("structural mutation", "add a layer", "remove a layer", "add a neuron", "delete a neuron", "insert a node", "node insertion", "layer addition", "growth mutation")),
    ("connection", "Connection mutation", ("connection mutation", "rewire", "add connection", "remove connection", "edge mutation")),
    ("activation", "Activation mutation", ("activation mutation", "change activation", "swap activation")),
    ("rate", "Learning-rate / hyperparameter mutation", ("learning rate mutation", "hyperparameter mutation", "adaptive learning rate", "mutate learning rate", "self-adaptive parameter")),
    ("uniform", "Uniform random mutation", ("uniform random mutation", "randomly mutate", "random perturbation of")),
]

CROSSOVER_RULES: list[tuple[str, str, tuple[str, ...]]] = [
    ("uniform", "Uniform crossover", ("uniform crossover", "uniformly swap", "each gene randomly")),
    ("one-point", "One-point crossover", ("one-point crossover", "single point crossover", "one point crossover")),
    ("two-point", "Two-point crossover", ("two-point crossover", "two point crossover")),
    ("ordered", "Ordered crossover (OX)", ("ordered crossover", "ox crossover", "order preserving crossover")),
    ("partially", "Partially mapped / precedence crossover", ("partially mapped crossover", "pmx", "precedence")),
    ("arithmetic", "Arithmetic / blend crossover", ("arithmetic crossover", "blend crossover", "simplex crossover", "linear combination of the parents")),
    ("recombination", "Direct genotype recombination", ("recombination", "crossover of the two parents", "combine the two networks")),
]

SELECTION_RULES: list[tuple[str, str, tuple[str, ...]]] = [
    ("tournament", "Tournament selection", ("tournament selection", "tournament")),
    ("truncation", "Truncation selection", ("truncation selection", "truncation")),
    ("elitism", "Elitism", ("elitism", "elitist", "elite individuals", "preserve the best")),
    ("roulette", "Roulette-wheel selection", ("roulette", "proportionate selection", "fitness proportionate")),
    ("spea", "SPEA-II", ("spea", "strength pareto")),
    ("nsga", "NSGA-II", ("nsga", "non-dominated sorting", "pareto front", "multiobjective selection")),
    ("novelty", "Novelty selection", ("novelty selection", "select by novelty", "novelty-based selection")),
    ("greedy", "Greedy / incumbent selection", ("greedy selection", "keep the best so far")),
]

# Which part of the candidate gets modified. This is the "how is the
# modification being done" axis, so it gets its own detection table.
LOCUS_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("learning-rate", ("learning rate", "step size", "self-adaptive parameter", "adaptive learning rate")),
    ("activation", ("activation function", "activation layer", "relu", "tanh activation")),
    ("neurons", ("number of neurons", "neuron count", "hidden units", "number of hidden", "width of the layer", "number of units")),
    ("connections", ("weight matrix", "adjacency matrix", "connection weight",
                     "add an edge", "edge mutation", "connectivity pattern")),
    ("topology", ("topology", "layer number", "depth of the network", "number of layers", "architecture gene")),
    ("architecture", ("architecture gene", "architecture parameter", "network architecture", "macro structure", "macro architecture")),
    ("rule", ("production rule", "rule set", "rule set", "instruction set",
              "symbolic expression", "tree node", "primitive")),
    ("weights", ("weight vector", "parameter vector", "coefficient",
                 "bias threshold", "weight mutation", "connection weight")),
    ("behavior", ("behavioural", "behavioral", "behaviour distribution", "behavior distribution", "behaviour space", "behavior space")),
    ("hyperparameters", ("hyperparameter", "batch size", "optimizer setting", "training hyperparameter")),
]

# ---------------------------------------------------------- layer detection

# (kind, regex) — matched against candidate architecture sentences.
LAYER_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("conv", (r"conv(?:olution(?:al)?)?\s*(?:layer)?\s*(?:of|with)?\s*(\d+)?",)),
    ("pool", (r"pooling\s*(?:layer)?", r"max[- ]pool", r"average pool")),
    ("recurrent", (r"\blstm\b", r"\bgru\b", r"recurrent\s*(?:layer|unit|cell)", r"rnn layer")),
    ("attention", (r"attention\s*(?:layer|block|mechanism)", r"self[- ]attention", r"transformer\s*(?:block|encoder)")),
    ("skip", (r"residual\s*(?:connection|block|layer)", r"skip\s*connection", r"shortcut connection")),
    ("dense", (r"fully[- ]connected\s*(?:layer)?", r"dense\s*(?:layer)?", r"multilayer perceptron", r"multi[- ]layer perceptron", r"feed[- ]forward\s*layer", r"hidden layer")),
    ("input", (r"input\s*(?:layer)?", r"input vector", r"state vector of dimension", r"sensory input")),
    ("output", (r"output\s*(?:layer|unit|action)", r"readout layer", r"action head", r"output neuron")),
]

NUM_WORDS = {
    "one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6,
    "seven": 7, "eight": 8, "nine": 9, "ten": 10,
}

# Sentences that describe the network's shape. Ordered: the first group is
# much more likely to enumerate layers than the second.
ARCH_CUES = (
    "architecture consists", "architecture is composed", "network consists",
    "network architecture", "our architecture", "the architecture",
    "network is composed", "layer stack", "hidden layers",
    "we use a network", "we evolve a network", "we evolve networks",
    "the evolved network", "evolved architecture", "network structure",
    "composed of", "consists of", "stack of", "input layer", "hidden layer",
    "output layer", "fully connected", "fully-connected", "convolution",
    "number of layers", "number of neurons", "hidden units", "layers of",
)

FITNESS_CUES = (
    "fitness function", "fitness is", "objective function", "we maximize",
    "we minimize", "reward function", "objective is", "fitness measure",
    "fitness of", "evaluated by", "fitness value", "fitness signal",
)


# Abstract block, in the layouts these papers actually use: a labelled heading,
# or the opening block before the Introduction heading.
ABS_RE = re.compile(
    r"(?:^|\n)\s*(?:Abstract|ABSTRACT)\s*[-:.\u2014]?\s*\n(.+?)"
    r"(?=\n\s*(?:1[\.\s]|I[\.\s]?\s*N|Introduction|INTRODUCTION|Keywords|Index Terms)\b)",
    re.S,
)


def abstract_of(text: str) -> str:
    """Abstract prose, or the first substantive paragraph if unlabelled."""
    m = ABS_RE.search(text[:9000])
    if m:
        body = " ".join(m.group(1).split())
        if len(body) > 120:
            return body
    for para in re.split(r"\n\s*\n", text[:6000]):
        para = " ".join(para.split())
        para = re.sub(r"^(Abstract|ABSTRACT)\s*[-:.\u2014]?\s*", "", para)
        if len(para) > 180:
            return para
    return ""


def sentences(text: str) -> list[str]:
    text = re.sub(r"\s*\n\s*", " ", text)
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z(“\"'(\[])", text)
    out = []
    for p in parts:
        p = " ".join(p.split())
        # drop citation debris left by reference extraction
        p = re.sub(r"\s*,\s*,+", ", ", p)
        p = re.sub(r"\s*[\[\(]\s*[\]\)]\s*", " ", p)
        if len(p) > 40:
            out.append(p)
    return out


def count_before(sent: str) -> int | None:
    """How many of something: 'three fully-connected layers', '2 conv layers'."""
    m = re.search(
        r"\b(\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s+"
        r"([a-z\- ]{0,18}?)(?:conv|dense|pool|lstm|gru|recurrent|hidden|linear|attention)",
        sent,
        re.I,
    )
    if not m:
        return None
    raw = m.group(1).lower()
    return int(raw) if raw.isdigit() else NUM_WORDS.get(raw)


UNIT_PATTERNS = [
    r"(\d+)\s*(?:hidden\s+)?(?:units|neurons|nodes)\s*(?:in|per|each)?",
    r"(?:hidden\s+)?(?:layer|units|layers?)\s*(?:of|with|having|containing)\s*(\d+)\s*(?:units|neurons|nodes)",
    r"(\d+)\s*(?:input|output)\s+(?:units|neurons|nodes)",
    r"(\d+)\s*x\s*\d+\s*(?:convolutional|conv|filter)",
    r"(\d+)\s*(?:channels|filters|feature maps)",
]


def extract_units(sent: str, label: str | None = None) -> int | None:
    """Width of a layer, as the paper states it.

    Tried label-first, because 'output layer of 2 units' and '2 input units'
    both match the generic patterns but mean different things.
    """
    if label:
        pat = rf"{label}[^.]{{0,40}}?(\d+)\s*(?:units|neurons|nodes|channels|filters|features)"
        m = re.search(pat, sent, re.I)
        if m:
            return int(m.group(1))
    for pat in UNIT_PATTERNS:
        m = re.search(pat, sent, re.I)
        if m:
            try:
                return int(m.group(1))
            except (TypeError, ValueError):
                continue
    return None


def detect_layers(sents: list[str]) -> tuple[list[dict], list[str]]:
    """Build an ordered layer list from the paper's own architecture sentences.

    Returns (layers, quotes). Layer dicts carry the matched sentence so the UI
    can show why the layer is there.
    """
    quotes: list[str] = []
    # A sentence qualifies either by naming a layer kind outright, or by one of
    # the architecture cues. The kind match has to stand on its own: many papers
    # state their architecture with none of the cue phrases at all, and gating on
    # the cues alone silently discarded those.
    strong = [s for s in sents if any(re.search(p, s, re.I) for _, ps in LAYER_RULES for p in ps)]
    cand = [s for s in sents if any(c in s.lower() for c in ARCH_CUES)]
    ordered = strong + [s for s in cand if s not in strong]

    layers: list[dict] = []
    seen: set[str] = set()

    def add(kind: str, sent: str, label: str) -> None:
        key = f"{kind}:{label}"
        if key in seen:
            return
        seen.add(key)
        units = extract_units(sent, label)
        layers.append({"kind": kind, "label": label, "units": units, "quote": sent})

    # pass 1: input / output markers first so the chain starts and ends right
    for sent in ordered[:30]:
        low = sent.lower()
        if "input" in low and "output" not in low and not any(l["kind"] == "input" for l in layers):
            add("input", sent, "input")
        if re.search(r"output\s*(?:layer|unit|neuron)|readout", low) and not any(
            l["kind"] == "output" for l in layers
        ):
            add("output", sent, "output")

    # pass 1b: "a three-layer MLP" / "two hidden layers" states the depth
    # explicitly, so the chain is filled in rather than collapsing to one box.
    for sent in ordered[:30]:
        if not layers:
            continue
        m = re.search(
            r"\b(\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s*"
            r"(?:[- ]layer|hidden layers?|-hidden-layer)",
            sent,
            re.I,
        )
        if not m:
            continue
        raw = m.group(1).lower()
        depth = int(raw) if raw.isdigit() else NUM_WORDS.get(raw)
        if not depth or depth < 2 or depth > 12:
            continue
        inner = [k for k in ("conv", "recurrent", "dense", "pool", "attention") if any(l["kind"] == k for l in layers)]
        kind = inner[0] if inner else "dense"
        label = LAYER_LABEL_SHORT.get(kind, kind)
        have = sum(1 for l in layers if l["kind"] == kind)
        for i in range(depth - have):
            layers.append(
                {"kind": kind, "label": label if i == 0 else f"{label} {i + 1}", "units": None, "quote": sent}
            )

    # pass 2: middle layers, in the order they are mentioned
    for sent in ordered[:30]:
        for kind, pats in LAYER_RULES:
            if kind in ("input", "output"):
                continue
            for p in pats:
                m = re.search(p, sent, re.I)
                if m:
                    label = LAYER_LABEL_SHORT.get(kind, kind)
                    add(kind, sent, label)
                    break

    # order: input, then middle, then output
    rank = {"input": 0, "conv": 1, "pool": 2, "dense": 3, "recurrent": 4,
            "attention": 5, "skip": 6, "output": 7, "unknown": 8}
    layers.sort(key=lambda l: rank.get(l["kind"], 9))

    for s in ordered[:3]:
        quotes.append(s)
    return layers[:14], quotes[:3]


LAYER_LABEL_SHORT = {
    "conv": "conv", "pool": "pool", "recurrent": "recurrent",
    "attention": "attention", "skip": "skip", "dense": "dense",
    "input": "input", "output": "output", "step": "step", "unknown": "unstated",
}


def detect_rules(sents: list[str], rules, limit: int = 6):
    """First-match-wins over a rule table of (key, label, cues)."""
    out = []
    for key, label, cues in rules:
        for s in sents:
            if any(re.search(c, s, re.I) for c in cues):
                quote = s
                if isinstance(label, tuple):
                    label, quote = label, s
                out.append({"key": key, "label": label, "quote": quote})
                break
        if len(out) >= limit:
            break
    return out


def first_match(hay: str, rules: list[tuple[str, tuple[str, ...]]]) -> str:
    for name, keys in rules:
        if any(k in hay for k in keys):
            return name
    return "other"


def classify_relevance(title: str, hay: str) -> str:
    t = title.lower()
    neuro = any(c in hay for c in NEURO_CUES) or any(c in t for c in NEURO_CUES)
    off = [c for c in OFF_TOPIC_CUES if c in t]

    if off and not any(c in t for c in ("neural", "network", "controller", "policy")):
        return "off-topic"
    if neuro and not off:
        return "neuroevolution"
    if neuro and off:
        return "adjacent"
    return "adjacent"


TAG_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("quality-diversity", ("quality-diversity", "map-elites", "illumination")),
    ("novelty-search", ("novelty search", "novelty archive")),
    ("open-ended", ("open-ended", "open ended")),
    ("modular", ("modular", "module selection")),
    ("direct-encoding", ("direct encoding",)),
    ("indirect-encoding", ("indirect encoding", "grammatical evolution", "developmental")),
    ("strongly-typed-gp", ("strongly typed genetic programming", "typed genetic programming")),
    ("policy-search", ("policy search", "evolved policy", "policy gradient")),
    ("architecture-search", ("architecture search", "network architecture search")),
    ("neurocontrol", ("neurocontroller", "neuro-control", "motor controller")),
    ("locomotion", ("locomotion", "gait", "walking", "running")),
    ("multi-agent", ("multi-agent", "swarm", "collective")),
    ("deep-network", ("deep neural", "deep learning", "convolutional", "lstm")),
    ("benchmark", ("benchmark", "bench suite")),
]


def enrich_row(row: dict) -> dict:
    pdf = CORPUS / row["fileName"]
    text = pdf_text(pdf) if pdf.exists() else ""
    hay = (row["title"] + "\n" + head_text(text)).lower()

    row["pdfBytes"] = pdf.stat().st_size if pdf.exists() else 0
    row["pages"] = pdf_pages(pdf) if pdf.exists() else 0
    row["task"] = first_match(hay, PHENOTYPE_RULES)
    row["family"] = first_match(hay, FAMILY_RULES)
    row["encoding"] = first_match(hay, ENCODING_RULES)
    _, tags = (list(TAG_RULES), None)
    fired = [n for n, keys in TAG_RULES if any(k in hay for k in keys)]
    row["tags"] = fired
    row["relevance"] = classify_relevance(row["title"], hay)
    return row


def q(s: str) -> str:
    s = str(s)
    for _ in range(3):
        t = unescape(s)
        if t == s:
            break
        s = t
    return json.dumps(s, ensure_ascii=False)


def emit_ts(rows: list[dict]) -> None:
    L = [
        "/* GENERATED by scripts/neuro_index.py — do not edit by hand.",
        " * Source: papers/neuroevolution/manifest.json, enriched from the PDFs.",
        " *",
        " * phenotype / family / encoding / tags are keyword classifications over",
        " * each paper's own title + abstract + opening text, not editorial",
        " * judgements. The per-paper architecture lives in data/papers/*.ts.",
        " */",
        "",
        "export type ManifestEntry = {",
        "  id: string;",
        "  arxiv: string;",
        "  doi?: string;",
        "  title: string;",
        "  year: number;",
        "  authors: string[];",
        "  venue?: string;",
        "  citations: number;",
        "  /** what the search produced */",
        "  task: string;",
        "  /** which evolutionary algorithm family */",
        "  family: string;",
        "  /** how a genome maps to that phenotype */",
        "  encoding: string;",
        "  tags: string[];",
        "  relevance: string;",
        "  fileName: string;",
        "  pdfBytes: number;",
        "  pages: number;",
        "};",
        "",
        "/** Citation-ordered corpus. Index 0 is the most-cited paper. */",
        "export const MANIFEST: ManifestEntry[] = [",
    ]
    for p in rows:
        bits = [f"id: {q(p['id'])}", f"arxiv: {q(p['arxiv'])}"]
        if p.get("doi"):
            bits.append(f"doi: {q(p['doi'])}")
        bits += [
            f"title: {q(p['title'])}",
            f"year: {int(p.get('year') or 0)}",
            f"authors: {json.dumps(p.get('authors') or [], ensure_ascii=False)}",
        ]
        if p.get("venue"):
            bits.append(f"venue: {q(p['venue'])}")
        bits += [
            f"citations: {int(p.get('citations') or 0)}",
            f"task: {q(p.get('task', 'other'))}",
            f"family: {q(p.get('family', 'other'))}",
            f"encoding: {q(p.get('encoding', 'other'))}",
            f"tags: {json.dumps(p.get('tags') or [], ensure_ascii=False)}",
            f"relevance: {q(p.get('relevance', 'adjacent'))}",
            f"fileName: {q(p['fileName'])}",
            f"pdfBytes: {int(p.get('pdfBytes') or 0)}",
            f"pages: {int(p.get('pages') or 0)}",
        ]
        L.append("  { " + ", ".join(bits) + " },")

    cites = [int(p.get("citations") or 0) for p in rows]
    yrs = [int(p.get("year") or 0) for p in rows if p.get("year")]
    L += [
        "];",
        "",
        "export const MANIFEST_BY_ID: Record<string, ManifestEntry> = Object.fromEntries(",
        "  MANIFEST.map((p) => [p.id, p]),",
        ");",
        "",
        f"export const MANIFEST_TOTAL_CITATIONS = {sum(cites)};",
    ]
    if yrs:
        L.append(f"export const YEAR_MIN = {min(yrs)};")
        L.append(f"export const YEAR_MAX = {max(yrs)};")
    L += [
        "",
        "export function manifestByTask(task: string): ManifestEntry[] {",
        "  return MANIFEST.filter((m) => m.task === task);",
        "}",
        "",
    ]
    OUT_TS.write_text("\n".join(L))


def main() -> int:
    manifest_path = CORPUS / "manifest.json"
    if not manifest_path.exists():
        print(f"missing {manifest_path}; run scripts/harvest_neuroevolution.py", file=sys.stderr)
        return 1
    rows = json.loads(manifest_path.read_text())
    print(f"indexing {len(rows)} papers", flush=True)

    with ThreadPoolExecutor(max_workers=8) as ex:
        rows = list(ex.map(enrich_row, rows))

    summary = {
        "count": len(rows),
        "totalCitations": sum(int(r.get("citations") or 0) for r in rows),
        "totalPages": sum(int(r.get("pages") or 0) for r in rows),
        "withText": sum(1 for r in rows if r.get("pdfBytes", 0) > 0),
        "byTask": {},
        "byFamily": {},
        "byEncoding": {},
        "byRelevance": {},
        "yearRange": None,
    }
    for key, field in (
        ("byTask", "task"),
        ("byFamily", "family"),
        ("byEncoding", "encoding"),
        ("byRelevance", "relevance"),
    ):
        for r in rows:
            v = r.get(field, "other")
            summary[key][v] = summary[key].get(v, 0) + 1
    yrs = [int(r["year"]) for r in rows if r.get("year")]
    if yrs:
        summary["yearRange"] = [min(yrs), max(yrs)]

    for r in rows:
        r.pop("abstract", None)
    manifest_path.write_text(json.dumps(rows, indent=2) + "\n")
    emit_ts(rows)
    (CORPUS / "index_summary.json").write_text(json.dumps(summary, indent=2) + "\n")

    print(f"wrote {OUT_TS.relative_to(ROOT)} ({len(rows)} papers)")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())