#!/usr/bin/env python3
"""Build the Object Detection lab's TypeScript data projections.

Inputs:
  papers/object_detection/manifest.json          (od_manifest.py)
  papers/object_detection/harvest/*.json         (verified harvest records)
  papers/object_detection/judgments.json         (review-pass statuses)

Outputs (src/labs/object-detection/data/):
  papers.ts problems.ts solutions.ts datasets.ts metrics.ts
  benchmarks.ts relations.ts years.ts year-deltas.ts audit.ts

Also emits analysis bundles to .cache/od_analysis/ for the review passes
(clusters / directions / industry / saturation).

Deterministic and idempotent: re-running only refreshes generated files;
judgments.json and review-authored files are never touched.

Usage: python3 scripts/od_build.py
"""

from __future__ import annotations

import json
import pathlib
import re
from collections import Counter, defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
PDF_DIR = ROOT / "papers" / "object_detection"
HARVEST = PDF_DIR / "harvest"
MANIFEST = PDF_DIR / "manifest.json"
JUDGMENTS = PDF_DIR / "judgments.json"
OUT = ROOT / "src" / "labs" / "object-detection" / "data"
BUNDLE = ROOT / ".cache" / "od_analysis"

GENERATED_NOTE = "/* GENERATED by scripts/od_build.py — do not edit by hand. */\n"

# ------------------------------------------------------------------ normalizing

PROBLEM_ALIASES = {
    "small-object-detection": "small-objects",
    "multi-scale-objects": "scale-variance",
    "nms-redundancy": "nms",
    "slow-convergence": "convergence",
    "compute-efficiency": "deployability",
    "training-efficiency": "convergence",
}

SOLUTION_ALIASES = {
    "one-to-many-hybrid": "group-wise-one-to-many",
    "localization": "iou-loss",
    "label-assignment": "dynamic-assignment",
    "nms": "post-processing-nms",
    "crowded-scenes": "dense-positive-supervision",
    "deployability": "real-time-backbone",
    "occlusion": "feature-fusion",
}

CATEGORY_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("postprocessing", ("nms", "post-processing", "non-max")),
    ("training", ("loss", "assignment", "distill", "training", "supervision",
                  "augmentation", "self-training", "pretraining", "mining",
                  "warmup", "schedule", "batch", "ema", "label", "focal")),
    ("mathematics", ("iou", "regression", "distribution", "transport",
                     "uncertainty", "trend", "gaussian", "optimal")),
    ("data", ("contrastive", "augment", "data")),
    ("architecture", ("stage", "transformer", "anchor", "pyramid", "fusion",
                      "attention", "backbone", "head", "cnn", "convolution",
                      "sampling", "denoising", "reparameterization", "nas",
                      "cascade", "deformable", "proposal", "dense", "keypoint",
                      "center", "corner", "edge-detection", "sparse", "query",
                      "decoder", "window", "kernel", "quantization", "scaling",
                      "receptive", "sliding", "branch", "stem", "grid")),
]


def canon_category(tag: str) -> str:
    for cat, keys in CATEGORY_RULES:
        if any(k in tag for k in keys):
            return cat
    return "architecture"


def title_case(slug: str) -> str:
    keep = {"iou", "nms", "fps", "coco", "voc", "clip", "nas", "cnn", "fdr", "dfl"}
    parts = []
    for w in slug.split("-"):
        parts.append(w.upper() if w in keep else w.capitalize())
    return " ".join(parts)


def short_label(slug: str) -> str:
    return " ".join(w.capitalize() for w in slug.split("-"))


DATASET_CANON = [
    (r"coco", "COCO"),
    (r"pascal voc 2007/2012|voc 2007/2012", "PASCAL VOC 2007+2012"),
    (r"pascal voc\s*2007|voc\s*2007|voc07", "PASCAL VOC 2007"),
    (r"pascal voc\s*2012|voc\s*2012|voc12", "PASCAL VOC 2012"),
    (r"pascal voc|voc", "PASCAL VOC"),
    (r"imagenet-?22k", "ImageNet-22K"),
    (r"imagenet|ilsvrc", "ImageNet"),
    (r"objects?\s*365", "Objects365"),
    (r"^lvis", "LVIS"),
    (r"^cityscapes$", "Cityscapes"),
    (r"^flickr30k$", "Flickr30K"),
    (r"open\s*images", "OpenImages"),
    (r"^dota", "DOTA"),
    (r"^visdrone", "VisDrone"),
    (r"^goldg", "GoldG"),
    (r"^odinw", "ODinW"),
    (r"conceptual captions", "Conceptual Captions"),
]


def canon_dataset(raw: str) -> str:
    s = re.sub(r"\s+", " ", raw).strip()
    low = s.lower()
    for pat, canon in DATASET_CANON:
        if re.search(pat, low):
            return canon
    return s


METRIC_RULES: list[tuple[str, str]] = [
    # detection main metric
    (r"^(map|mAP|mean ap|mmAP)(\s*)@?\[?\.?5[-:]\.?95|^(map|mAP)?@?\[?\.?5[-:,]\.?95\]?$"
     r"|^mAP50[-–:]95$|^AP50:95$|^mAP\s*\(AP50:95\)$|^mmAP\b.*$", "mAP"),
    (r"^(map|mAP)@?0?\.?5$|^mAP50$|^ap@0?\.5$|^AP@0\.5$|^mAP@\.5$", "AP50"),
    (r"^ap@?0?\.?75$|^mAP@0?\.75$|^mAP@\.75$", "AP75"),
    # size splits
    (r"^ap[s_ ]?small$|^apsmall$|^aps$|^ap_s$", "APs"),
    (r"^ap[s_ ]?medium$|^apmedium$|^apm$|^ap_m$", "APm"),
    (r"^ap[s_ ]?large$|^aplarge$|^apl$|^ap_l$", "APL"),
    (r"^ap small/medium/large$|^ap_s/m/l$|^aps/apm/apl$", "APs/APm/APL"),
    (r"^ap[ _]?(small|medium|large)\b", lambda m: {"small": "APs", "medium": "APm", "large": "APL"}[m.group(1)]),
    # other ap flavors
    (r"^(mask ?ap|mask ?mAP)$|^apmask$", "mask AP"),
    (r"^(keypoint ?ap|oks ?ap)$|^apkp$", "keypoint AP"),
    (r"^ap ?box$|^bbox ?ap$", "box AP"),
    (r"^ap ?r$", "APr"), (r"^ap ?c$", "APc"), (r"^ap ?f$", "APf"),
    (r"^apr/apc/apf$", "APr/APc/APf"),
    # speed / compute
    (r"^fps$", "FPS"),
    (r"^(gflops|gflops?)$", "GFLOPs"),
    (r"^flops$", "FLOPs"),
    (r"^(mflops|bflops)$", "FLOPs"),
    (r"^gm(ac)?s?$", "GMACs"),
    (r"^(madds|mult-adds)$", "MAdds"),
    (r"^(params|parameters|parameter count|# ?params)$", "parameters"),
    (r"^params ?\(m\)$", "parameters (M)"),
    # time
    (r"^(latency|inference time|test time|infer time|gpu ms|latency \(ms\)|inference time \(ms\)|test time \(ms\))$",
     "latency (ms)"),
    (r"^time ?\(s/img\)$|^seconds per image$|^test time \(sec/img\)$", "latency (s/img)"),
    (r"^training time.*|^gpu hours$", "training time"),
    (r"^(epochs|training epochs)$", "epochs"),
    # memory
    (r"^gpu memory$|^memory ?\(mb\)$|^training memory$", "GPU memory"),
    # ranking / classification
    (r"^top-?1 accuracy$|^top-1$|^top1$", "top-1 accuracy"),
    (r"^top-?1 error$", "top-1 error"),
    (r"^top-?5 accuracy$|^top-5$|^top5$", "top-5 accuracy"),
    (r"^top-?5 error$", "top-5 error"),
    (r"^ar(@100|100|@1k|1k|300|1000|1|10)?$|^average recall$", "AR"),
    (r"^(ars|arm|arl)$", lambda m: "AR" + m.group(1)[1:].capitalize()),
    (r"^ar_s/m/l$|^ar_s/ml$", "ARs/ARm/ARl"),
    (r"^recall(@10|@100|@1|@5)?$|^mean recall rate$|^r@([0-9]+)$", "recall"),
    (r"^(precision|accuracy|f1|best f1)$", lambda m: {"precision": "precision", "accuracy": "accuracy", "f1": "F1", "best f1": "F1"}[m.group(1)]),
    (r"^(miou|mIOU)$", "mIoU"),
    (r"^mr-2.*$", "mMR"),
    (r"^mm?$", None),  # dropped below
]

METRIC_EXACT = {
    "mmap": "mAP", "map50-95": "mAP", "ap@[0.5:0.95]": "mAP",
    "mean ap": "mAP", "mAP50-95": "mAP", "mAP@0.75": "AP75",
    "mAP@.75": "AP75", "mAP50": "AP50", "mAP75": "AP75",
    "mAP (AP50:95)": "mAP", "ap50:95": "mAP",
    "ap (coco 0.5:0.95)": "mAP", "mmAP (ap iou 0.5:0.95)": "mAP",
    "mask mAP": "mask AP", "maskmap": "mask AP", "mapmask": "mask AP",
    "ars": "ARs", "arm": "ARm", "arl": "ARl",
    "average precision": "AP", "average recall": "AR",
}


def canon_metric(raw: str) -> str:
    s = re.sub(r"\s+", " ", raw).strip()
    low = s.lower()
    if low in METRIC_EXACT:
        return METRIC_EXACT[low]
    # direct dict first
    direct = {
        "ap": "AP", "map": "mAP", "ap50": "AP50", "ap75": "AP75",
        "fps": "FPS", "flops": "FLOPs", "gflops": "GFLOPs",
        "latency (ms)": "latency (ms)", "latency": "latency",
        "parameters": "parameters", "recall": "recall", "precision": "precision",
        "map@[.5:.95]": "mAP", "map@[0.5:0.95]": "mAP", "map@[.5,.95]": "mAP",
        "mAP@0.5": "AP50", "mAP50": "AP50", "mAP75": "AP75",
        "params": "parameters", "fps ": "FPS", "f1": "F1",
        "ar": "AR", "ar100": "AR", "ar@100": "AR", "ar1k": "AR", "ar@1k": "AR",
        "aps": "APs", "apm": "APm", "apl": "APL",
        "ap_s": "APs", "ap_m": "APm", "ap_l": "APL",
        "top-1": "top-1 accuracy", "top-5": "top-5 accuracy",
        "gflops": "GFLOPs", "gflops": "GFLOPs", "gFLOPs": "GFLOPs",
    }
    if low in direct:
        return direct[low]
    for pat, rep in METRIC_RULES:
        if rep is None:
            continue
        m = re.match(pat, low)
        if m:
            return rep(m) if callable(rep) else rep
    return s


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:48]


def short_title(title: str) -> str:
    if ":" in title:
        head = title.split(":")[0].strip()
        if 2 <= len(head) <= 34:
            return head
    words = title.split()
    return " ".join(words[:4]) if len(" ".join(words[:5])) <= 40 else " ".join(words[:3])


def ts(obj) -> str:
    return json.dumps(obj, indent=1, ensure_ascii=False)


def num(raw: str) -> float | None:
    m = re.search(r"-?\d+(?:\.\d+)?", raw.replace(",", ""))
    return float(m.group(0)) if m else None


# ------------------------------------------------------------------- load data

def load() -> tuple[list[dict], dict[str, dict], dict]:
    manifest = json.loads(MANIFEST.read_text())
    harvest: dict[str, dict] = {}
    for p in sorted(HARVEST.glob("OD*.json")):
        rec = json.loads(p.read_text())
        harvest[rec["id"]] = rec
    judgments = json.loads(JUDGMENTS.read_text()) if JUDGMENTS.exists() else {}
    missing = [m["id"] for m in manifest if m["id"] not in harvest]
    if missing:
        raise SystemExit(f"missing harvest records: {missing}")
    return manifest, harvest, judgments


# ------------------------------------------------------------------- papers.ts

def build_papers(manifest: list[dict], harvest: dict[str, dict]) -> list[dict]:
    papers = []
    for m in manifest:
        h = harvest[m["id"]]
        prob = h["problem"]["problemTags"]
        sol = h["solution"]["solutionTags"]
        prob = [PROBLEM_ALIASES.get(t, t) for t in prob]
        sol = [SOLUTION_ALIASES.get(t, t) for t in sol]
        prob = list(dict.fromkeys(prob))
        sol = list(dict.fromkeys(sol))
        papers.append({
            "id": m["id"],
            "arxiv": m.get("arxiv"),
            "title": m["title"],
            "shortTitle": short_title(m["title"]),
            "year": m["year"],
            "authors": m.get("authors", [])[:8],
            "fileName": m["fileName"],
            "files": m["files"],
            "venue": h.get("venue") or m.get("venue"),
            "doi": h["citations"].get("doi") or m.get("doi"),
            "pdfUrl": m.get("pdfUrl"),
            "citations": m.get("citations"),
            "pages": m.get("pages"),
            "tags": (prob + sol)[:8],
            "problemTags": prob,
            "solutionTags": sol,
            "summary": h["solution"]["summary"],
            "problemSummary": h["problem"]["summary"],
            "contributions": [h["solution"]["approach"]]
            + h["solution"]["components"][:6],
            "limitations": h["limitations"]["items"][:5],
            "datasets": list(dict.fromkeys(
                canon_dataset(d) for d in h["technical"]["datasets"])),
            "metrics": list(dict.fromkeys(
                canon_metric(x) for x in h["technical"]["metrics"])),
            "benchmarks": [
                {**{k: v for k, v in b.items() if v},
                 "dataset": canon_dataset(b["dataset"]),
                 "metric": canon_metric(b["metric"])}
                for b in h["experiments"]["benchmarks"]
            ],
            "futureDirections": h["futureDirections"],
            "industryApplications": h["industry"]["applications"],
            "deploymentClaims": h["industry"]["deploymentClaims"][:6],
            "evidences": list(dict.fromkeys(prob + sol)),
            "harvestFile": f"papers/object_detection/harvest/{m['id']}.json",
        })
    return papers


def emit_papers(papers: list[dict]) -> None:
    years = [p["year"] for p in papers]
    cit = sum(p["citations"] or 0 for p in papers)
    body = (
        GENERATED_NOTE
        + 'import type { Paper } from "./types";\n\n'
        + "export const PAPERS: Paper[] = " + ts(papers) + ";\n\n"
        + "export const PAPER_BY_ID: Record<string, Paper> = "
        + "Object.fromEntries(PAPERS.map((p) => [p.id, p]));\n\n"
        + f"export const PAPER_COUNT = {len(papers)};\n"
        + f"export const YEAR_MIN = {min(years)};\n"
        + f"export const YEAR_MAX = {max(years)};\n"
        + f"export const TOTAL_CITATIONS = {cit};\n"
        + f"export const PAPERS_WITH_DOI = "
        + f"{sum(1 for p in papers if p['doi'])};\n"
    )
    (OUT / "papers.ts").write_text(body)


# ----------------------------------------------------------------- problems.ts

def build_problems(papers: list[dict], harvest: dict, judgments: dict) -> list[dict]:
    by_tag: dict[str, list[dict]] = defaultdict(list)
    for p in papers:
        for t in p["problemTags"]:
            by_tag[t].append(p)

    status_j = judgments.get("problemStatuses", {})
    problems = []
    for tag, plist in by_tag.items():
        plist = sorted(plist, key=lambda p: (p["year"], p["id"]))
        # statements: earliest-first, deduped, capped
        stmts: list[str] = []
        seen: set[str] = set()
        for p in plist + plist[::-1]:
            h = harvest[p["id"]]
            for s in h["problem"]["statements"]:
                key = re.sub(r"\s+", " ", s.lower())[:80]
                if key in seen:
                    continue
                seen.add(key)
                stmts.append(s)
            if len(stmts) >= 14:
                break
        # occurrences by year
        by_year: dict[int, list[dict]] = defaultdict(list)
        for p in plist:
            by_year[p["year"]].append(p)
        occurrences = []
        for year in sorted(by_year):
            group = by_year[year]
            attempted = []
            evidence = []
            for p in group:
                h = harvest[p["id"]]
                quote = next(
                    (e["quote"] for e in h["solution"]["evidence"][:3]), None)
                attempted.append({
                    "paperId": p["id"],
                    "shortTitle": p["shortTitle"],
                    "year": year,
                    "approach": h["solution"]["approach"],
                    "solutionTags": p["solutionTags"],
                    **({"quote": quote} if quote else {}),
                })
                pq = next(
                    (e["quote"] for e in h["problem"]["evidence"][:3]), None)
                if pq:
                    evidence.append({"paperId": p["id"], "quote": pq})
            occurrences.append({
                "year": year,
                "papers": [p["id"] for p in group],
                "attemptedSolutions": attempted[:8],
                "evidence": evidence[:6],
            })
        j = status_j.get(tag, {})
        problems.append({
            "id": tag,
            "shortLabel": short_label(tag),
            "problem": stmts[0] if stmts else short_label(tag),
            "statements": stmts[:14],
            "firstObservedYear": plist[0]["year"],
            "lastObservedYear": plist[-1]["year"],
            "paperCount": len(plist),
            "occurrences": occurrences,
            "currentStatus": j.get("status", "uncertain"),
            "statusEvidence": j.get("statusEvidence", ""),
            "statusPapers": j.get("statusPapers", []),
        })
    problems.sort(key=lambda x: (-x["paperCount"], x["firstObservedYear"], x["id"]))
    return problems


def emit_problems(problems: list[dict]) -> None:
    body = (
        GENERATED_NOTE
        + 'import type { ProblemLifecycle } from "./types";\n\n'
        + "export const PROBLEM_LIFECYCLES: ProblemLifecycle[] = "
        + ts(problems) + ";\n\n"
        + "export const PROBLEM_BY_ID: Record<string, ProblemLifecycle> = "
        + "Object.fromEntries(PROBLEM_LIFECYCLES.map((p) => [p.id, p]));\n"
    )
    (OUT / "problems.ts").write_text(body)


# ---------------------------------------------------------------- solutions.ts

SIM_LINKS = {
    "post-processing-nms": "nms",
    "iou-loss": "iou",
    "ciou": "iou",
    "focal-loss": "focal",
    "focal-loss-quality": "focal",
    "anchors": "anchors",
    "anchor-design": "anchors",
    "kmeans-anchors": "anchors",
    "anchor-free": "anchors-vs-free",
    "feature-pyramid": "pyramid",
    "multi-scale": "pyramid",
    "set-prediction": "hungarian",
    "transformer-query": "transformer-query",
    "attention": "attention",
    "self-attention": "attention",
    "cross-attention": "attention",
    "deformable-attention": "deformable-attention",
    "dynamic-assignment": "dynamic-assignment",
    "label-assignment-simota": "dynamic-assignment",
    "denoising-training": "query-denoising",
    "cascade": "cascade",
    "mosaic-augmentation": "mosaic",
    "distribution-fl": "box-regression",
    "receptive-field": "rf",
    "dense-prediction": "box-regression",
    "gaussian-heatmap": "edge-scenarios",
    "keypoint-based": "edge-scenarios",
}


def build_solutions(papers: list[dict], problems: list[dict]) -> list[dict]:
    prob_of_tag: dict[str, set[str]] = defaultdict(set)
    for p in papers:
        for t in p["problemTags"]:
            for s in p["solutionTags"]:
                prob_of_tag[s].add(t)

    by_tag: dict[str, list[dict]] = defaultdict(list)
    for p in papers:
        for t in p["solutionTags"]:
            by_tag[t].append(p)

    prob_labels = {pr["id"]: pr["shortLabel"] for pr in problems}
    solutions = []
    for tag, plist in by_tag.items():
        plist = sorted(plist, key=lambda p: (p["year"], p["id"]))
        probs = sorted(prob_of_tag[tag], key=lambda t: -sum(
            1 for p in plist if t in p["problemTags"]))
        summary = plist[0]["contributions"][0]
        if len(summary) > 220:
            summary = summary[:217].rstrip() + "…"
        solutions.append({
            "id": tag,
            "name": title_case(tag),
            "category": canon_category(tag),
            "summary": summary,
            "firstYear": plist[0]["year"],
            "paperCount": len(plist),
            "paperIds": [p["id"] for p in plist],
            "addresses": probs[:6],
            **({"simulator": SIM_LINKS[tag]} if tag in SIM_LINKS else {}),
        })
    solutions.sort(key=lambda x: (-x["paperCount"], x["firstYear"], x["id"]))
    return solutions


def emit_solutions(solutions: list[dict]) -> None:
    body = (
        GENERATED_NOTE
        + 'import type { Solution } from "./types";\n\n'
        + "export const SOLUTIONS: Solution[] = " + ts(solutions) + ";\n\n"
        + "export const SOLUTION_BY_ID: Record<string, Solution> = "
        + "Object.fromEntries(SOLUTIONS.map((s) => [s.id, s]));\n\n"
        + "/* solution tag -> simulator label (view glue) */\n"
        + "export const SIMULATOR_INDEX: Record<string, string> = "
        + ts({s["id"]: s["name"] for s in solutions if s.get("simulator")})
        + ";\n"
    )
    (OUT / "solutions.ts").write_text(body)


# ------------------------------------------------------- datasets.ts metrics.ts

def build_datasets_metrics(papers: list[dict]) -> tuple[list[dict], list[dict]]:
    ds: dict[str, dict] = {}
    for p in papers:
        for d in p["datasets"]:
            e = ds.setdefault(d, {"name": d, "years": [], "paperIds": []})
            if p["year"] not in e["years"]:
                e["years"].append(p["year"])
            e["paperIds"].append(p["id"])
    datasets = []
    for d, e in sorted(ds.items(), key=lambda kv: -len(kv[1]["paperIds"])):
        years = sorted(e["years"])
        datasets.append({
            "id": slug(d),
            "name": d,
            "years": years,
            "paperIds": sorted(set(e["paperIds"])),
            "note": (f"Used by {len(set(e['paperIds']))} papers, "
                     f"{years[0]}–{years[-1]}"),
        })

    mt: dict[str, set] = defaultdict(set)
    for p in papers:
        for m in p["metrics"]:
            mt[m].add(p["id"])
    metrics = []
    for m, ids in sorted(mt.items(), key=lambda kv: -len(kv[1])):
        metrics.append({
            "id": slug(m),
            "name": m,
            "paperCount": len(ids),
            "papers": sorted(ids),
            "note": f"Reported by {len(ids)} papers",
        })
    return datasets, metrics


def emit_datasets_metrics(datasets: list[dict], metrics: list[dict]) -> None:
    (OUT / "datasets.ts").write_text(
        GENERATED_NOTE
        + 'import type { DatasetInfo } from "./types";\n\n'
        + "export const DATASETS: DatasetInfo[] = " + ts(datasets) + ";\n\n"
        + "export const DATASET_BY_ID: Record<string, DatasetInfo> = "
        + "Object.fromEntries(DATASETS.map((d) => [d.id, d]));\n"
    )
    (OUT / "metrics.ts").write_text(
        GENERATED_NOTE
        + 'import type { MetricInfo } from "./types";\n\n'
        + "export const METRICS: MetricInfo[] = " + ts(metrics) + ";\n"
    )


# --------------------------------------------------------------- benchmarks.ts

def build_benchmarks(papers: list[dict]) -> tuple[list[dict], list[dict]]:
    obs = []
    for p in papers:
        for b in p["benchmarks"]:
            v = num(str(b.get("value", "")))
            if v is None:
                continue
            obs.append({
                "paperId": p["id"],
                "year": p["year"],
                "dataset": b["dataset"],
                "metric": b["metric"],
                "value": v,
                "raw": str(b["value"]),
                **({"split": b["split"]} if b.get("split") else {}),
                **({"location": b["location"]} if b.get("location") else {}),
            })
    best: dict[tuple, dict] = {}
    for o in sorted(obs, key=lambda x: x["year"]):
        key = (o["dataset"], o["metric"])
        cur = best.get(key)
        if cur is None or o["value"] > cur["value"]:
            best[key] = o
    best_rows = [
        {"dataset": k[0], "metric": k[1], "year": v["year"],
         "paperId": v["paperId"], "value": v["value"]}
        for k, v in sorted(best.items(), key=lambda kv: (kv[0][0], kv[0][1]))
    ]
    return obs, best_rows


def emit_benchmarks(obs: list[dict], best: list[dict]) -> None:
    (OUT / "benchmarks.ts").write_text(
        GENERATED_NOTE
        + 'import type { BenchmarkObservation, BenchmarkBest } from "./types";\n\n'
        + "export const BENCHMARKS: BenchmarkObservation[] = "
        + ts(obs) + ";\n\n"
        + "export const BENCHMARK_BEST: BenchmarkBest[] = "
        + ts(best) + ";\n\n"
        + "export const BENCHMARK_DATASETS: string[] = "
        + ts(sorted({o["dataset"] for o in obs})) + ";\n"
    )


# ---------------------------------------------------------------- relations.ts

def norm_key(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", s.lower())


def build_relations(papers: list[dict], harvest: dict) -> list[dict]:
    index: dict[str, str] = {}
    for p in papers:
        index[norm_key(p["title"])] = p["id"]
        index[norm_key(p["shortTitle"])] = p["id"]
        if p["arxiv"]:
            index[p["arxiv"]] = p["id"]
    # alias keys with punctuation removed for relatedWork names
    rels = []
    for p in papers:
        h = harvest[p["id"]]
        for rw in h["background"].get("relatedWork", []):
            name = norm_key(rw.get("name", ""))
            if not name or len(name) < 4:
                continue
            target = index.get(name)
            if target is None:
                # containment match against titles (skip self)
                for k, tid in index.items():
                    if tid != p["id"] and (name in k or k in name) and len(k) >= 6:
                        target = tid
                        break
            if target and target != p["id"]:
                rels.append({
                    "from": p["id"],
                    "to": target,
                    "kind": "buildsOn",
                    "relation": rw.get("relation", "prior work"),
                    **({"quote": rw["quote"]} if rw.get("quote") else {}),
                })
    # dedupe
    seen = set()
    out = []
    for r in rels:
        key = (r["from"], r["to"], r["relation"][:40])
        if key in seen:
            continue
        seen.add(key)
        out.append(r)
    return out


def emit_relations(rels: list[dict]) -> None:
    (OUT / "relations.ts").write_text(
        GENERATED_NOTE
        + 'import type { Relation } from "./types";\n\n'
        + "/* paper -> paper links parsed from background.relatedWork\n"
        + " * where the referenced work is itself in the corpus. */\n"
        + "export const RELATIONS: Relation[] = " + ts(rels) + ";\n"
    )


# -------------------------------------------------------------------- years.ts

def build_years(papers: list[dict], problems: list[dict],
                judgments: dict) -> list[dict]:
    years = sorted({p["year"] for p in papers})
    status_j = judgments.get("problemStatuses", {})
    prob_first = {pr["id"]: pr["firstObservedYear"] for pr in problems}
    prob_last = {pr["id"]: pr["lastObservedYear"] for pr in problems}
    prob_status = {pr["id"]: pr["currentStatus"] for pr in problems}
    rare_problems = {pr["id"] for pr in problems if pr["paperCount"] <= 4}

    sol_counts_year: dict[int, Counter] = defaultdict(Counter)
    prob_counts_year: dict[int, Counter] = defaultdict(Counter)
    for p in papers:
        for t in p["solutionTags"]:
            sol_counts_year[p["year"]][t] += 1
        for t in p["problemTags"]:
            prob_counts_year[p["year"]][t] += 1

    sol_names = {}
    # filled by caller via solutions list is easier; recompute label inline
    states = []
    for i, y in enumerate(years):
        yp = [p for p in papers if p["year"] == y]
        sc = sol_counts_year[y]
        pc = prob_counts_year[y]
        prev = sol_counts_year[years[i - 1]] if i else Counter()
        dom = [t for t, _ in sc.most_common(6)]
        emerging = [t for t in sc if t not in prev]
        declining = [t for t in prev
                     if prev[t] >= 3 and sc.get(t, 0) <= prev[t] // 2]
        new_probs = [t for t in pc if prob_first.get(t) == y]
        persist = [t for t in pc
                   if sum(1 for yy in years[:i] if prob_counts_year[yy].get(t)) >= 2]
        solved = [t for t in pc
                  if prob_status.get(t) in ("resolved", "reduced")
                  and prob_last.get(t) == y]
        unsolved = [t for t in pc
                    if prob_status.get(t) in ("persistent", "transformed",
                                              "uncertain")]
        math_dev = []
        arch_dev = []
        comp_dev = []
        apps = []
        dirs = []
        for p in yp:
            h = harvest_global[p["id"]]
            for eq in h["technical"]["equations"][:3]:
                s = eq.get("name") or eq.get("expr", "")
                if s and s not in math_dev:
                    math_dev.append(s)
            for t in p["solutionTags"]:
                if canon_category(t) == "architecture" and t not in arch_dev:
                    if t in emerging or sc[t] >= 3:
                        arch_dev.append(t)
            for b in p["benchmarks"]:
                if b["metric"] == "FPS" and len(comp_dev) < 6:
                    comp_dev.append(f"{p['shortTitle']}: {b['value']} FPS")
            for a in p["industryApplications"]:
                if a["domain"] not in apps:
                    apps.append(a["domain"])
            for f in p["futureDirections"][:3]:
                d = f["direction"]
                if len(d) > 140:
                    d = d[:137] + "…"
                if d not in dirs:
                    dirs.append(d)
        edge = sorted(t for t in pc if t in rare_problems)
        states.append({
            "year": y,
            "paperCount": len(yp),
            "dominantApproaches": dom,
            "emergingIdeas": emerging,
            "decliningIdeas": declining,
            "persistentProblems": persist,
            "newProblems": new_probs,
            "solvedOrReducedProblems": solved,
            "unsolvedProblems": unsolved,
            "mathematicalDevelopments": math_dev[:6],
            "architecturalDevelopments": arch_dev[:8],
            "computationalDevelopments": comp_dev[:6],
            "applications": apps[:8],
            "edgeCases": edge[:6],
            "researchDirections": dirs[:8],
            "supportingPapers": [p["id"] for p in yp],
        })
    return states


def emit_years(states: list[dict]) -> None:
    (OUT / "years.ts").write_text(
        GENERATED_NOTE
        + 'import type { YearResearchState } from "./types";\n\n'
        + "export const YEAR_STATES: Record<number, YearResearchState> = "
        + ts({s["year"]: s for s in states}) + ";\n\n"
        + "export const YEARS: number[] = "
        + ts([s["year"] for s in states]) + ";\n"
    )


def build_year_deltas(states: list[dict], papers: list[dict]) -> list[dict]:
    deltas = []
    for a, b in zip(states, states[1:]):
        sa, sb = set(a["dominantApproaches"] + a["emergingIdeas"]), \
            set(b["dominantApproaches"])
        added = sorted(sb - sa)
        removed = sorted(sa - sb)
        persisted = sorted(sa & sb)
        new_probs = b["newProblems"]
        summary = (
            f"{b['year']}: {b['paperCount']} papers. "
            + (f"+{len(added)} approaches ({', '.join(added[:4])}). " if added else "")
            + (f"−{len(removed)} approaches. " if removed else "")
            + (f"New problems: {', '.join(new_probs[:3])}." if new_probs
               else "No new problem tags.")
        )
        deltas.append({
            "from": a["year"],
            "to": b["year"],
            "added": added,
            "removed": removed,
            "persisted": persisted,
            "newProblems": new_probs,
            "summary": summary,
            "supportingPapers": sorted(
                set(a["supportingPapers"]) | set(b["supportingPapers"])),
        })
    return deltas


def emit_year_deltas(deltas: list[dict]) -> None:
    (OUT / "year-deltas.ts").write_text(
        GENERATED_NOTE
        + 'import type { YearDelta } from "./types";\n\n'
        + "export const YEAR_DELTAS: YearDelta[] = " + ts(deltas) + ";\n"
    )


# -------------------------------------------------------------------- audit.ts

def emit_audit() -> None:
    (OUT / "audit.ts").write_text(
        GENERATED_NOTE
        + '''import type { AuditCheck } from "./types";
import { PAPERS, PAPER_BY_ID, PAPER_COUNT } from "./papers";
import { PROBLEM_LIFECYCLES } from "./problems";
import { SOLUTIONS } from "./solutions";
import { YEAR_STATES } from "./years";
import { RELATIONS } from "./relations";
import { BENCHMARKS } from "./benchmarks";
import { DATASETS } from "./datasets";
import { METRICS } from "./metrics";

const ids = new Set(PAPERS.map((p) => p.id));

function check(id: string, label: string, ok: boolean, detail: string): AuditCheck {
  return { id, label, pass: ok, detail };
}

/** Deterministic integrity checks over the generated corpus data.
 *  Quote-level provenance is checked in __tests__/audit.test.ts against
 *  the harvest JSON records (which are themselves verified against the
 *  extracted PDF text by scripts/od_harvest_check.py). */
export function runAudit(): AuditCheck[] {
  const checks: AuditCheck[] = [];

  const dupIds = PAPERS.length - ids.size;
  checks.push(check("unique-ids", "Every paper id is unique", dupIds === 0,
    `${dupIds} duplicate ids`));

  const badYear = PAPERS.filter((p) => !p.year);
  checks.push(check("paper-years", "Every paper has a year", badYear.length === 0,
    `${badYear.length} papers missing year`));

  const badSummary = PAPERS.filter((p) => !p.summary || !p.problemSummary);
  checks.push(check("summaries", "Every paper has summaries", badSummary.length === 0,
    `${badSummary.length} papers missing summary`));

  const noEvidence = PAPERS.filter((p) => p.evidences.length === 0);
  checks.push(check("paper-evidence", "Every paper evidences ≥1 corpus concept",
    noEvidence.length === 0, `${noEvidence.length} papers with empty evidences`));

  const problemIds = new Set(PROBLEM_LIFECYCLES.map((p) => p.id));
  const solutionIds = new Set(SOLUTIONS.map((s) => s.id));
  const badTags: string[] = [];
  for (const p of PAPERS) {
    for (const t of p.problemTags) if (!problemIds.has(t)) badTags.push(`${p.id}:${t}`);
    for (const t of p.solutionTags) if (!solutionIds.has(t)) badTags.push(`${p.id}:${t}`);
  }
  checks.push(check("tag-vocabulary",
    "Every problem/solution tag resolves to the dictionary",
    badTags.length === 0, badTags.slice(0, 5).join(", ") || "all resolve"));

  const referenced = new Set<string>();
  for (const pr of PROBLEM_LIFECYCLES)
    for (const o of pr.occurrences) for (const pid of o.papers) referenced.add(pid);
  for (const s of SOLUTIONS) for (const pid of s.paperIds) referenced.add(pid);
  for (const r of RELATIONS) { referenced.add(r.from); referenced.add(r.to); }
  for (const b of BENCHMARKS) referenced.add(b.paperId);
  for (const d of DATASETS) for (const pid of d.paperIds) referenced.add(pid);
  for (const m of METRICS) for (const pid of m.papers) referenced.add(pid);
  for (const y of Object.values(YEAR_STATES))
    for (const pid of y.supportingPapers) referenced.add(pid);
  const dangling = [...referenced].filter((pid) => !ids.has(pid));
  checks.push(check("referential-integrity",
    "Every referenced paperId resolves", dangling.length === 0,
    dangling.slice(0, 5).join(", ") || "all resolve"));

  const uncovered = PAPERS.filter(
    (p) => !YEAR_STATES[p.year] || !YEAR_STATES[p.year].supportingPapers.includes(p.id),
  );
  checks.push(check("year-coverage", "Every paper appears in its year state",
    uncovered.length === 0, `${uncovered.length} uncovered`));

  const emptyYears = Object.values(YEAR_STATES).filter(
    (y) => y.supportingPapers.length !== PAPERS.filter((p) => p.year === y.year).length,
  );
  checks.push(check("year-counts", "Year paper counts match corpus",
    emptyYears.length === 0,
    emptyYears.map((y) => String(y.year)).join(", ") || "all match"));

  const emptyProblems = PROBLEM_LIFECYCLES.filter((p) => p.occurrences.length === 0);
  checks.push(check("problem-occurrences", "Every problem has occurrences",
    emptyProblems.length === 0,
    emptyProblems.map((p) => p.id).join(", ") || "all have occurrences"));

  const summaryOk = PAPER_COUNT === PAPERS.length;
  checks.push(check("count", "PAPER_COUNT matches array length", summaryOk,
    `${PAPER_COUNT} vs ${PAPERS.length}`));

  return checks;
}

export function countPapersByYear(): Record<number, number> {
  const out: Record<number, number> = {};
  for (const p of PAPERS) out[p.year] = (out[p.year] ?? 0) + 1;
  return out;
}

export { PAPER_BY_ID };
''')


# -------------------------------------------------- analysis JSON -> TS render

ANALYSIS = PDF_DIR / "analysis"


def render_analysis() -> list[str]:
    """Render papers/object_detection/analysis/*.json into TS data files.

    Skips files that do not exist yet (review passes land them over time).
    """
    done: list[str] = []

    f = ANALYSIS / "clusters.json"
    if f.exists():
        clusters = json.loads(f.read_text())
        (OUT / "clusters.ts").write_text(
            GENERATED_NOTE
            + 'import type { ProblemCluster } from "./types";\n\n'
            + "export const CLUSTERS: ProblemCluster[] = " + ts(clusters) + ";\n\n"
            + "export const CLUSTER_BY_ID: Record<string, ProblemCluster> = "
            + "Object.fromEntries(CLUSTERS.map((c) => [c.id, c]));\n"
        )
        done.append(f"clusters.ts      {len(clusters)} clusters")

    dir_files = sorted(ANALYSIS.glob("directions*.json"))
    if dir_files:
        dirs: list[dict] = []
        for df in dir_files:
            dirs.extend(json.loads(df.read_text()))
        dirs.sort(key=lambda d: (d["sourceYear"], d["id"]))
        (OUT / "directions.ts").write_text(
            GENERATED_NOTE
            + 'import type { FutureDirection } from "./types";\n\n'
            + f"/* merged from {', '.join(d.name for d in dir_files)} */\n"
            + "export const FUTURE_DIRECTIONS: FutureDirection[] = "
            + ts(dirs) + ";\n\n"
            + "export const DIRECTION_BY_ID: Record<string, FutureDirection> = "
            + "Object.fromEntries(FUTURE_DIRECTIONS.map((d) => [d.id, d]));\n"
        )
        done.append(f"directions.ts    {len(dirs)} directions")

    f = ANALYSIS / "industry.json"
    if f.exists():
        ind = json.loads(f.read_text())
        (OUT / "industry.ts").write_text(
            GENERATED_NOTE
            + 'import type { IndustryAnalysis } from "./types";\n\n'
            + "export const INDUSTRY: IndustryAnalysis = " + ts(ind) + ";\n"
        )
        done.append(f"industry.ts      {len(ind.get('domains', []))} domains, "
                    f"{len(ind.get('gaps', []))} gaps")

    f = ANALYSIS / "saturation.json"
    if f.exists():
        sat = json.loads(f.read_text())
        (OUT / "saturation.ts").write_text(
            GENERATED_NOTE
            + 'import type { SaturationEntry } from "./types";\n\n'
            + "export const SATURATION: SaturationEntry[] = " + ts(sat) + ";\n"
        )
        done.append(f"saturation.ts    {len(sat)} entries")

    f = ANALYSIS / "crossdomain.json"
    if f.exists():
        ana = json.loads(f.read_text())
        (OUT / "crossdomain.ts").write_text(
            GENERATED_NOTE
            + 'import type { Analogy } from "./types";\n\n'
            + "export const ANALOGIES: Analogy[] = " + ts(ana) + ";\n"
        )
        done.append(f"crossdomain.ts   {len(ana)} analogies")
    return done


def emit_harvest_records(harvest: dict[str, dict]) -> str:
    """Emit every remaining harvest field (verbatim, uncapped) as a
    lazy-loadable TS module keyed by paper id."""
    out: dict[str, dict] = {}
    for pid, h in sorted(harvest.items()):
        quoted = lambda ev: [  # noqa: E731
            {k: v for k, v in e.items() if k in ("quote", "location") and v}
            for e in ev
        ]
        out[pid] = {
            "problem": {
                "summary": h["problem"]["summary"],
                "statements": h["problem"]["statements"],
                "evidence": quoted(h["problem"]["evidence"]),
            },
            "background": {
                "summary": h["background"]["summary"],
                "relatedWork": [
                    {k: v for k, v in r.items()
                     if k in ("name", "relation", "quote", "location") and v}
                    for r in h["background"]["relatedWork"]
                ],
                "evidence": quoted(h["background"]["evidence"]),
            },
            "solution": {
                "summary": h["solution"]["summary"],
                "approach": h["solution"]["approach"],
                "components": h["solution"]["components"],
                "evidence": quoted(h["solution"]["evidence"]),
            },
            "experiments": {
                "summary": h["experiments"]["summary"],
                "baselines": h["experiments"]["baselines"],
                "evidence": quoted(h["experiments"]["evidence"]),
            },
            "limitations": {
                "summary": h["limitations"]["summary"],
                "items": h["limitations"]["items"],
                "evidence": quoted(h["limitations"]["evidence"]),
            },
            "industry": {"evidence": quoted(h["industry"]["evidence"])},
            "technical": {
                "algorithms": h["technical"]["algorithms"],
                "backbones": h["technical"]["backbones"],
                "models": h["technical"]["models"],
                "equations": [
                    {k: v for k, v in eq.items()
                     if k in ("name", "expr", "location") and v}
                    for eq in h["technical"]["equations"]
                ],
            },
        }
    body = json.dumps(out, separators=(",", ":"), ensure_ascii=False)
    (OUT / "harvest-records.ts").write_text(
        GENERATED_NOTE
        + 'import type { PaperHarvest } from "./types";\n\n'
        + "/* Full harvest records, verbatim and uncapped. Imported lazily by\n"
        + " * the paper explorer so the 1.5MB payload stays out of the main chunk. */\n"
        + f"export const HARVEST_RECORDS: Record<string, PaperHarvest> = {body};\n"
    )
    n_quotes = sum(
        len(s["evidence"]) for r in out.values()
        for s in (r["problem"], r["background"], r["solution"],
                  r["experiments"], r["limitations"], r["industry"])
    )
    return (f"harvest-records.ts {len(out)} records, {n_quotes} section quotes, "
            f"{len(body) // 1024}KB")


# ------------------------------------------------------- analysis bundles

def emit_bundles(papers: list[dict], problems: list[dict], harvest: dict) -> None:
    BUNDLE.mkdir(parents=True, exist_ok=True)

    # 1. cluster candidates
    clusters = []
    for pr in problems:
        if pr["paperCount"] < 3:
            continue
        sol_counter: Counter = Counter()
        for p in papers:
            if pr["id"] in p["problemTags"]:
                for s in p["solutionTags"]:
                    sol_counter[s] += 1
        ids = sorted({pid for o in pr["occurrences"] for pid in o["papers"]})
        clusters.append({
            "problemId": pr["id"],
            "shortLabel": pr["shortLabel"],
            "problem": pr["problem"][:300],
            "paperCount": pr["paperCount"],
            "firstYear": pr["firstObservedYear"],
            "lastYear": pr["lastObservedYear"],
            "papers": ids,
            "topSolutionTags": [t for t, _ in sol_counter.most_common(8)],
            "sampleStatements": pr["statements"][:4],
            "sampleEvidence": [e for o in pr["occurrences"]
                               for e in o["evidence"]][:6],
        })
    (BUNDLE / "cluster_candidates.json").write_text(ts(clusters))

    # 2. future directions + later-paper index
    dirs = []
    for p in papers:
        for i, f in enumerate(p["futureDirections"]):
            dirs.append({
                "uid": f"{p['id']}-f{i}",
                "paperId": p["id"],
                "year": p["year"],
                "direction": f["direction"],
                "quote": f["quote"],
                "location": f.get("location"),
            })
    later = [
        {"id": p["id"], "year": p["year"], "title": p["title"],
         "solutionTags": p["solutionTags"], "problemTags": p["problemTags"],
         "summary": p["summary"][:220]}
        for p in papers
    ]
    (BUNDLE / "future_directions.json").write_text(
        ts({"directions": dirs, "papers": later}))

    # 3. industry bundle
    apps, claims = [], []
    for p in papers:
        for a in p["industryApplications"]:
            apps.append({"paperId": p["id"], "year": p["year"], **a})
        for c in p["deploymentClaims"]:
            claims.append({"paperId": p["id"], "year": p["year"], "claim": c})
    (BUNDLE / "industry_bundle.json").write_text(ts({"applications": apps,
                                                     "deploymentClaims": claims}))

    # 4. saturation bundle
    sat = []
    for pr in problems:
        per_year = {o["year"]: len(o["papers"]) for o in pr["occurrences"]}
        span = pr["lastObservedYear"] - pr["firstObservedYear"] + 1
        sat.append({
            "problemId": pr["id"],
            "shortLabel": pr["shortLabel"],
            "firstYear": pr["firstObservedYear"],
            "lastYear": pr["lastObservedYear"],
            "paperCount": pr["paperCount"],
            "attemptCount": sum(len(o["attemptedSolutions"])
                                for o in pr["occurrences"]),
            "papersPerYear": round(pr["paperCount"] / span, 2),
            "papersPerActiveYear": round(
                pr["paperCount"] / max(1, len(per_year)), 2),
            "perYear": per_year,
            "currentStatus": pr["currentStatus"],
            "statements": pr["statements"][:3],
            "recentPapers": [pid for o in pr["occurrences"][-3:]
                             for pid in o["papers"]],
        })
    (BUNDLE / "saturation_bundle.json").write_text(ts(sat))


# ------------------------------------------------------------------------ main

harvest_global: dict[str, dict] = {}


def main() -> int:
    global harvest_global
    manifest, harvest, judgments = load()
    harvest_global = harvest
    OUT.mkdir(parents=True, exist_ok=True)

    papers = build_papers(manifest, harvest)
    problems = build_problems(papers, harvest, judgments)
    solutions = build_solutions(papers, problems)
    datasets, metrics = build_datasets_metrics(papers)
    obs, best = build_benchmarks(papers)
    rels = build_relations(papers, harvest)
    states = build_years(papers, problems, judgments)
    deltas = build_year_deltas(states, papers)

    emit_papers(papers)
    emit_problems(problems)
    emit_solutions(solutions)
    emit_datasets_metrics(datasets, metrics)
    emit_benchmarks(obs, best)
    emit_relations(rels)
    emit_years(states)
    emit_year_deltas(deltas)
    emit_audit()
    emit_bundles(papers, problems, harvest)
    print(emit_harvest_records(harvest))
    for line in render_analysis():
        print(f"{line}")

    print(f"papers.ts          {len(papers)} papers")
    print(f"problems.ts        {len(problems)} problems "
          f"({sum(1 for p in problems if p['currentStatus'] != 'uncertain')} judged)")
    print(f"solutions.ts       {len(solutions)} solutions")
    print(f"datasets.ts        {len(datasets)} datasets")
    print(f"metrics.ts         {len(metrics)} metrics")
    print(f"benchmarks.ts      {len(obs)} observations, {len(best)} best-per-key")
    print(f"relations.ts       {len(rels)} paper->paper links")
    print(f"years.ts           {len(states)} year states "
          f"({states[0]['year']}-{states[-1]['year']})")
    print(f"year-deltas.ts     {len(deltas)} deltas")
    print(f"bundles            {BUNDLE.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
