#!/usr/bin/env python3
"""Object Detection corpus — continuous knowledge loop.

Safe re-ingest: PDFs dropped into papers/object_detection/ are picked up,
existing OD ids are STABLE (harvest records and analysis reference them),
new papers get fresh sequential ids, and everything downstream is re-run.

Pipeline per invocation:
  1. run od_manifest.py (network + pdftotext, cached/idempotent)
  2. restore old OD ids for known papers; assign ODnnn+1 to new papers
  3. report new papers lacking harvest -> write harvest/_batches/pending.md
  4. run od_harvest_check.py (quote chain, harvest vs PDF)
  5. run od_analysis_check.py (review-pass JSON vs manifest/PDF quotes)
  6. run od_build.py (regenerate all TS data projections)
  7. print the gate commands (lint / test / build)

Nothing here edits harvest JSON, judgments, or analysis files — those are
review passes; the loop only detects that they are needed.

Usage: python3 scripts/od_reingest.py
Exit code 0 = pipeline steps all passed (pending harvest passes are
reported, not failures).
"""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OD = ROOT / "papers" / "object_detection"
MANIFEST = OD / "manifest.json"
HARVEST = OD / "harvest"
SCRIPTS = ROOT / "scripts"


def run(script: str, *args: str) -> bool:
    print(f"\n=== {script} {' '.join(args)} ===")
    r = subprocess.run([sys.executable, str(SCRIPTS / script), *args])
    return r.returncode == 0


def identity(e: dict) -> str:
    if e.get("arxiv"):
        return f"arxiv:{e['arxiv']}"
    files = ",".join(sorted(e.get("files", [])))
    return f"files:{files}"


def main() -> int:
    old = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else []
    old_by_id = {e["id"]: e for e in old}
    old_by_ident = {identity(e): e["id"] for e in old}
    old_order = [e["id"] for e in old]
    old_max = max((int(e["id"][2:]) for e in old), default=0)

    if not run("od_manifest.py"):
        print("manifest step failed")
        return 1

    new = json.loads(MANIFEST.read_text())
    restored: list[dict] = []
    fresh: list[dict] = []
    for e in new:
        oid = old_by_ident.get(identity(e))
        if oid:
            e["id"] = oid
            restored.append(e)
        else:
            fresh.append(e)

    fresh.sort(key=lambda e: (e.get("year") or 9999, e.get("arxiv") or "zzz"))
    next_n = old_max
    for e in fresh:
        next_n += 1
        e["id"] = f"OD{next_n:03d}"

    keep = {e["id"] for e in restored}
    ordered = [e for oid in old_order if oid in keep
               for e in restored if e["id"] == oid]
    ordered.extend(fresh)
    MANIFEST.write_text(json.dumps(ordered, indent=1, ensure_ascii=False) + "\n")

    removed = [oid for oid in old_order if oid not in keep]
    print(f"\nmanifest: {len(ordered)} papers "
          f"({len(restored)} known ids stable, {len(fresh)} new, "
          f"{len(removed)} missing files)")
    for oid in removed:
        print(f"  WARNING: {oid} no longer matches any PDF — harvest/analysis "
              f"still reference it; re-add the PDF or retire the records")
    for e in fresh:
        print(f"  NEW {e['id']} ({e.get('year')}) {e['title'][:70]}")

    # ---- harvest coverage
    have = {json.loads(p.read_text())["id"] for p in HARVEST.glob("OD*.json")}
    need = [e for e in ordered if e["id"] not in have]
    if need:
        brief = HARVEST / "_batches" / "pending.md"
        brief.parent.mkdir(exist_ok=True)
        lines = ["# Pending harvest (generated by od_reingest.py)", ""]
        for e in need:
            lines.append(f"- {e['id']} ({e.get('year')}) — textFile: "
                         f"`{e['textFile']}` — {e['title']}")
        brief.write_text("\n".join(lines) + "\n")
        print(f"\nharvest: {len(need)} paper(s) missing records — see "
              f"{brief.relative_to(ROOT)}")
    else:
        brief = HARVEST / "_batches" / "pending.md"
        if brief.exists():
            brief.unlink()
        print("\nharvest: all papers have records")

    ok = True
    ids = [e["id"] for e in ordered]
    ok &= run("od_harvest_check.py", *ids)
    ok &= run("od_analysis_check.py")
    ok &= run("od_build.py")

    print("\n=== gate ===")
    print("npm run lint && npm test && npm run build")
    if need:
        print(f"REMAINING: harvest {len(need)} new paper(s), then re-run "
              f"od_reingest.py (analysis refresh may also be needed)")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
