// GENERATED by scripts/tf_build.py -- do not edit.
import type { SimulatorBinding } from "./types";

export const SIMULATOR_PAPERS: SimulatorBinding[] = [
  { id: "quantization", label: "Quantization", papers: ["T014", "T326", "T356", "T387"] },
  { id: "pruning", label: "Pruning", papers: ["T147", "T180", "T334", "T379"] },
  { id: "layer-reduction", label: "Layer reduction", papers: ["T147", "T180", "T334", "T379"] },
  { id: "distillation", label: "Distillation", papers: ["T011", "T079", "T144", "T160"] },
  { id: "peft", label: "PEFT", papers: ["T032", "T043", "T086", "T225"] },
  { id: "retrieval", label: "Retrieval", papers: ["T024", "T221", "T303", "T324"] },
  { id: "reasoning", label: "Reasoning", papers: ["T233", "T248", "T342", "T398"] },
];
